server path = '@this_is_quite_a_long_socket'
server listening socket #3
concurrent server path = '@this_is_quite_a_long_socket'
Device or resource busy, concurrent server failed to listen
server going to accept connections
server going to accept connections
client1 path = '@this_is_quite_a_long_socket'
client connection socket #4
client connected
client2 path = '@this_is_quite_a_long_socket'
client connection socket #5
client connected
received 'This is my message'
received 'Let us have another message'
message from server to client1: 'This is my message. server is alive and kicking.'
message from server to client2: 'Let us have another message. server is alive and kicking.'
client disconnected
client disconnected
