
extractParams
readline(a): 0
a

readline( 	a 	b): 0
a
b

readline(	 ab): 0
ab

readline(	 ab cd): 0
ab
cd

readline(	 ab cd	ef # blah): 0
ab
cd
ef

readline(	 'ab' 'cd'	'ef' # blah): 0
ab
cd
ef

readline(	 "ab" 'cd'	"ef" # blah): 0
ab
cd
ef

readline(	 ab cd	ef 'gh ij	kl' "mn op	qr" 	# blah): 0
ab
cd
ef
gh ij	kl
mn op	qr

readline(	 ab cd	ef 'gh "ij\'	kl' "mn 'op\"	qr" 	# blah): 0
ab
cd
ef
gh "ij'	kl
mn 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr" 	# blah): 0
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl): 1
a\b
cd
ef
g\h "ij'	kl

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr): 1
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(path "C:\Backup\"): 1
path
C:\Backup"

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path
C:\Backup



and

spaces
matter


readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path

readline(		f	blah	''): 0


f
blah


readline(		f	blah	'): 1


f
blah


readline(		f	blah		): 0


f
blah




Test: client configuration
Syntax:
  expire, occ.: optional, max = 1; params: min = max = 1
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  parsers_dir, occ.: optional, no max; params: min = max = 1
  path, occ.: min = 1, no max; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    ignore, occ.: optional, max = 1; params: min = max = 1
    no_compress, occ.: optional, max = 1; params: min = max = 1
    parser, occ.: optional, no max; params: min = max = 2
    report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
  report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
  subset, occ.: optional, max = 1; params: min = max = 1
  users, occ.: optional, max = 1; params: min = 1, no max
Test: with object
 0: root
 2:   filter and subdir
 3:     condition path_start subdir
 4:     condition !size< 100
 6:   users biloute machin
 8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Config:
2:   filter and subdir
3:     condition path_start subdir
4:     condition !size< 100
6:   users biloute machin
8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Test: server configuration
Syntax:
  client, occ.: min = 1, no max; params: min = 1, max = 2
    config, occ.: optional, max = 1; params: min = max = 1
    expire, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    hostname, occ.: optional, max = 1; params: min = max = 1
    ignore, occ.: optional, max = 1; params: min = max = 1
    option, occ.: optional, no max; params: min = 1, max = 2
    path, occ.: optional, no max; params: min = max = 1
      compress, occ.: optional, max = 1; params: min = max = 1
      filter, occ.: optional, no max; params: min = max = 2
        condition, occ.: min = 1, no max; params: min = max = 2
      ignore, occ.: optional, max = 1; params: min = max = 1
      no_compress, occ.: optional, max = 1; params: min = max = 1
      parser, occ.: optional, no max; params: min = max = 2
      report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
    protocol, occ.: optional, max = 1; params: min = max = 1
    report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
    timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
    users, occ.: optional, max = 1; params: min = 1, no max
  db, occ.: optional, max = 1; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    compress_auto, occ.: optional, max = 1; params: min = max = 0
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  log, occ.: optional, max = 1; params: min = max = 1
    backups, occ.: optional, max = 1; params: min = max = 1
    level, occ.: optional, max = 1; params: min = max = 1
    max_lines, occ.: optional, max = 1; params: min = max = 1
  parsers_dir, occ.: optional, no max; params: min = max = 1
  report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
  tree, occ.: optional, max = 1; params: min = max = 1
    compressed, occ.: optional, max = 1; params: min = max = 1
    daily, occ.: optional, max = 1; params: min = max = 1
    hourly, occ.: optional, max = 1; params: min = max = 1
    links, occ.: optional, max = 1; params: min = max = 1
    weekly, occ.: optional, max = 1; params: min = max = 1
 0: root
 1:   log hbackup.log
 2:     max_lines 100000
 3:     backups 10
 4:     level verbose
 6:   db test_db
 7:     compress auto
 9:     compress_auto
11:   tree test_tree
12:     links symbolic
13:     compressed check
14:     hourly 23
15:     daily 6
16:     weekly 52
18:   parsers_dir ../../../parsers/.libs
20:   filter all nothing
21:     condition type pipe
22:     condition size> 10
24:   ignore nothing
26:   filter all backup
27:     condition type file
28:     condition path_end ~
30:   filter any test_or
31:     condition filter backup
32:     condition !size< 1000
34:   client myClient xp
35:     protocol smb
36:     users backup
37:     config C:\Backup\Backup.LST
39:   client myClient
40:     protocol nfs
41:     users backup root
42:     hostname myClient
43:     config /home/User/hbackup.list
45:   client newClient
46:     protocol ssh
47:     option username user
48:     option password p4sS?
49:     config /home/Blah/hbackup.list
51:   client other
52:     protocol none
53:     hostname otherClient
54:     option username foo
55:     option password bar
56:     config /home/Blah/hbackup.list
58:     filter and subdir
59:       condition path_start subdir
60:       condition !size< 100
62:     filter and bigfile
63:       condition size>= 10
64:       condition type file
66:     expire 1
68:     path test2//
70:     path test1
72:       filter and not_object
73:         condition !path_end .o
75:       filter or to_be_ignored
76:         condition filter subdir
77:         condition filter backup
78:         condition !filter not_object
80:       ignore to_be_ignored
82:       compress bigfile
84:       parser cvs controlled
85:       parser svn modified
87:   client myhost
88:     report_copy_error_once
89:     protocol file
90:     hostname myhost.mynetwork.lan
91:     timeout_nowarning
92:     config etc/localhost.list
93:     expire 1
95:   client client xp
96:     ignore backup
97:     protocol smb
98:     option username Myself
99:     option password flesyM
100:     option nocase
101:     hostname myClient
102:     config C:\Backup\Backup.LST
104:   client aClient vista
105:     protocol smb
106:     filter and huge_file
107:       condition !filter backup
108:       condition !size< 100
110:     path C:\Test Dir
111:       filter and compress_m
112:         condition !filter huge_file
113:       compress compress_m
114:       ignore backup
115:       parser svn modified
116:       report_copy_error_once
Config:
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
6:   db test_db
7:     compress auto
9:     compress_auto
11:   tree test_tree
12:     links symbolic
13:     compressed check
14:     hourly 23
15:     daily 6
16:     weekly 52
18:   parsers_dir ../../../parsers/.libs
20:   filter all nothing
21:     condition type pipe
22:     condition size> 10
24:   ignore nothing
26:   filter all backup
27:     condition type file
28:     condition path_end ~
30:   filter any test_or
31:     condition filter backup
32:     condition !size< 1000
34:   client myClient xp
35:     protocol smb
36:     users backup
37:     config C:\Backup\Backup.LST
39:   client myClient
40:     protocol nfs
41:     users backup root
42:     hostname myClient
43:     config /home/User/hbackup.list
45:   client newClient
46:     protocol ssh
47:     option username user
48:     option password p4sS?
49:     config /home/Blah/hbackup.list
51:   client other
52:     protocol none
53:     hostname otherClient
54:     option username foo
55:     option password bar
56:     config /home/Blah/hbackup.list
58:     filter and subdir
59:       condition path_start subdir
60:       condition !size< 100
62:     filter and bigfile
63:       condition size>= 10
64:       condition type file
66:     expire 1
68:     path test2//
70:     path test1
72:       filter and not_object
73:         condition !path_end .o
75:       filter or to_be_ignored
76:         condition filter subdir
77:         condition filter backup
78:         condition !filter not_object
80:       ignore to_be_ignored
82:       compress bigfile
84:       parser cvs controlled
85:       parser svn modified
87:   client myhost
88:     report_copy_error_once
89:     protocol file
90:     hostname myhost.mynetwork.lan
91:     timeout_nowarning
92:     config etc/localhost.list
93:     expire 1
95:   client client xp
96:     ignore backup
97:     protocol smb
98:     option username Myself
99:     option password flesyM
100:     option nocase
101:     hostname myClient
102:     config C:\Backup\Backup.LST
104:   client aClient vista
105:     protocol smb
106:     filter and huge_file
107:       condition !filter backup
108:       condition !size< 100
110:     path C:\Test Dir
111:       filter and compress_m
112:         condition !filter huge_file
113:       compress compress_m
114:       ignore backup
115:       parser svn modified
116:       report_copy_error_once
Test: configuration save
 0: root
 1:   log hbackup.log
 2:     max_lines 100000
 3:     backups 10
 4:     level verbose
 5:   db test_db
 6:     compress auto
 7:     compress_auto
 8:   tree test_tree
 9:     links symbolic
10:     compressed check
11:     hourly 23
12:     daily 6
13:     weekly 52
14:   parsers_dir ../../../parsers/.libs
15:   filter all nothing
16:     condition type pipe
17:     condition size> 10
18:   ignore nothing
19:   filter all backup
20:     condition type file
21:     condition path_end ~
22:   filter any test_or
23:     condition filter backup
24:     condition !size< 1000
25:   client myClient xp
26:     protocol smb
27:     users backup
28:     config C:\Backup\Backup.LST
29:   client myClient
30:     protocol nfs
31:     users backup root
32:     hostname myClient
33:     config /home/User/hbackup.list
34:   client newClient
35:     protocol ssh
36:     option username user
37:     option password p4sS?
38:     config /home/Blah/hbackup.list
39:   client other
40:     protocol none
41:     hostname otherClient
42:     option username foo
43:     option password bar
44:     config /home/Blah/hbackup.list
45:     filter and subdir
46:       condition path_start subdir
47:       condition !size< 100
48:     filter and bigfile
49:       condition size>= 10
50:       condition type file
51:     expire 1
52:     path test2//
53:     path test1
54:       filter and not_object
55:         condition !path_end .o
56:       filter or to_be_ignored
57:         condition filter subdir
58:         condition filter backup
59:         condition !filter not_object
60:       ignore to_be_ignored
61:       compress bigfile
62:       parser cvs controlled
63:       parser svn modified
64:   client myhost
65:     report_copy_error_once
66:     protocol file
67:     hostname myhost.mynetwork.lan
68:     timeout_nowarning
69:     config etc/localhost.list
70:     expire 1
71:   client client xp
72:     ignore backup
73:     protocol smb
74:     option username Myself
75:     option password flesyM
76:     option nocase
77:     hostname myClient
78:     config C:\Backup\Backup.LST
79:   client aClient vista
80:     protocol smb
81:     filter and huge_file
82:       condition !filter backup
83:       condition !size< 100
84:     path C:\Test Dir
85:       filter and compress_m
86:         condition !filter huge_file
87:       compress compress_m
88:       ignore backup
89:       parser svn modified
90:       report_copy_error_once
Config:
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
5:   db test_db
6:     compress auto
7:     compress_auto
8:   tree test_tree
9:     links symbolic
10:     compressed check
11:     hourly 23
12:     daily 6
13:     weekly 52
14:   parsers_dir ../../../parsers/.libs
15:   filter all nothing
16:     condition type pipe
17:     condition size> 10
18:   ignore nothing
19:   filter all backup
20:     condition type file
21:     condition path_end ~
22:   filter any test_or
23:     condition filter backup
24:     condition !size< 1000
25:   client myClient xp
26:     protocol smb
27:     users backup
28:     config C:\Backup\Backup.LST
29:   client myClient
30:     protocol nfs
31:     users backup root
32:     hostname myClient
33:     config /home/User/hbackup.list
34:   client newClient
35:     protocol ssh
36:     option username user
37:     option password p4sS?
38:     config /home/Blah/hbackup.list
39:   client other
40:     protocol none
41:     hostname otherClient
42:     option username foo
43:     option password bar
44:     config /home/Blah/hbackup.list
45:     filter and subdir
46:       condition path_start subdir
47:       condition !size< 100
48:     filter and bigfile
49:       condition size>= 10
50:       condition type file
51:     expire 1
52:     path test2//
53:     path test1
54:       filter and not_object
55:         condition !path_end .o
56:       filter or to_be_ignored
57:         condition filter subdir
58:         condition filter backup
59:         condition !filter not_object
60:       ignore to_be_ignored
61:       compress bigfile
62:       parser cvs controlled
63:       parser svn modified
64:   client myhost
65:     report_copy_error_once
66:     protocol file
67:     hostname myhost.mynetwork.lan
68:     timeout_nowarning
69:     config etc/localhost.list
70:     expire 1
71:   client client xp
72:     ignore backup
73:     protocol smb
74:     option username Myself
75:     option password flesyM
76:     option nocase
77:     hostname myClient
78:     config C:\Backup\Backup.LST
79:   client aClient vista
80:     protocol smb
81:     filter and huge_file
82:       condition !filter backup
83:       condition !size< 100
84:     path C:\Test Dir
85:       filter and compress_m
86:         condition !filter huge_file
87:       compress compress_m
88:       ignore backup
89:       parser svn modified
90:       report_copy_error_once
Test: broken configuration
Error: at line 7: exactly 2 params required, not 1 for 'filter'
Error: at line 11: missing keyword 'condition'
Error: at line 15: at least 1 params required, not 0 for 'users'
Error: at line 17: exactly 1 params required, not 0 for 'ignore'
Error: at line 13: need at most 1 occurence(s) of 'ignore'
Error: at line 23: at most 2 params required, not 3 for 'option'
Error: at line 24: at least 1 params required, not 0 for 'option'
Error: at line 32: exactly 2 params required, not 3 for 'filter'
Error: at line 33: exactly 2 params required, not 3 for 'condition'
Error: at line 34: exactly 2 params required, not 1 for 'condition'
Error: at line 37: exactly 1 params required, not 2 for 'expire'
Error: at line 51: missing keyword 'condition'
Error: at line 53: exactly 2 params required, not 1 for 'filter'
Error: at line 53: missing keyword 'condition'
Error: at line 41: need at most 1 occurence(s) of 'compress'
Error: at line 41: need at most 1 occurence(s) of 'ignore'
Error: at line 19: need at most 1 occurence(s) of 'config'
Error: at line 19: need at most 1 occurence(s) of 'expire'
Error: at line 19: need at most 1 occurence(s) of 'hostname'
Error: at line 71: exactly 1 params required, not 2 for 'ignore'
Error: at line 72: exactly 1 params required, not 2 for 'compress'
Error: at line 85: exactly 1 params required, not 0 for 'ignore'
Error: at line 86: exactly 1 params required, not 0 for 'compress'
Error: global: need at most 1 occurence(s) of 'db'
Error: global: need at most 1 occurence(s) of 'report_copy_error_once'
Error: at line 88: incorrect or misplaced 'what_the_f...?'
failed to read config!
 0: root
 1:   db test_db
 2:   db blah
 4:   report_copy_error_once
 5:   report_copy_error_once
Config:
1:   db test_db
2:   db blah
4:   report_copy_error_once
5:   report_copy_error_once
7:   filter all
8:     condition type file
9:     condition path_end ~
11:   filter any test_or
13:   client myClient
14:     protocol nfs
15:     users
16:     ignore test_or
17:     ignore
19:   client other
20:     protocol ssh
21:     hostname otherClient
22:     hostname 192.168.0.132
23:     option I am happy
24:     option
25:     config /home/backup/Backup.list
26:     config /home/backup/Backup2.list
28:     filter and subdir
29:       condition path_start subdir
30:       condition !size< 100
32:     filter and bigfile 3
33:       condition size>= 10 yeah
34:       condition type
36:     expire 1
37:     expire 2 3
39:     path test2//
41:     path test1
43:       filter and not_object
44:         condition !path_end .o
46:       filter or to_be_ignored
47:         condition filter subdir
48:         condition filter backup
49:         condition !filter not_object
51:       filter and blah
53:       filter or
56:       ignore to_be_ignored
57:       ignore to_be_ignored2
59:       compress bigfile
60:       compress bigfile2
62:       parser cvs controlled
63:       parser svn modified
65:   client myhost
66:     hostname myhost.mynetwork.lan
67:     config etc/localhost.list
68:     expire 1
70:     path blah
71:       ignore 2 3
72:       compress 4 5
74:   client client xp
75:     protocol smb
76:     option username Myself
77:     option password flesyM
78:     option nocase
79:     hostname myClient
80:     config C:\Backup\Backup.LST
82:     path C:\Crash"
83:     path C:\Crash
84:     path blah
85:       ignore
86:       compress
