server path = '0.0.0.0:12345'
server listening socket #3
server going to accept connections
server going to accept connections
client1 path = 'localhost:12345'
client connection socket #4
client connected
client2 path = '127.0.0.1:12345'
client connection socket #5
client connected
received 'This is my message'
received 'Let us have another message'
message from server to client1: 'This is my message. server is alive and kicking.'
message from server to client2: 'Let us have another message. server is alive and kicking.'
client disconnected
client disconnected
