q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.pop enter
q1.pop exit: rc = 0
o = 20
q1.pop enter
q1.pop exit: rc = 0
o = 21
q1.pop enter
q1.pop exit: rc = 0
o = 22
q1.pop enter
q1.pop exit: rc = 0
o = 23
q1.pop enter
q1.pop exit: rc = 0
o = 24
q1.signal enter
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.push enter
q1.push exit: rc = 0
q1.pop enter
q1.pop exit: rc = 1
q1.pop enter
q1.pop exit: rc = 0
o = 25
q1.pop enter
q1.pop exit: rc = 0
o = 26
q1.pop enter
q1.pop exit: rc = 0
o = 27
q1.pop enter
q1.pop exit: rc = 0
o = 28
q1.pop enter
q1.pop exit: rc = 0
o = 29
q1.pop enter
q1.pop exit: rc = 0
o = 30
q1.pop enter
q1.pop exit: rc = 0
o = 31
q1.pop enter
q1.pop exit: rc = 0
o = 32
q1.pop enter
q1.pop exit: rc = 0
o = 33
q1.pop enter
q1.pop exit: rc = 0
o = 34
q1.signal enter
q1.pop enter
q1.pop exit: rc = 1
q1.close enter
q1.close exit
