initial (global) log level is verbose
receiver (local) log level is info
sender (global) log level is verbose
basic test
log test
receive: type=1 tag=0, len=0, value='start'
receive: type=3 tag=1, len=0, value=''
receive: type=2 tag=0, len=0, value='check'
receive: type=3 tag=18, len=27, value='I am not a stupid protocol!'
receive: type=0 tag=0, len=0, value='end'
receive: type=1 tag=0, len=0, value='start'
receive: type=3 tag=11, len=12, value='tlv_test.cpp'
receive: type=3 tag=12, len=3, value='131'
receive: type=3 tag=13, len=1, value='3'
receive: type=3 tag=14, len=1, value='0'
receive: type=3 tag=15, len=1, value='0'
receive: type=3 tag=16, len=43, value='this log should be send over the socket (9)'
receive: type=3 tag=11, len=4, value='file'
receive: type=3 tag=12, len=5, value='12345'
receive: type=3 tag=13, len=1, value='2'
receive: type=3 tag=14, len=1, value='1'
receive: type=3 tag=15, len=1, value='3'
receive: type=3 tag=16, len=34, value='this is some text with a number 17'
receive: type=0 tag=0, len=0, value='end'
receive: type=-1 tag=0, len=2, value='receiving tag and length'
