initial (global) log level is verbose
 > report 'my report' [info]:
 -> filter 'default console filter' (open) [info]:
 --> no conditions
 --> output:
 ---> console 'default console' (open) [info]
receiver (local) log level is verbose
receiver (local) log level is verbose
sender (global) log level is verbose
basic test
log test
receive: type=1 tag=65530, len=0, value=''
receive: type=3 tag=1, len=0, value=''
receive: type=2 tag=65531, len=0, value=''
receive: type=3 tag=18, len=27, value='I am not a stupid protocol!'
receive: type=0 tag=65532, len=0, value=''
receive: type=1 tag=65530, len=0, value=''
receive: type=3 tag=65520, len=12, value='tlv_test.cpp'
receive: type=3 tag=65521, len=3, value='146'
receive: type=3 tag=65522, len=4, value='main'
receive: type=3 tag=65523, len=1, value='4'
receive: type=3 tag=65524, len=1, value='0'
receive: type=3 tag=65525, len=1, value='2'
receive: type=3 tag=65526, len=7, value='7654321'
receive: type=3 tag=65527, len=1, value='0'
receive: type=3 tag=65528, len=0, value=''
receive: type=3 tag=65529, len=43, value='this log should be send over the socket (9)'
 --> this log should be send over the socket (9)
receive: type=3 tag=65520, len=12, value='tlv_test.cpp'
receive: type=3 tag=65521, len=3, value='148'
receive: type=3 tag=65522, len=4, value='main'
receive: type=3 tag=65523, len=1, value='3'
receive: type=3 tag=65524, len=1, value='0'
receive: type=3 tag=65525, len=2, value='-1'
receive: type=3 tag=65526, len=2, value='-1'
receive: type=3 tag=65527, len=1, value='0'
receive: type=3 tag=65528, len=0, value=''
receive: type=3 tag=65529, len=39, value='this one too, but without thread ID (9)'
this one too, but without thread ID (9)
receive: type=3 tag=65520, len=4, value='file'
receive: type=3 tag=65521, len=5, value='12345'
receive: type=3 tag=65522, len=0, value=''
receive: type=3 tag=65523, len=1, value='2'
receive: type=3 tag=65524, len=1, value='0'
receive: type=3 tag=65525, len=2, value='-1'
receive: type=3 tag=65526, len=7, value='7654321'
receive: type=3 tag=65527, len=2, value='15'
receive: type=3 tag=65528, len=15, value='12345'
receive: type=3 tag=65529, len=34, value='this is some text with a number 17'
Warning: this is some text with a number 17
	00000000  31 32 33 34 35 00 09 0a  1f 20 7e 7f 80 5a 61     |12345.... ~..Za|
	0000000f
receive: type=3 tag=65520, len=12, value='tlv_test.cpp'
receive: type=3 tag=65521, len=3, value='153'
receive: type=3 tag=65522, len=4, value='main'
receive: type=3 tag=65523, len=1, value='3'
receive: type=3 tag=65524, len=1, value='0'
receive: type=3 tag=65525, len=2, value='-1'
receive: type=3 tag=65526, len=2, value='-1'
receive: type=3 tag=65527, len=1, value='0'
receive: type=3 tag=65528, len=0, value=''
receive: type=3 tag=65529, len=28, value='message sent twice to socket'
message sent twice to socket
receive: type=3 tag=65520, len=12, value='tlv_test.cpp'
receive: type=3 tag=65521, len=3, value='153'
receive: type=3 tag=65522, len=4, value='main'
receive: type=3 tag=65523, len=1, value='3'
receive: type=3 tag=65524, len=1, value='0'
receive: type=3 tag=65525, len=2, value='-1'
receive: type=3 tag=65526, len=2, value='-1'
receive: type=3 tag=65527, len=1, value='0'
receive: type=3 tag=65528, len=0, value=''
receive: type=3 tag=65529, len=28, value='message sent twice to socket'
message sent twice to socket
receive: type=0 tag=65532, len=0, value=''
receive: type=-1 tag=0, len=0, value='connection closed by sender'
