#!/bin/sh

# Check arguments
if [ -z "$1" ]; then
  echo "Too few arguments"
  exit 1
fi

# Path to scripts
WHERE=`dirname $0`

# Get data
. $WHERE/interpret $1

output="$DIR/test/$NAME.all"
expected="$DIR/test/$NAME.exp"

# Check output file presence
if [ ! -r "$output" ]; then
  echo "File '$output' does not exist"
  exit 2
fi

# Launch diff-er in the background
tkdiff "$expected" "$output" &

exit 0
