#!/bin/bash -e

echo "$0" >&2

# Set mask
umask 0022

# Dir names
CONFIGDIR="etc"

TESTDIR="test1"

# Create given directory, enter it
if [ -n "$1" ]; then
  rm -rf "$1" && mkdir "$1" && cd "$1" || exit 1
else
  # Clean
  rm -rf "$CONFIGDIR"
  rm -rf "$TESTDIR"
fi

# Create environment file
cat << EOF >> test_env
export CONFIGDIR="$CONFIGDIR"
export TESTDIR="$TESTDIR"
EOF

# Test bench
mkdir "$TESTDIR"
mkdir "$TESTDIR/testdir"
echo "Hello world!" > "$TESTDIR/testfile"
touch -d "20061022 GMT" "$TESTDIR/testfile"
chmod 750 "$TESTDIR/testfile"
touch "$TESTDIR/testfile~"
ln -s "testfile" "$TESTDIR/testlink"
mkfifo "$TESTDIR/testpipe"

# Filters test
mkdir "$TESTDIR/subdir"
echo "Hello Moon!" > "$TESTDIR/subdir/testfile"
touch "$TESTDIR/subdir/testfile1"
echo "Hello Moon!" > "$TESTDIR/subdir/testfile2"
touch "$TESTDIR/test space"
mkdir "$TESTDIR/dir space"
touch "$TESTDIR/dir space/file space"
ln -s "linked space" "$TESTDIR/dir space/link space"

# Big file
dd if=/dev/zero of=test1/big_file bs=1M count=10 status=noxfer 2> /dev/null

# Long link
ln -s "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" "test1/longlink"

# Strange names
touch "`echo -e "$TESTDIR/strange1\\01TAB\\tCR\\r"`"
touch "`echo -e "$TESTDIR/strange2\\01TAB\\tLF\\n"`"
touch "`echo -e "$TESTDIR/strange3\\01TAB\\tLF\\nCR\\r"`"

# Server config
mkdir "$CONFIGDIR"
cat << EOF > "$CONFIGDIR/hbackup.conf"
log "hbackup.log"
  max_lines 100000
  backups 10
  level verbose

db "test_db"
  compress auto
  # Check backwards compatibility
  compress_auto

tree "test_tree"
  links symbolic
  compressed check
  hourly 23
  daily 6
  weekly 52

parsers_dir ../../../parsers/.libs

filter all nothing
  condition type pipe
  condition size> 10

ignore nothing

filter all backup
  condition type file
  condition path_end ~

filter any test_or
  condition filter backup
  condition !size< 1000

client myClient xp
  protocol smb
  users backup
  config C:\Backup\Backup.LST

client myClient
  protocol nfs
  users backup root
  hostname myClient
  config /home/User/hbackup.list

client newClient
  protocol ssh
  option username user
  option password p4sS?
  config /home/Blah/hbackup.list

client other
  protocol none
  hostname otherClient
  option username foo
  option password bar
  config /home/Blah/hbackup.list
  # This is a comment
  filter and subdir
    condition path_start subdir
    condition !size< 100

  filter and bigfile
    condition size>= 10
    condition type file

  expire 1

  path test2//

  path "test1" # should work

    filter and not_object
      condition !path_end ".o"

    filter or to_be_ignored
      condition filter subdir
      condition filter backup
      condition !filter not_object

    ignore to_be_ignored

    compress bigfile

    parser cvs controlled
    parser svn modified

client myhost
  report_copy_error_once
  protocol file
  hostname myhost.mynetwork.lan
  timeout_nowarning
  config "$CONFIGDIR/localhost.list"
  expire 1

client client xp
  ignore backup
  protocol smb
  option username Myself
  option password flesyM
  option nocase
  hostname myClient
  config "C:\Backup\Backup.LST"

client aClient vista
  protocol smb
  filter and huge_file
    condition !filter backup
    condition !size< 100
  # Cannot end in \", would fail
  path "C:\Test Dir"
    filter and compress_m
      condition !filter huge_file
    compress compress_m
    ignore backup
    parser svn modified
    report_copy_error_once
EOF

# Client config
cat << EOF > "$CONFIGDIR/localhost.list"
# This is a comment
filter and subdir
  condition path_start subdir
  condition !size< 100
EOF
echo -e "\r" >> "$CONFIGDIR/localhost.list"
cat << EOF >> "$CONFIGDIR/localhost.list"
users biloute machin

ignore backup

filter and bigfile
  condition size>= 10
  condition type file

expire 1

path test2//

path "test1" # should work

  filter and not_object
    condition !path_end ".o"

  filter or to_be_ignored
    condition filter subdir
    condition !filter not_object

  ignore to_be_ignored

  compress bigfile

  parser cvs controlled
  parser svn modified

  filter and cvs_entries
    condition name Entries

  no_compress cvs_entries
EOF

# Broken config
cat << EOF > "$CONFIGDIR/broken.conf"
db "test_db"
db blah

report_copy_error_once
report_copy_error_once

filter all
  condition type file
  condition path_end ~

filter any test_or

client myClient
  protocol nfs
  users
  ignore test_or
  ignore

client other
  protocol ssh
  hostname otherClient
  hostname 192.168.0.132
  option I am happy
  option
  config /home/backup/Backup.list
  config /home/backup/Backup2.list
  # This is a comment
  filter and subdir
    condition path_start subdir
    condition !size< 100

  filter and bigfile 3
    condition size>= 10 yeah
    condition type

  expire 1
  expire 2 3

  path test2//

  path "test1" # should work

    filter and not_object
      condition !path_end ".o"

    filter or to_be_ignored
      condition filter subdir
      condition filter backup
      condition !filter not_object

    filter and blah

    filter or


    ignore to_be_ignored
    ignore to_be_ignored2

    compress bigfile
    compress bigfile2

    parser cvs controlled
    parser svn modified

client myhost
  hostname myhost.mynetwork.lan
  config "$CONFIGDIR/localhost.list"
  expire 1

  path blah
    ignore  2 3
    compress 4 5

client client xp
  protocol smb
  option username Myself
  option password flesyM
  option nocase
  hostname myClient
  config "C:\Backup\Backup.LST"

  path "C:\Crash\"
  path "C:\Crash\

  path blah
    ignore
    compress

what_the_f...?
EOF

cd ..
# --remove-files broken in tar 1.23
tar -c -z -f $1.tar.gz $1
rm -rf $1
