#!/bin/sh

target="$1"
test_dir="${target}_test_dir"

# Create test directory, enter it
rm -rf "$test_dir" && cp -a test_dir "$test_dir" && cd "$test_dir" || exit 1

# Get environment variables
. ./test_env || exit 1

expected="../$target".exp
output="../$target".all
success="../$target".done
executable="../${target}_test"

# Set path to access test scripts in priority
OLD_PATH=$PATH
export PATH=../../../test_tools:$PATH

# Cleanup previous attempt, if any
rm -f "$output" "$success"

# Run
if ! "$executable" 2>&1 | sed "s/\r/\\\r\n/g" > "$output"; then
	exit 2
fi

# Revert path
PATH=$OLD_PATH

# Check
if ! diff -q "$expected" "$output" > /dev/null; then
	echo "$target: error: test output is different from expected" >&2
	exit 3
fi

# Cleanup
rm -f "$output"

# Success
touch "$success"
exit 0
