#!/bin/sh

target="$1"
test_dir="${target}_test_dir"

# Create test directory, enter it
rm -rf "$test_dir" && cp -a test_dir "$test_dir" && cd "$test_dir" || exit 1

expected="../$target".exp
output="../$target".all
executable="../${target}_test"

# Set path to access test scripts in priority
OLD_PATH=$PATH
export PATH=../../../test_tools:$PATH

# Cleanup previous attempt, if any
rm -f "$output"

# Run
if ! "$executable" > "$output" 2>&1; then
	exit 2
fi

# Revert path
PATH=$OLD_PATH

# Check
if ! diff -q "$expected" "$output" > /dev/null; then
	echo "$target: error: test output is different from expected" >&2
	exit 3
fi

# Cleanup
rm -f "$output"
exit 0
