#!/bin/bash

# Set mask
umask 0022

# Dir names
CONFIGDIR="etc"
TESTDIR="test1"
TESTDIR2="test2"
TESTDIRCIFS="test_cifs"
TESTDIRNFS="test_nfs"
TESTDIRUSER="test_user"
TESTDBDIR="test_db"
TESTRESTORE="test_r"

ROOTDIRNFS="/home/User"

# Clean
if [ -d "$TESTDBDIR" ]; then
  chmod -R 755 "$TESTDBDIR"
fi
rm -rf "$CONFIGDIR"
rm -rf "$TESTDBDIR"
rm -rf "$TESTDIR"
rm -rf "$TESTDIR2"
rm -rf "$TESTDIRCIFS"
rm -rf "$TESTDIRNFS"
rm -rf "$TESTDIRUSER"
rm -rf "$TESTRESTORE"

if [ "$1" == "clean" ]; then
  exit 0
fi

# Test bench
mkdir "$TESTDIR"
mkdir "$TESTDIR/testdir"
echo "Hello world!" > "$TESTDIR/testfile"
touch -d 20061022 "$TESTDIR/testfile"
touch "$TESTDIR/testfile~"
ln -s "testfile" "$TESTDIR/testlink"
mkfifo "$TESTDIR/testpipe"

# Filters test
mkdir "$TESTDIR/subdir"
echo "Hello Moon!" > "$TESTDIR/subdir/testfile"
touch "$TESTDIR/subdir/testfile1"
echo "Hello Moon!" > "$TESTDIR/subdir/testfile2"
touch "$TESTDIR/test space"
mkdir "$TESTDIR/dir space"
touch "$TESTDIR/dir space/file space"

# CVS test
CVSDIR="$TESTDIR/cvs"
mkdir "$CVSDIR"
touch "$CVSDIR/filemod.o"
touch "$CVSDIR/filenew.c"
touch "$CVSDIR/fileoth"
touch "$CVSDIR/fileutd.h"
mkdir "$CVSDIR/dirbad"
touch "$CVSDIR/dirbad/fileoth"
touch "$CVSDIR/dirbad/fileutd"
mkdir "$CVSDIR/diroth"
mkdir "$CVSDIR/dirutd"
touch "$CVSDIR/dirutd/fileoth"
touch "$CVSDIR/dirutd/fileutd"
mkdir "$CVSDIR/dirutd/CVS"
cat << EOF > "$CVSDIR/dirutd/CVS/Entries"
/fileutd/1.2/Wed Oct  4 18:04:40 2006//
D
EOF
mkdir "$CVSDIR/CVS"
cat << EOF > "$CVSDIR/CVS/Entries"
/filenew.c/0/dummy timestamp//
/filemod.o/1.1/Mon Oct  2 16:27:11 2006//D2007.12.16.23.00.00
/fileutd.h/1.2/Wed Oct  4 18:04:40 2006//
D/dirbad////
D/dirutd////
EOF

# Multiple backup
mkdir "$TESTDIR2"
mkdir "$TESTDIR2/testdir"
dd if=/dev/zero of="$TESTDIR2/testfile" bs=142 count=1024 2> /dev/null
touch -t 200610221134.56 "$TESTDIR2/testfile"
dd if=/dev/zero of="$TESTDIR2/testfile~" bs=512 count=1024 2> /dev/null
dd if=/dev/zero of="$TESTDIR2/testfile2" bs=253 count=1024 2> /dev/null
ln -s "testfile" "$TESTDIR2/testlink"

# CIFS test
mkdir -p "$TESTDIRCIFS/Backup"
mkdir -p "$TESTDIRCIFS/Test"
touch "$TESTDIRCIFS/Test/File.TXT"
mkdir -p "$TESTDIRCIFS/Test/Dir"
echo 1 > "$TESTDIRCIFS/Test/Dir/a File.TXT"
echo 2 > "$TESTDIRCIFS/Test/Dir/another File.TXT"
cat << EOF > "$TESTDIRCIFS/Backup/Backup.LST"
path "C:\Test" # Do not end it in \" !!!
EOF

# NFS test
mkdir -p "$TESTDIRNFS/test"
touch "$TESTDIRNFS/test/File2.txt"
mkdir -p "$TESTDIRNFS/test/dir"
echo 3 > "$TESTDIRNFS/test/dir/file3.txt"
mkdir -p "$TESTDIRNFS/test2"
touch "$TESTDIRNFS/test2/File3.txt"
touch "$TESTDIRNFS/test2/File4.txt"
cat << EOF > "$TESTDIRNFS/hbackup.list"
path "$ROOTDIRNFS/test/"
EOF

# User-mode test
mkdir -p "$TESTDIRUSER/testuser"
echo 10 > "$TESTDIRUSER/testuser/f1.txt"
mkdir -p "$TESTDIRUSER/testuser/subdir"
echo 20 > "$TESTDIRUSER/testuser/subdir/f2.txt"
mkdir -p "$TESTDIRUSER/testuser/subdir2"
echo 30 > "$TESTDIRUSER/testuser/subdir2/f3.txt"
echo 40 > "$TESTDIRUSER/testuser/subdir2/f4.txt"
mkdir -p "$TESTDIRUSER/.hbackup"
cat << EOF > "$TESTDIRUSER/.hbackup/config"
path "~/testuser/"
EOF

# Restore
mkdir -p "$TESTRESTORE"

# Config
mkdir "$CONFIGDIR"
cat << EOF > "$CONFIGDIR/hbackup.conf"
db "$TESTDBDIR"
trash 1

filter all backup
condition type file
condition path_end ~

filter any test_or
condition filter backup
condition !size< 1000

client nfs myClient
hostname myClient
config $ROOTDIRNFS/hbackup.list

client ssh other
hostname otherClient
config /home/backup/Backup.list

client file myhost
hostname myhost.mynetwork.lan
config "$CONFIGDIR/localhost.list"
expire 1

client smb client
option username Myself
option password flesyM
option nocase
hostname myClient
config "C:\Backup\Backup.LST"
EOF

cat << EOF > "$CONFIGDIR/localhost.list"
# This is a comment
filter and subdir
condition path_start subdir
condition !size< 100

filter and bigfile
condition size>= 10
condition type file

expire 1

path test2//

path "test1" # should work

filter and not_object
condition !path_end ".o"

filter or to_be_ignored
condition filter subdir
condition filter backup
condition !filter not_object

ignore to_be_ignored

compress bigfile

parser cvs controlled
EOF
