#!/bin/bash
#
# Wrapper around make, to colorize based on keywords
# This is inspired by colormake.
#

colorize() {
  while read; do
    if echo "$REPLY" | grep -i "\(error[: ]\|failed\)" > /dev/null; then
      # Print errors in red
      echo -e "\033[31m$REPLY\033[0m"
    elif echo "$REPLY" | grep --color -F "***" > /dev/null; then
      # Print errors in red
      echo -e "\033[31m$REPLY\033[0m"
    elif echo "$REPLY" | grep -i "warning[: ]" > /dev/null; then
      # Print warnings in orange
      echo -e "\033[33m$REPLY\033[0m"
    elif echo "$REPLY" | grep -i "\(success[: ]\|passed\)" > /dev/null; then
      # Print successes in green
      echo -e "\033[32m$REPLY\033[0m"
    elif echo "$REPLY" | grep -e "^make" > /dev/null; then
      # Print make commands in light grey
      echo -e "\033[37m$REPLY\033[0m"
    elif echo "$REPLY" | grep -e "^[^ ]*: " > /dev/null; then
      # Print info in blue
      echo -e "\033[36m$REPLY\033[0m"
    else
      echo "$REPLY"
    fi
  done
}

# Determine what program to call
make $@ 2>&1 | colorize
exit ${PIPESTATUS[0]}
