#!/bin/bash

colorize() {
  while read; do
    if echo $REPLY | grep -e "^make" > /dev/null; then
      echo -e "\033[37m$REPLY\033[0m"
    elif echo $REPLY | grep -e "^creating " > /dev/null; then
      echo -e "\033[32m$REPLY\033[0m"
    elif echo $REPLY | grep -i "error: " > /dev/null; then
      # Print errors in red
      echo -e "\033[31m$REPLY\033[0m"
    elif echo $REPLY | grep -i "warning: " > /dev/null; then
      # Print warnings in orange
      echo -e "\033[33m$REPLY\033[0m"
    elif echo $REPLY | grep -e "^[^ ]*\.[^ ]*: " > /dev/null; then
      echo -e "\033[36m$REPLY\036[0m"
    else
      # Print info in blue
      echo "$REPLY"
    fi
  done
}

make $@ 2>&1 | colorize
exit ${PIPESTATUS[0]}
