Version
HBackup (c) 2006-2008 Hervé Fache version 0.9a
Help
HBackup (c) 2006-2008 Hervé Fache
  -v,  --verbose
    Be verbose about actions

  -u,  --user
    Perform user-mode backup

  -t,  --check
    Check DB for corrupted data

  -s,  --scan
    Scan DB for missing data

  -r <directory>,  --restore <directory>
    Restore to directory

  -q,  --quiet
    Be quiet

  -P <path>,  --path <path>
    Specify path

  -p,  --pretend
    Only check configuration

  -l,  --list
    List available data

  -i,  --initialize
    Initialize if needed

  -f,  --fix
    Fix backup database

  -D <UNIX epoch>,  --date <UNIX epoch>
    Specify date

  -d,  --debug
    Print debug information

  -C <client>,  --client <client>  (accepted multiple times)
    Specify client name

  -c <file name>,  --config <file name>
    Specify configuration file

  --,  --ignore_rest
    Ignores the rest of the labeled arguments following this flag.

  --version
    Displays version information and exits.

  -h,  --help
    Displays usage information and exits.

Error
Error: -! -- Couldn't find match for argument
HBackup (c) 2006-2008 Hervé Fache
  -v,  --verbose
    Be verbose about actions

  -u,  --user
    Perform user-mode backup

  -t,  --check
    Check DB for corrupted data

  -s,  --scan
    Scan DB for missing data

  -r <directory>,  --restore <directory>
    Restore to directory

  -q,  --quiet
    Be quiet

  -P <path>,  --path <path>
    Specify path

  -p,  --pretend
    Only check configuration

  -l,  --list
    List available data

  -i,  --initialize
    Initialize if needed

  -f,  --fix
    Fix backup database

  -D <UNIX epoch>,  --date <UNIX epoch>
    Specify date

  -d,  --debug
    Print debug information

  -C <client>,  --client <client>  (accepted multiple times)
    Specify client name

  -c <file name>,  --config <file name>
    Specify configuration file

  --,  --ignore_rest
    Ignores the rest of the labeled arguments following this flag.

  --version
    Displays version information and exits.

  -h,  --help
    Displays usage information and exits.

List clients (missing DB path)
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Showing list
Error: Given DB path does not exist: test_db
List clients (empty DB path)
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Showing list
Error: Given DB path does not contain a database: test_db
Backup, DB missing
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Backing up in server mode
Error: Given DB path does not exist: test_db
Typical backup, initialize DB
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Backing up in server mode
Database initialized in test_db
Database open in read/write mode
Trying client 'client' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test
 ----> Filter and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Reading list of missing checksums
Created client.xp's list
Database client client.xp open in read/write mode
Backup path: C:/Test
A C:/Test/Dir
 -> Dir Dir
A C:/Test/Dir/a File.TXT (2 B)
Adding file data to DB for b026324c6904b2a9cb4b88d6d61c81d1-0
A C:/Test/Dir/another File.TXT (2 B)
Adding file data to DB for 26ab0db90d72e28ad0ba1e22ee510510-0
A C:/Test/File.TXT (0 B)
Adding file data to DB for d41d8cd98f00b204e9800998ecf8427e-0
Database client client.xp modified
Database client client.xp closed
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
Backing up client
Created myClient's list
Database client myClient open in read/write mode
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
A /home/User/test/File2.txt (0 B)
A /home/User/test/dir
 -> Dir dir
A /home/User/test/dir/file3.txt (2 B)
Adding file data to DB for 6d7fce9fee471194aa8b5b6e47267f03-0
Database client myClient modified
Database client myClient closed
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter and not_object
 -----> Condition: not path_end .o
 ----> Filter or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter:   to_be_ignored
 ---> Path: test2
Backing up client
Created myhost's list
Database client myhost open in read/write mode
Backup path: test1
A test1/big_file (10 MB)
Done:   3.9%\r
Done:   7.8%\r
Done:  11.7%\r
Done:  15.6%\r
Done:  19.5%\r
Done:  23.4%\r
Done:  27.3%\r
Done:  31.2%\r
Done:  35.2%\r
Done:  39.1%\r
Done:  43.0%\r
Done:  46.9%\r
Done:  50.8%\r
Done:  54.7%\r
Done:  58.6%\r
Done:  62.5%\r
Done:  66.4%\r
Done:  70.3%\r
Done:  74.2%\r
Done:  78.1%\r
Done:  82.0%\r
Done:  85.9%\r
Done:  89.8%\r
Done:  93.8%\r
Done:  97.7%\r
            \r
Adding compressed file data to DB for f1c9645dbc14efddc7d8a322685f26eb-0
A test1/cvs
 -> Dir cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
A test1/cvs/CVS
 -> Dir cvs/CVS
A test1/cvs/CVS/Entries (161 B)
Adding compressed file data to DB for fef51838cd3cfe8ed96355742eb71fbd-0
A test1/cvs/CVS/Root (16 B)
Adding compressed file data to DB for b90f8fa56ea1d39881d4a199c7a81d35-0
A test1/cvs/dirbad
 -> Dir cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
A test1/cvs/dirutd
 -> Dir cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
A test1/cvs/dirutd/CVS
 -> Dir cvs/dirutd/CVS
A test1/cvs/dirutd/CVS/Entries (42 B)
Adding compressed file data to DB for 5252f242d27b8c2c9fdbdcbb33545d07-0
A test1/cvs/dirutd/CVS/Root (10 B)
Adding compressed file data to DB for eb75fb33b2019ef3c840eb5ccdc2e795-0
A test1/cvs/dirutd/fileutd (0 B)
A test1/cvs/filenew.c (0 B)
A test1/cvs/fileutd.h (0 B)
A test1/dir space
 -> Dir dir space
A test1/dir space/file space (0 B)
A test1/svn
 -> Dir svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
A test1/svn/.svn
 -> Dir svn/.svn
A test1/svn/.svn/entries (77 B)
Adding compressed file data to DB for 0f2ea973d77135dc3d06c8e68da6dc59-0
A test1/svn/dirbad
 -> Dir svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
A test1/svn/dirutd
 -> Dir svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
A test1/svn/dirutd/.svn
 -> Dir svn/dirutd/.svn
A test1/svn/dirutd/.svn/entries (30 B)
Adding compressed file data to DB for 8bdef5751e46ed57d237cbe3f4a5061c-0
A test1/svn/dirutd/fileutd (0 B)
A test1/svn/filenew.c (0 B)
A test1/test space (0 B)
A test1/testdir
 -> Dir testdir
A test1/testfile (13 B)
Adding compressed file data to DB for 59ca0efa9f5633cb0371bbc0355478d8-0
A test1/testlink
A test1/testpipe
Backup path: test2
A test2/testdir
 -> Dir testdir
A test2/testfile (145 kB)
Adding file data to DB for 3d546a1ce46c6ae10ad34ab8a81c542e-0
A test2/testfile2 (259 kB)
Adding file data to DB for fb00cd74a5f35e89a7fbdd3c1d05375a-0
A test2/testfile~ (524 kB)
Done:  78.1%\r
            \r
Adding file data to DB for 59071590099d21dd439896592338bf95-0
A test2/testlink
Database client myhost modified
Database client myhost closed
Trying client 'other' using protocol 'ssh'
Error: Protocol not supported: ssh
Database closed
Specify clients
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> client.xp
 --> myhost
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Backing up in server mode
Database open in read/write mode
Trying client 'client' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test
 ----> Filter and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Reading list of missing checksums
Database client client.xp open in read/write mode
Backup path: C:/Test
 -> Dir Dir
Database client client.xp closed
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter and not_object
 -----> Condition: not path_end .o
 ----> Filter or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter:   to_be_ignored
 ---> Path: test2
Backing up client
Database client myhost open in read/write mode
Backup path: test1
 -> Dir cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir cvs/CVS
 -> Dir cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir cvs/dirutd/CVS
 -> Dir dir space
 -> Dir svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
 -> Dir svn/.svn
 -> Dir svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
 -> Dir svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
 -> Dir svn/dirutd/.svn
 -> Dir testdir
Backup path: test2
 -> Dir testdir
Database client myhost closed
Database closed
User-mode backup
Backing up in user mode
Database initialized in test_user/.hbackup
Database open in read/write mode
 -> Reading client configuration file
Configuration:
 -> Client: localhost
 --> Protocol: file
 --> Config: test_user/.hbackup/config
 --> Expiry: none
 --> Paths: 
 ---> Path: test_user/testuser
Backing up client
Reading list of missing checksums
Created localhost's list
Database client localhost open in read/write mode
Backup path: test_user/testuser
A test_user/testuser/f1.txt (3 B)
Adding file data to DB for 31d30eea8d0968d6458e0ad0027c9f80-0
A test_user/testuser/subdir
 -> Dir subdir
A test_user/testuser/subdir/f2.txt (3 B)
Adding file data to DB for dbbf8220893d497d403bb9cdf49db7a4-0
A test_user/testuser/subdir2
 -> Dir subdir2
A test_user/testuser/subdir2/f3.txt (3 B)
Adding file data to DB for d5b4c7d9b06b60a7846c4529834c9812-0
A test_user/testuser/subdir2/f4.txt (3 B)
Adding file data to DB for 90e2a51705594d033a3abe9d77b2b7ad-0
Database client localhost modified
Database client localhost closed
Database closed
Fix DB
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Fixing database
Database open in read/write mode
Database closed
Scan DB
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Scanning database
Database open in read/write mode
Reading client.xp's list
Reading myClient's list
Reading myhost's list
Found 15 checksums
Crawling through DB
0f2ea973d77135dc3d06c8e68da6dc59-0\r
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
59ca0efa9f5633cb0371bbc0355478d8-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
b90f8fa56ea1d39881d4a199c7a81d35-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
fef51838cd3cfe8ed96355742eb71fbd-0\r
                                  \r
Found 15 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Database closed
Check DB
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Checking database
Database open in read-only mode
Crawling through DB data
0f2ea973d77135dc3d06c8e68da6dc59-0\r
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
59ca0efa9f5633cb0371bbc0355478d8-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
b90f8fa56ea1d39881d4a199c7a81d35-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
fef51838cd3cfe8ed96355742eb71fbd-0\r
                                  \r
Found 15 valid and 0 broken data files
Database closed
List clients
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Showing list
Database open in read-only mode
Database closed
 client.xp
 myClient
 myhost
Try to list paths in both myhost and smb://client (fails)
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> myhost
 --> smb://client
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Showing list
Error: Maximum one client allowed
List paths in myhost
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> myhost
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Showing list
Database open in read-only mode
Database client myhost open in read-only mode
Database client myhost closed
Database closed
 test1
 test2
List paths in myhost under test2/
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> myhost
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Showing list
Database open in read-only mode
Database client myhost open in read-only mode
Database client myhost closed
Database closed
 test2/testdir
 test2/testfile
 test2/testfile2
 test2/testfile~
 test2/testlink
List paths in myhost under test1/cvs
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> myhost
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Showing list
Database open in read-only mode
Database client myhost open in read-only mode
Database client myhost closed
Database closed
 test1/cvs/CVS
 test1/cvs/dirbad
 test1/cvs/dirutd
 test1/cvs/filenew.c
 test1/cvs/fileutd.h
Restore a file
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> myhost
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Restoring
Database open in read-only mode
Database client myhost open in read-only mode
U test_r/test2/testfile
Database client myhost closed
Database closed
Restore all data in a client/dir path that's not by itself in DB
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> myhost
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Restoring
Database open in read-only mode
Database client myhost open in read-only mode
U test_r/test1/big_file
U test_r/test1/cvs
U test_r/test1/cvs/CVS
U test_r/test1/cvs/CVS/Entries
U test_r/test1/cvs/CVS/Root
U test_r/test1/cvs/dirbad
U test_r/test1/cvs/dirutd
U test_r/test1/cvs/dirutd/CVS
U test_r/test1/cvs/dirutd/CVS/Entries
U test_r/test1/cvs/dirutd/CVS/Root
U test_r/test1/cvs/dirutd/fileutd
U test_r/test1/cvs/filenew.c
U test_r/test1/cvs/fileutd.h
U test_r/test1/dir space
U test_r/test1/dir space/file space
U test_r/test1/svn
U test_r/test1/svn/.svn
U test_r/test1/svn/.svn/entries
U test_r/test1/svn/dirbad
U test_r/test1/svn/dirutd
U test_r/test1/svn/dirutd/.svn
U test_r/test1/svn/dirutd/.svn/entries
U test_r/test1/svn/dirutd/fileutd
U test_r/test1/svn/filenew.c
U test_r/test1/test space
U test_r/test1/testdir
U test_r/test1/testfile
U test_r/test1/testlink
U test_r/test1/testpipe
Database client myhost closed
Database closed
Restore all data in a client/dir path
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> myhost
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Restoring
Database open in read-only mode
Database client myhost open in read-only mode
U test_r/test1/cvs
U test_r/test1/cvs/CVS
U test_r/test1/cvs/CVS/Entries
U test_r/test1/cvs/CVS/Root
U test_r/test1/cvs/dirbad
U test_r/test1/cvs/dirutd
U test_r/test1/cvs/dirutd/CVS
U test_r/test1/cvs/dirutd/CVS/Entries
U test_r/test1/cvs/dirutd/CVS/Root
U test_r/test1/cvs/dirutd/fileutd
U test_r/test1/cvs/filenew.c
U test_r/test1/cvs/fileutd.h
Database client myhost closed
Database closed
Restore all data in a client
 -> Reading configuration file 'etc/hbackup.conf'
Warning: Keyword trash is deprecated and will be removed in the next
version of this software, please remove it from your configuration
Configuration:
 -> DB path: test_db
 -> Selected clients:
 --> myhost
 -> Clients:
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: none
 -> Filter and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Restoring
Database open in read-only mode
Database client myhost open in read-only mode
U test_r/test1/big_file
U test_r/test1/cvs
U test_r/test1/cvs/CVS
U test_r/test1/cvs/CVS/Entries
U test_r/test1/cvs/CVS/Root
U test_r/test1/cvs/dirbad
U test_r/test1/cvs/dirutd
U test_r/test1/cvs/dirutd/CVS
U test_r/test1/cvs/dirutd/CVS/Entries
U test_r/test1/cvs/dirutd/CVS/Root
U test_r/test1/cvs/dirutd/fileutd
U test_r/test1/cvs/filenew.c
U test_r/test1/cvs/fileutd.h
U test_r/test1/dir space
U test_r/test1/dir space/file space
U test_r/test1/svn
U test_r/test1/svn/.svn
U test_r/test1/svn/.svn/entries
U test_r/test1/svn/dirbad
U test_r/test1/svn/dirutd
U test_r/test1/svn/dirutd/.svn
U test_r/test1/svn/dirutd/.svn/entries
U test_r/test1/svn/dirutd/fileutd
U test_r/test1/svn/filenew.c
U test_r/test1/test space
U test_r/test1/testdir
U test_r/test1/testfile
U test_r/test1/testlink
U test_r/test1/testpipe
U test_r/test2/testdir
U test_r/test2/testfile
U test_r/test2/testfile2
U test_r/test2/testfile~
Done:  78.1%\r
            \r
U test_r/test2/testlink
Database client myhost closed
Database closed
Broken configuration
 -> Reading configuration file 'etc/broken.conf'
Error: after line: 0: need at most 1 occurence(s) of keyword 'db'
Error: at line: 3: keyword 'trash' requires 1 parameter(s), found 2
Error: at line: 5: keyword 'filter' requires 2 parameter(s), found 1
Error: after line: 9: missing keyword 'condition'
Error: after line: 11: missing keyword 'config'
Error: after line: 11: missing keyword 'protocol'
Error: after line: 13: need at most 1 occurence(s) of keyword 'config'
Error: after line: 13: need at most 1 occurence(s) of keyword 'expire'
Error: after line: 13: need at most 1 occurence(s) of keyword 'hostname'
Error: after line: 13: missing keyword 'protocol'
Error: at line: 16: keyword 'option' requires at most 2 parameter(s), found 3
Error: at line: 17: keyword 'option' requires at least 1 parameter(s), found 0
Error: at line: 25: keyword 'filter' requires 2 parameter(s), found 3
Error: at line: 26: keyword 'condition' requires 2 parameter(s), found 3
Error: at line: 27: keyword 'condition' requires 2 parameter(s), found 1
Error: at line: 30: keyword 'expire' requires 1 parameter(s), found 2
Error: at line: 32: keyword 'path' incorrect or misplaced, aborting
