HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Backing up
 --> Database initialized
 --> Database open
Backup client 'myhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test2
 --> Path: test1
Backup path 'test1'
 --> A test1/cvs
 --> A test1/cvs/CVS
 --> A test1/cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 --> A test1/cvs/dirutd
 --> A test1/cvs/dirutd/CVS
 --> A test1/cvs/dirutd/fileutd
 --> A test1/cvs/filenew.c
 --> A test1/cvs/fileutd.h
 --> A test1/dir space
 --> A test1/dir space/file space
 --> A test1/test space
 --> A test1/testdir
 --> A test1/testlink
 --> A test1/testpipe
Backup path 'test2'
 --> A test2/testdir
 --> A test2/testfile
 --> A test2/testfile2
 --> A test2/testfile~
 --> A test2/testlink
Backup client 'myClient' using protocol 'nfs'
 -> Reading backup list file
 --> Path: /home/User/test
Backup path '/home/User/test'
Unmounted test_db/mount
 --> A /home/User/test/File2.txt
Unmounted test_db/mount
Backup client 'client' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
 --> A C:/Test/File.TXT
Unmounted test_db/mount
Protocol not supported: ssh
 --> Database closed
HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Backing up
 --> Database open
Backup client 'myhost' using protocol 'file'
 -> Reading backup list file
 --> Path: test2
 --> Path: test1
Backup path 'test1'
Directory should be under CVS control: test1/cvs/dirbad
Backup path 'test2'
Backup client 'client' using protocol 'smb'
 -> Reading backup list file
 --> Path: C:/Test
Backup path 'C:/Test'
Unmounted test_db/mount
 --> Database closed
HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Scanning database
 --> Database open
 --> Scanning database contents: 4 files
 --> Database closed
HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Checking database
 --> Database open
 --> Scanning database contents thoroughly: 4 files
 --> Database closed
HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Showing list
 --> Database open
 --> Database closed
 file://myhost
 nfs://myClient
 smb://client
HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Restoring
 --> Database open
 ---> test_r/test2/testfile
 --> Database closed
HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Restoring
 --> Database open
 ---> test_r/test1/cvs
 ---> test_r/test1/cvs/CVS
 ---> test_r/test1/cvs/dirbad
 ---> test_r/test1/cvs/dirutd
 ---> test_r/test1/cvs/dirutd/CVS
 ---> test_r/test1/cvs/dirutd/fileutd
 ---> test_r/test1/cvs/filenew.c
 ---> test_r/test1/cvs/fileutd.h
 ---> test_r/test1/dir space
 ---> test_r/test1/dir space/file space
 ---> test_r/test1/test space
 ---> test_r/test1/testdir
 ---> test_r/test1/testlink
 ---> test_r/test1/testpipe
 --> Database closed
HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Restoring
 --> Database open
 ---> test_r/test1/cvs
 ---> test_r/test1/cvs/CVS
 ---> test_r/test1/cvs/dirbad
 ---> test_r/test1/cvs/dirutd
 ---> test_r/test1/cvs/dirutd/CVS
 ---> test_r/test1/cvs/dirutd/fileutd
 ---> test_r/test1/cvs/filenew.c
 ---> test_r/test1/cvs/fileutd.h
 --> Database closed
HBackup
 -> Reading configuration file
 --> Client: myClient
 --> Client: other
 --> Client: myhost
 --> Client: client
Restoring
 --> Database open
 ---> test_r/test1/cvs
 ---> test_r/test1/cvs/CVS
 ---> test_r/test1/cvs/dirbad
 ---> test_r/test1/cvs/dirutd
 ---> test_r/test1/cvs/dirutd/CVS
 ---> test_r/test1/cvs/dirutd/fileutd
 ---> test_r/test1/cvs/filenew.c
 ---> test_r/test1/cvs/fileutd.h
 ---> test_r/test1/dir space
 ---> test_r/test1/dir space/file space
 ---> test_r/test1/test space
 ---> test_r/test1/testdir
 ---> test_r/test1/testlink
 ---> test_r/test1/testpipe
 ---> test_r/test2/testdir
 ---> test_r/test2/testfile
 ---> test_r/test2/testfile2
 ---> test_r/test2/testfile~
 ---> test_r/test2/testlink
 --> Database closed
