#!/bin/sh

target="$1"
expected="$target".exp
output="$target".all


# Set path to access test scripts in priority
export PATH=../../test_tools:$PATH

# Cleanup previous attempt, if any
rm -f $output

# Setup
TEST_SETUP=`which test_setup`
if [ ! -r $TEST_SETUP ]; then
	echo "Cannot setup test environment"
	exit 1
fi
. $TEST_SETUP

echo "Help" >> $output
../hbackup -h -- >> $output 2>&1

echo "Version" >> $output
../hbackup --version -- >> $output 2>&1

echo "Error" >> $output
../hbackup -! -- >> $output 2>&1

echo "List prefixes (missing DB path)" >> $output
../hbackup -d -c etc/hbackup.conf -l >> $output 2>&1

echo "List prefixes (empty DB path)" >> $output
mkdir test_db
../hbackup -d -c etc/hbackup.conf -l >> $output 2>&1
rmdir test_db

echo "Typical backup" >> $output
../hbackup -d -c etc/hbackup.conf -- >> $output 2>&1

echo "Specify clients" >> $output
../hbackup -d -c etc/hbackup.conf -C myhost -C client >> $output 2>&1

echo "User-mode backup" >> $output
export HOME="$TESTDIRUSER"
../hbackup -du -c etc/hbackup.conf -- >> $output 2>&1

echo "Scan DB" >> $output
../hbackup -d -c etc/hbackup.conf -s >> $output 2>&1

echo "Check DB" >> $output
../hbackup -d -c etc/hbackup.conf -t >> $output 2>&1

echo "List prefixes" >> $output
../hbackup -d -c etc/hbackup.conf -l >> $output 2>&1

echo "Try to list paths in both myhost and smb://client (fails)" >> $output
../hbackup -d -c etc/hbackup.conf -l -C myhost -C smb://client >> $output 2>&1

echo "List paths in myhost" >> $output
../hbackup -d -c etc/hbackup.conf -l -C myhost >> $output 2>&1

echo "List paths in myhost under test2/" >> $output
../hbackup -d -c etc/hbackup.conf -l -C myhost -P test2/ >> $output 2>&1

echo "List paths in myhost under test1/cvs" >> $output
../hbackup -d -c etc/hbackup.conf -l -C myhost -P test1/cvs >> $output 2>&1

echo "Restore a file" >> $output
rm -rf test_r && ../hbackup -d -c etc/hbackup.conf -r test_r -C myhost -P test2/testfile >> $output 2>&1

echo "Restore all data in a prefix/dir path that's not by itself in DB" >> $output
rm -rf test_r && ../hbackup -d -c etc/hbackup.conf -r test_r -C myhost -P test1 -D 0 >> $output 2>&1

echo "Restore all data in a prefix/dir path" >> $output
rm -rf test_r && ../hbackup -d -c etc/hbackup.conf -r test_r -C myhost -P test1/cvs >> $output 2>&1

echo "Restore all data in a prefix" >> $output
rm -rf test_r && ../hbackup -d -c etc/hbackup.conf -r test_r -C myhost >> $output 2>&1

# Check
if ! diff -q $expected $output > /dev/null; then
	echo "$target: error: test output is different from expected" >&2
	exit 3
fi

# Cleanup
rm -f $output
exit 0