Testing: ../../hwbackup

Help
hwbackup options:
  -c config or --config config: give configuration file path
  -d config or --database db: give database path (supersedes -c)
  -v config or --verbose: be verbose
  -w config or --website: destination dir for web pages

Wrong config
Configuration file not accessible '/test1/doesnotexist'

Wrong config
DB not found in configuration file 'test1/testfile'

Nothing yet
DB does not exist 'test_db'

Wrong website
Looking at DB in 'test_db'
Cannot create website in '/proc/0'

Backup for one client
Looking at DB in 'test_db'
Web pages will be created in 'test_web'
Clients: 'aClient.vista'
Index:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/2002/REC-xhtml1-20020801/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta name="generator" content="HTML Tidy for Linux/x86 (vers 1 September 2005), see www.w3.org" />
    <title>HBackup report</title>
    <meta name="GENERATOR" content="Hand-coded HTML" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <h1>HBackup report</h1>
    <h2>Database</h2>
    <p>Never fully scanned.</p>
    <p>Never fully checked.</p>
    <h2>Clients</h2>
    <h3>aClient.vista</h3>
    <p>Last full backup on 2008-07-27 at 23:59:00.</p>
  </body>
</html>

Scanned
Looking at DB in 'test_db'
Web pages will be created in 'test_web'
Clients: 'aClient.vista'
Index:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/2002/REC-xhtml1-20020801/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta name="generator" content="HTML Tidy for Linux/x86 (vers 1 September 2005), see www.w3.org" />
    <title>HBackup report</title>
    <meta name="GENERATOR" content="Hand-coded HTML" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <h1>HBackup report</h1>
    <h2>Database</h2>
    <p>Last full scan on 2008-07-28 at 00:00:00.</p>
    <p>Never fully checked.</p>
    <h2>Clients</h2>
    <h3>aClient.vista</h3>
    <p>Last full backup on 2008-07-27 at 23:59:00.</p>
  </body>
</html>

Checked
Looking at DB in 'test_db'
Web pages will be created in 'test_web'
Clients: 'aClient.vista'
Index:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/2002/REC-xhtml1-20020801/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta name="generator" content="HTML Tidy for Linux/x86 (vers 1 September 2005), see www.w3.org" />
    <title>HBackup report</title>
    <meta name="GENERATOR" content="Hand-coded HTML" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <h1>HBackup report</h1>
    <h2>Database</h2>
    <p>Last full scan on 2008-07-28 at 00:00:00.</p>
    <p>Last full check on 2008-07-28 at 00:01:00.</p>
    <h2>Clients</h2>
    <h3>aClient.vista</h3>
    <p>Last full backup on 2008-07-27 at 23:59:00.</p>
  </body>
</html>
