#!/bin/sh

prog="../../hwbackup"

# Prepare
../../hbackup -c etc/hbackup.conf -iq > /dev/null 2>&1

echo "Testing: $prog"

echo
echo "Help"
$prog -h -- 2>&1

echo
echo "Wrong config"
$prog -c /test1/doesnotexist || echo -n ""

echo
echo "Wrong config"
$prog -c test1/testfile

echo
echo "Wrong website"
$prog -c etc/hbackup.conf -v -w /proc/0

echo
echo "Create pages"
$prog -c etc/hbackup.conf -v -w test_web

echo "Index:"
cat test_web/index.xhtml
