#!/bin/sh

prog="../../src/hwbackup -t"
touch -d "19710307 22:40 CET" test_time

echo "Testing: $prog"

echo
echo "Help"
$prog -h -- 2>&1

echo
echo "Wrong config"
$prog -c /test1/doesnotexist || echo -n ""

echo
echo "Wrong config"
$prog -c test1/testfile

echo
echo "Nothing yet"
$prog -c etc/hbackup.conf -v -w test_web

# Backup one client
../../src/hbackup -c etc/hbackup.conf -iq -C aClient.vista > /dev/null 2>&1
touch -c -d "20080727 23:59 GMT" test_db/aClient.vista/.last-backup

echo
echo "Wrong website"
$prog -c etc/hbackup.conf -v -w /proc/0

echo
echo "Backup for one client"
$prog -c etc/hbackup.conf -v -w test_web
echo "Index:"
cat test_web/index.xhtml

# Scan
../../src/hbackup -c etc/hbackup.conf -s > /dev/null 2>&1
touch -c -d "20080728 GMT" test_db/.last-scan

echo
echo "Scanned"
$prog -c etc/hbackup.conf -v -w test_web
echo "Index:"
cat test_web/index.xhtml

# Check
../../src/hbackup -c etc/hbackup.conf -t > /dev/null 2>&1
touch -c -d "20080728 00:01 GMT" test_db/.last-check

echo
echo "Checked"
$prog -c etc/hbackup.conf -v -w test_web
echo "Index:"
cat test_web/index.xhtml

# Backup another client, not finished
../../src/hbackup -c etc/hbackup.conf -q -C myClient > /dev/null 2>&1
rm -f test_db/myClient/.last-backup
touch -d "20080728 00:15 GMT" test_db/myClient/journal
touch -d "20080728 00:17 GMT" test_db/myClient/partial

echo
echo "Backup for two clients, second not finished"
$prog -c etc/hbackup.conf -v -w test_web
echo "Index:"
cat test_web/index.xhtml

# Backup another client, not finished
rm -f test_db/myClient/journal
rm -f test_db/myClient/partial
../../src/hbackup -c etc/hbackup.conf -q -C myClient.xp > /dev/null 2>&1
touch -d "20080728 00:15 GMT" test_db/myClient/journal
touch -d "20080728 00:17 GMT" test_db/myClient/partial
touch -c -d "20080728 00:32 GMT" test_db/myClient.xp/.last-backup
touch -d "20080728 00:45 GMT" test_db/myClient.xp/journal
touch -d "20080728 00:47 GMT" test_db/myClient.xp/partial

echo
echo "Backup for three clients, second and third not finished"
$prog -c etc/hbackup.conf -v -w test_web
echo "Index:"
cat test_web/index.xhtml

echo
echo "Same as above, with unrelated directory"
mkdir test_db/stupid_dir
$prog -c etc/hbackup.conf -v -w test_web
echo "Index:"
cat test_web/index.xhtml
