Testing: ../../hwbackup

Help
hwbackup options:
  -c config or --config config: give configuration file path
  -d config or --database db: give database path (supersedes -c)
  -v config or --verbose: be verbose
  -w config or --website: destination dir for web pages

Wrong config
Configuration file not accessible '/test1/doesnotexist'

Wrong config
DB not found in configuration file 'test1/testfile'

Wrong website
Looking at DB in 'test_db'
Cannot create website in '/proc/0'

Create pages
Looking at DB in 'test_db'
Web pages will be created in 'test_web'
Clients: 'aClient.vista' 'client.xp' 'myClient' 'myClient.xp' 'myhost'
Index:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/2002/REC-xhtml1-20020801/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta name="generator" content="HTML Tidy for Linux/x86 (vers 1 September 2005), see www.w3.org" />
    <title>HBackup report</title>
    <meta name="GENERATOR" content="Hand-coded HTML" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <h1>HBackup report</h1>
    <h2>Clients</h2>
    <p>The following clients have been found:</p>
    <ul>
    <li>aClient.vista</li>
    <li>client.xp</li>
    <li>myClient</li>
    <li>myClient.xp</li>
    <li>myhost</li>
    </ul>
  </body>
</html>
