#!/bin/bash -e

cat << EOF
/*! \file
 * \brief This file is autogenerated and MUST NOT be included directly
 */

//! \brief Print from global report object
#define HLOG_GENERIC_GLOBAL 0x1
//! \brief Print from local report object
#define HLOG_GENERIC_LOCAL  0x2
//! \brief Print from global and local report objects
#define HLOG_GENERIC_BOTH   (HLOG_GENERIC_GLOBAL | HLOG_GENERIC_LOCAL)

//! \brief Check whether printing at level \a l is enabled
#define hlog_global_is_worth(l) \\
  ((l) <= htoolbox::report.level())

//! \brief Check whether printing at level \a l is enabled
#define hlog_local_is_worth(l) \\
  ((htoolbox::tl_report != NULL) && ((l) <= htoolbox::tl_report->level()))

//! \brief Check whether printing at level \a l is enabled
#define hlog_is_worth(l) \\
  (hlog_global_is_worth(l) || hlog_local_is_worth(l))

//! \brief Check whether printing at level \a l is enabled for report \a r
#define hlog_report_is_worth(r, l) \\
  ((l) <= r.level())

//! \brief All standard, local and global macros below derive this
#define hlog_generic(m, l, t, i, s, b, f, ...) \\
  do { \\
    if ((m & HLOG_GENERIC_LOCAL) && hlog_local_is_worth(l)) \\
      htoolbox::tl_report->log(__FILE__,__LINE__,__FUNCTION__,(l),(t),(i), \\
        htoolbox::tl_thread_id,(s),(b),(f),##__VA_ARGS__); \\
    if ((m & HLOG_GENERIC_GLOBAL) && hlog_global_is_worth(l)) \\
      htoolbox::report.log(__FILE__,__LINE__,__FUNCTION__,(l),(t),(i), \\
        htoolbox::tl_thread_id,(s),(b),(f),##__VA_ARGS__); \\
  } while (0)

//! \brief All report-specific macros below derive this
#define hlog_report_generic(r, l, t, i, s, b, f, ...) \\
  do { \\
    if (hlog_report_is_worth(r, l)) \\
      r.log(__FILE__,__LINE__,__FUNCTION__,(l),(t),(i), \\
        htoolbox::tl_thread_id,(s),(b),(f),##__VA_ARGS__); \\
  } while (0)

EOF

TEMP_FLAG="htoolbox::Report::HLOG_TEMPORARY"
for scope in '' _global _local _report; do
  case $scope in
    _global)
      mode="HLOG_GENERIC_GLOBAL"
      doxy_scope=" to \a global report only"
      ;;
    _local)
      mode="HLOG_GENERIC_LOCAL"
      doxy_scope=" to \a thread-local report only"
      ;;
    _report)
      mode=""
      doxy_scope=" to specific \a report only"
      ;;
    *)
      mode="HLOG_GENERIC_BOTH"
      doxy_scope=" to both \a global and \a thread-local reports"
      ;;
    esac
  for suffix in '' _temp _arrow _buffer; do
    for level in alert error warning info verbose debug regression; do
      if [ "$suffix" == "_temp" -o "$suffix" == "_arrow" ]; then
        if [ "$level" != "verbose" -a "$level" != "debug" ]; then
          continue
        fi
      fi
      doxy_suffix=
      if [ "$suffix" == "_temp" ]; then
        flag="$TEMP_FLAG"
        doxy_suffix=" \a temporarily"
      else
        flag="0"
      fi
      if [ "$scope" == "_report" ]; then
        first_arg="report, "
      else
        first_arg=""
      fi
      if [ "$suffix" == "_arrow" ]; then
        first_arg="$first_arg""indent, "
        indent="(indent)"
        doxy_suffix=" with indentation \a arrows"
      else
        indent="-1"
      fi
      if [ "$suffix" == "_buffer" ]; then
        first_arg="$first_arg""size, buffer, "
        buffer="(size), (buffer)"
        doxy_suffix=" with binary \a buffer data"
      else
        buffer="0, NULL"
      fi
      echo
      echo "//! \\brief Log$doxy_scope at \a $level level$doxy_suffix"
      echo -n "#define hlog""$scope""_$level""$suffix"
      echo "($first_arg""format, ...) \\"
      if [ "$scope" == "_report" ]; then
        echo -n "  hlog_report_generic((report)"
      else
        echo -n "  hlog_generic($mode"
      fi
      echo ", htoolbox::$level, \\"
      echo "    $flag, $indent, $buffer, (format), ##__VA_ARGS__)"
    done
  done
done
