Buffer capacity = 10
Buffer empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0

write: 123456
Buffer capacity = 10
Buffer empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 6

read: 3: 123
Buffer capacity = 10
Buffer empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 3

read: 3: 456
Buffer capacity = 10
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

write: ABCD
Buffer capacity = 10
Buffer empty? no
Buffer full? no
Buffer writeable = 6
Buffer readable = 4

read: 3: ABC
Buffer capacity = 10
Buffer empty? no
Buffer full? no
Buffer writeable = 9
Buffer readable = 1

read: 1: D
Buffer capacity = 10
Buffer empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0

write: abcdefghij
Buffer capacity = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 10

read: 6: abcdef
Buffer capacity = 10
Buffer empty? no
Buffer full? no
Buffer writeable = 6
Buffer readable = 4

write: !@#$%^
Buffer capacity = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

wrote: 0
Buffer capacity = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

read: 10: ghij!@#$%^
Buffer capacity = 10
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

read: 0: ghij!@#$%^
Buffer capacity = 10
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

wrote: 10
Buffer capacity = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

wrote: 0
Buffer capacity = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
