Global filter
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
>List 0 client(s):
>List 1 client(s):
 -> Client: localhost
 --> Protocol: file
 --> Config: etc/doesnotexist
 --> Expiry: none
Database initialized: test_db
Database open in read/write mode
Trying client 'localhost' using protocol 'file'
Error: etc/doesnotexist: Client configuration file not found
Database closed
>List 0 client(s):
>List 1 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
>List 2 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 -> Client: myClient2
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM 
 --> Config: C:/Backup/Backup2.LST
 --> Expiry: none
>List 3 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 -> Client: myClient2
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM 
 --> Config: C:/Backup/Backup2.LST
 --> Expiry: none
 -> Client: otherClient
 --> Protocol: ssh
 --> Config: c:/home/backup/Backup.list
 --> Expiry: none
>List 4 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 -> Client: myClient2
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM 
 --> Config: C:/Backup/Backup2.LST
 --> Expiry: none
 -> Client: otherClient
 --> Protocol: ssh
 --> Config: c:/home/backup/Backup.list
 --> Expiry: none
 -> Client: Client
 --> Protocol: smb
 --> Options: username=user iocharset=utf8 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
>List 5 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 -> Client: myClient2
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM 
 --> Config: C:/Backup/Backup2.LST
 --> Expiry: none
 -> Client: otherClient
 --> Protocol: ssh
 --> Config: c:/home/backup/Backup.list
 --> Expiry: none
 -> Client: Client
 --> Protocol: smb
 --> Options: username=user iocharset=utf8 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
 -> Client: Client2
 --> Protocol: smb
 --> Hostname: Client
 --> Options: nocase username=user password= 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
>List 6 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 -> Client: myClient2
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM 
 --> Config: C:/Backup/Backup2.LST
 --> Expiry: none
 -> Client: otherClient
 --> Protocol: ssh
 --> Config: c:/home/backup/Backup.list
 --> Expiry: none
 -> Client: Client
 --> Protocol: smb
 --> Options: username=user iocharset=utf8 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
 -> Client: Client2
 --> Protocol: smb
 --> Hostname: Client
 --> Options: nocase username=user password= 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
 -> Client: Client3
 --> Protocol: smb
 --> Hostname: Client
 --> Options: username= 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
>List 7 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 -> Client: myClient2
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM 
 --> Config: C:/Backup/Backup2.LST
 --> Expiry: none
 -> Client: otherClient
 --> Protocol: ssh
 --> Config: c:/home/backup/Backup.list
 --> Expiry: none
 -> Client: Client
 --> Protocol: smb
 --> Options: username=user iocharset=utf8 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
 -> Client: Client2
 --> Protocol: smb
 --> Hostname: Client
 --> Options: nocase username=user password= 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
 -> Client: Client3
 --> Protocol: smb
 --> Hostname: Client
 --> Options: username= 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
 -> Client: Client4
 --> Protocol: smb
 --> Hostname: Client
 --> Options: username= password= 
 --> Config: C:/home/BlaH/Backup.list
 --> Expiry: none
Database open in read/write mode
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ---> Path: /home/User/test2
Backing up client
Reading list of missing checksums
List created: myClient
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/mount
A /home/User/test/File2.txt	(0 B)
Adding file data to DB for d41d8cd98f00b204e9800998ecf8427e-0
A /home/User/test/dir
 -> Dir dir
A /home/User/test/dir/file3.txt	(2 B)
Adding file data to DB for 6d7fce9fee471194aa8b5b6e47267f03-0
Backup path: /home/User/test2
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test2 test_db/mount
A /home/User/test2/File3.txt	(0 B)
A /home/User/test2/File4.txt	(0 B)
Database modified: myClient
Database closed: myClient
 -> umount -fl test_db/mount
Trying client 'myClient2' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM //myClient/C$ test_db/mount
 -> Reading client configuration file
Error: Cannot decode decimal value
Error: test_db/mount/Backup/Backup2.LST: 8: Failed to add condition
Error: Cannot decode decimal value
Error: test_db/mount/Backup/Backup2.LST: 9: Failed to add condition
Error: Cannot decode decimal value
Error: test_db/mount/Backup/Backup2.LST: 10: Failed to add condition
Error: Cannot decode decimal value
Error: test_db/mount/Backup/Backup2.LST: 11: Failed to add condition
Error: Cannot decode octal value
Error: test_db/mount/Backup/Backup2.LST: 12: Failed to add condition
Error: Cannot decode octal value
Error: test_db/mount/Backup/Backup2.LST: 13: Failed to add condition
Error: Cannot decode unit, must be 'iB' or 'B'
Error: test_db/mount/Backup/Backup2.LST: 14: Failed to add condition
Error: Cannot decode unit, must be 'iB' or 'B'
Error: test_db/mount/Backup/Backup2.LST: 15: Failed to add condition
Error: Cannot decode multiplier
Error: test_db/mount/Backup/Backup2.LST: 17: Failed to add condition
 -> umount -fl test_db/mount
Trying client 'otherClient' using protocol 'ssh'
Error: Protocol not supported: ssh
Trying client 'Client' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=user,iocharset=utf8 //Client/C$ test_db/mount
Error: test_db/mount/home/BlaH/Backup.list: Client configuration file not found
 -> umount -fl test_db/mount
Trying client 'Client2' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,nocase,username=user,password= //Client/C$ test_db/mount
Error: test_db/mount/home/BlaH/Backup.list: Client configuration file not found
 -> umount -fl test_db/mount
Trying client 'Client3' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username= //Client/C$ test_db/mount
Error: test_db/mount/home/BlaH/Backup.list: Client configuration file not found
 -> umount -fl test_db/mount
Trying client 'Client4' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=,password= //Client/C$ test_db/mount
Error: test_db/mount/home/BlaH/Backup.list: Client configuration file not found
 -> umount -fl test_db/mount
Database closed
>List 1 client(s):
 -> Client: testhost
 --> Protocol: file
 --> Hostname: localhost
 --> Config: etc/localhost.list
 --> Expiry: none
Database open in read/write mode
Trying client 'testhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: testhost
 --> Protocol: file
 --> Hostname: localhost
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Reading list of missing checksums
List created: testhost
Database open r/w: testhost
Backup path: test1
A test1/big_file	(10 MB)
Done:   3.9%\r
Done:   7.8%\r
Done:  11.7%\r
Done:  15.6%\r
Done:  19.5%\r
Done:  23.4%\r
Done:  27.3%\r
Done:  31.2%\r
Done:  35.2%\r
Done:  39.1%\r
Done:  43.0%\r
Done:  46.9%\r
Done:  50.8%\r
Done:  54.7%\r
Done:  58.6%\r
Done:  62.5%\r
Done:  66.4%\r
Done:  70.3%\r
Done:  74.2%\r
Done:  78.1%\r
Done:  82.0%\r
Done:  85.9%\r
Done:  89.8%\r
Done:  93.8%\r
Done:  97.7%\r
            \r
Adding compressed file data to DB for f1c9645dbc14efddc7d8a322685f26eb-0
A test1/cvs
 -> Dir cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
A test1/cvs/CVS
 -> Dir cvs/CVS
A test1/cvs/CVS/Entries	(161 B)
Adding compressed file data to DB for fef51838cd3cfe8ed96355742eb71fbd-0
A test1/cvs/CVS/Root	(16 B)
Adding compressed file data to DB for b90f8fa56ea1d39881d4a199c7a81d35-0
A test1/cvs/dirbad
 -> Dir cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
A test1/cvs/dirutd
 -> Dir cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
A test1/cvs/dirutd/CVS
 -> Dir cvs/dirutd/CVS
A test1/cvs/dirutd/CVS/Entries	(42 B)
Adding compressed file data to DB for 5252f242d27b8c2c9fdbdcbb33545d07-0
A test1/cvs/dirutd/CVS/Root	(10 B)
Adding compressed file data to DB for eb75fb33b2019ef3c840eb5ccdc2e795-0
A test1/cvs/dirutd/fileutd	(0 B)
A test1/cvs/filenew.c	(0 B)
A test1/cvs/fileutd.h	(0 B)
A test1/dir space
 -> Dir dir space
A test1/dir space/file space	(0 B)
A test1/svn
 -> Dir svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
A test1/svn/.svn
 -> Dir svn/.svn
A test1/svn/.svn/entries	(77 B)
Adding compressed file data to DB for 0f2ea973d77135dc3d06c8e68da6dc59-0
A test1/svn/dirbad
 -> Dir svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
A test1/svn/dirutd
 -> Dir svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
A test1/svn/dirutd/.svn
 -> Dir svn/dirutd/.svn
A test1/svn/dirutd/.svn/entries	(30 B)
Adding compressed file data to DB for 8bdef5751e46ed57d237cbe3f4a5061c-0
A test1/svn/dirutd/fileutd	(0 B)
A test1/svn/filenew.c	(0 B)
A test1/test space	(0 B)
A test1/testdir
 -> Dir testdir
A test1/testfile	(13 B)
Adding compressed file data to DB for 59ca0efa9f5633cb0371bbc0355478d8-0
A test1/testlink
A test1/testpipe
Backup path: test2
A test2/testdir
 -> Dir testdir
A test2/testfile	(145 kB)
Adding file data to DB for 3d546a1ce46c6ae10ad34ab8a81c542e-0
A test2/testfile2	(259 kB)
Adding file data to DB for fb00cd74a5f35e89a7fbdd3c1d05375a-0
A test2/testfile~	(524 kB)
Done:  78.1%\r
            \r
Adding file data to DB for 59071590099d21dd439896592338bf95-0
A test2/testlink
Database modified: testhost
Database closed: testhost
Database closed
>List 1 client(s):
 -> Client: testhost
 --> Protocol: file
 --> Config: etc/localhost.list
 --> Expiry: none
Database open in read/write mode
Trying client 'testhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: testhost
 --> Protocol: file
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Reading list of missing checksums
Database open r/w: testhost
Backup path: test1
 -> Dir cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir cvs/CVS
 -> Dir cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir cvs/dirutd/CVS
 -> Dir dir space
 -> Dir svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
 -> Dir svn/.svn
 -> Dir svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
 -> Dir svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
 -> Dir svn/dirutd/.svn
 -> Dir testdir
Backup path: test2
 -> Dir testdir
Database closed: testhost
Database closed
>List 1 client(s):
 -> Client: testhost
 --> Protocol: file
 --> Config: etc/localhost.list
 --> Expiry: none
Database open in read/write mode
Trying client 'testhost' using protocol 'file'
 -> Reading client configuration file
Error: etc/localhost.list: 30: Path inside another
Database closed
>List 1 client(s):
 -> Client: testhost
 --> Protocol: file
 --> Config: etc/localhost.list2
 --> Expiry: none
Database open in read/write mode
Trying client 'testhost' using protocol 'file'
 -> Reading client configuration file
Error: etc/localhost.list2: 12: Path inside another
Error: etc/localhost.list2: 30: Path inside another
backup failed
Database closed

Test: missing clients
Database open in read/write mode
Trying client 'myhost2' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myhost2/C$ test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myhost2
 --> Protocol: smb
 --> Config: C:/Backup/testhost2.list
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
Backing up client
Reading list of missing checksums
List created: myhost2
Database open r/w: myhost2
Backup path: C:/Test Dir
A C:/Test Dir/My Dir
 -> Dir My Dir
A C:/Test Dir/My Dir/a File.TXT	(2 B)
Adding file data to DB for b026324c6904b2a9cb4b88d6d61c81d1-0
A C:/Test Dir/My Dir/another File.TXT	(2 B)
Adding file data to DB for 26ab0db90d72e28ad0ba1e22ee510510-0
A C:/Test Dir/My File.TXT	(0 B)
Database modified: myhost2
Database closed: myhost2
 -> umount -fl test_db/mount
Database closed
Database open in read/write mode
Trying client 'myhost3' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myhost3:/home/User test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myhost3
 --> Protocol: nfs
 --> Config: /home/User/testhost3.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
Backing up client
Reading list of missing checksums
List created: myhost3
Database open r/w: myhost3
Backup path: /home/User/test
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myhost3:/home/User/test test_db/mount
A /home/User/test/File2.txt	(0 B)
A /home/User/test/dir
 -> Dir dir
A /home/User/test/dir/file3.txt	(2 B)
Database modified: myhost3
Database closed: myhost3
 -> umount -fl test_db/mount
Database closed
Database open in read/write mode
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Config: etc/testhost.list
 --> Expiry: none
 --> Paths: 
 ---> Path: test1/cvs
Backing up client
Reading list of missing checksums
List created: myhost
Database open r/w: myhost
Backup path: test1/cvs
A test1/cvs/CVS
 -> Dir CVS
A test1/cvs/CVS/Entries	(161 B)
A test1/cvs/CVS/Root	(16 B)
A test1/cvs/CVS/Whatever	(17 B)
Adding file data to DB for 9283e2c51868272850bd2d89b63c58e8-0
A test1/cvs/CVS/Wherever
 -> Dir CVS/Wherever
A test1/cvs/CVS/Wherever/Whichever	(0 B)
A test1/cvs/dirbad
 -> Dir dirbad
A test1/cvs/dirbad/fileoth	(0 B)
A test1/cvs/dirbad/fileutd	(0 B)
A test1/cvs/diroth
 -> Dir diroth
A test1/cvs/dirutd
 -> Dir dirutd
A test1/cvs/dirutd/CVS
 -> Dir dirutd/CVS
A test1/cvs/dirutd/CVS/Entries	(42 B)
A test1/cvs/dirutd/CVS/Root	(10 B)
A test1/cvs/dirutd/CVS/Whatever	(11 B)
Adding file data to DB for caecaacc7fdee8a7667d4f4f315858a9-0
A test1/cvs/dirutd/fileoth	(0 B)
A test1/cvs/dirutd/fileutd	(0 B)
A test1/cvs/filemod.o	(0 B)
A test1/cvs/filenew.c	(0 B)
A test1/cvs/fileoth	(0 B)
A test1/cvs/fileutd.h	(0 B)
Database modified: myhost
Database closed: myhost
Database closed
Database open in read-only mode

Clients in DB
Records found: 5
 myClient
 myhost
 myhost2
 myhost3
 testhost

Paths in 'myhost' client in DB
Database open r-o: myhost
Database closed: myhost
Records found: 1
 test1

Paths in 'myhost' client under test1 in DB
Database open r-o: myhost
Database closed: myhost
Records found: 1
 test1/cvs

Paths in 'myhost' client under test1/cvs in DB
Database open r-o: myhost
Database closed: myhost
Records found: 8
 test1/cvs/CVS
 test1/cvs/dirbad
 test1/cvs/diroth
 test1/cvs/dirutd
 test1/cvs/filemod.o
 test1/cvs/filenew.c
 test1/cvs/fileoth
 test1/cvs/fileutd.h

Paths in 'myhost' client under test1/cvs/diroth in DB
Database open r-o: myhost
Database closed: myhost
Records found: 0

Paths in 'myhost' client under test1/cvs/dirutd in DB
Database open r-o: myhost
Database closed: myhost
Records found: 3
 test1/cvs/dirutd/CVS
 test1/cvs/dirutd/fileoth
 test1/cvs/dirutd/fileutd
Database closed
Create list of clients
>List 3 client(s):
 -> Client: myhost
 --> Protocol: file
 --> Config: etc/testhost.list
 --> Expiry: none
 -> Client: myhost2
 --> Protocol: smb
 --> Config: C:/Backup/testhost2.list
 --> Expiry: none
 -> Client: myhost3
 --> Protocol: nfs
 --> Config: /home/User/testhost3.list
 --> Expiry: none
Database open in read/write mode
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Config: etc/testhost.list
 --> Expiry: none
 --> Paths: 
 ---> Path: test1/cvs
Backing up client
Reading list of missing checksums
Database open r/w: myhost
Backup path: test1/cvs
 -> Dir CVS
 -> Dir CVS/Wherever
 -> Dir dirbad
 -> Dir diroth
 -> Dir dirutd
 -> Dir dirutd/CVS
Database closed: myhost
Trying client 'myhost2' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myhost2/C$ test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myhost2
 --> Protocol: smb
 --> Config: C:/Backup/testhost2.list
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
Backing up client
Database open r/w: myhost2
Backup path: C:/Test Dir
 -> Dir My Dir
Database closed: myhost2
 -> umount -fl test_db/mount
Trying client 'myhost3' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myhost3:/home/User test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myhost3
 --> Protocol: nfs
 --> Config: /home/User/testhost3.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
Backing up client
Database open r/w: myhost3
Backup path: /home/User/test
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myhost3:/home/User/test test_db/mount
 -> Dir dir
Database closed: myhost3
 -> umount -fl test_db/mount
Database closed
Create list of clients
>List 2 client(s):
 -> Client: myhost2
 --> Protocol: smb
 --> Config: C:/Backup/testhost2.list
 --> Expiry: none
 -> Client: myhost3
 --> Protocol: nfs
 --> Config: /home/User/testhost3.list
 --> Expiry: none
Database open in read/write mode
Trying client 'myhost2' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myhost2/C$ test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myhost2
 --> Protocol: smb
 --> Config: C:/Backup/testhost2.list
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
Backing up client
Reading list of missing checksums
Database open r/w: myhost2
Backup path: C:/Test Dir
 -> Dir My Dir
Database closed: myhost2
 -> umount -fl test_db/mount
Trying client 'myhost3' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myhost3:/home/User test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myhost3
 --> Protocol: nfs
 --> Config: /home/User/testhost3.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
Backing up client
Database open r/w: myhost3
Backup path: /home/User/test
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myhost3:/home/User/test test_db/mount
 -> Dir dir
Database closed: myhost3
 -> umount -fl test_db/mount
Database closed
Create list of clients
>List 2 client(s):
 -> Client: myhost
 --> Protocol: file
 --> Config: etc/testhost.list
 --> Expiry: none
 -> Client: myhost3
 --> Protocol: nfs
 --> Config: /home/User/testhost3.list
 --> Expiry: none
Database open in read/write mode
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Config: etc/testhost.list
 --> Expiry: none
 --> Paths: 
 ---> Path: test1/cvs
Backing up client
Reading list of missing checksums
Database open r/w: myhost
Backup path: test1/cvs
 -> Dir CVS
 -> Dir CVS/Wherever
 -> Dir dirbad
 -> Dir diroth
 -> Dir dirutd
 -> Dir dirutd/CVS
Database closed: myhost
Trying client 'myhost3' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myhost3:/home/User test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myhost3
 --> Protocol: nfs
 --> Config: /home/User/testhost3.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
Backing up client
Database open r/w: myhost3
Backup path: /home/User/test
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myhost3:/home/User/test test_db/mount
 -> Dir dir
Database closed: myhost3
 -> umount -fl test_db/mount
Database closed
Create list of clients
>List 2 client(s):
 -> Client: myhost
 --> Protocol: file
 --> Config: etc/testhost.list
 --> Expiry: none
 -> Client: myhost2
 --> Protocol: smb
 --> Config: C:/Backup/testhost2.list
 --> Expiry: none
Database open in read/write mode
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Config: etc/testhost.list
 --> Expiry: none
 --> Paths: 
 ---> Path: test1/cvs
Backing up client
Reading list of missing checksums
Database open r/w: myhost
Backup path: test1/cvs
 -> Dir CVS
 -> Dir CVS/Wherever
 -> Dir dirbad
 -> Dir diroth
 -> Dir dirutd
 -> Dir dirutd/CVS
Database closed: myhost
Trying client 'myhost2' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myhost2/C$ test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myhost2
 --> Protocol: smb
 --> Config: C:/Backup/testhost2.list
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
Backing up client
Database open r/w: myhost2
Backup path: C:/Test Dir
 -> Dir My Dir
Database closed: myhost2
 -> umount -fl test_db/mount
Database closed
Second mount fails
>List 1 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
Database open in read/write mode
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ---> Path: /home/User/test2
Backing up client
Reading list of missing checksums
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/mount
 -> Dir dir
Backup path: /home/User/test2
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test2 test_db/mount
Error: Connection timed out: Skipping client
Database closed: myClient
Database closed
First mount fails
>List 1 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
Database open in read/write mode
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ---> Path: /home/User/test2
Backing up client
Reading list of missing checksums
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/mount
Error: Connection timed out: Skipping client
Database closed: myClient
Database closed
Works again
>List 1 client(s):
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
Database open in read/write mode
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ---> Path: /home/User/test2
Backing up client
Reading list of missing checksums
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/mount
 -> Dir dir
Backup path: /home/User/test2
 -> umount -fl test_db/mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test2 test_db/mount
Database closed: myClient
 -> umount -fl test_db/mount
Database closed
Test with dual boot client
>List 1 client(s):
 -> Client: myClient
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
Database open in read/write mode
Trying client 'myClient' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myClient/C$ test_db/mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Subset: xp
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Reading list of missing checksums
List created: myClient.xp
Database open r/w: myClient.xp
Backup path: C:/Test Dir
A C:/Test Dir/My Dir
 -> Dir My Dir
A C:/Test Dir/My Dir/a File.TXT	(2 B)
A C:/Test Dir/My Dir/another File.TXT	(2 B)
A C:/Test Dir/My File.TXT	(0 B)
Database modified: myClient.xp
Database closed: myClient.xp
 -> umount -fl test_db/mount
Database closed

Clients in DB
Records found: 6
 myClient
 myClient.xp
 myhost
 myhost2
 myhost3
 testhost
