Conditions test
filter_name check
match 2.1
filter_name_start check
match 3.1
match 3.2
filter_name_end check
match 4.1
filter_name_regex check
match 5.1
filter_path check
match 6.1
filter_path_start check
match 7.1
filter_path_end check
match 8.1
filter_path_regex check
match 9.1
filter_size_ge check
Not matching 4000
Not matching 4999
Matching 5000
Matching 5001
Matching 6000
filter_size_gt check
Not matching 4000
Not matching 4999
Not matching 5000
Matching 5001
Matching 6000
filter_size_le check
Matching 4000
Matching 4999
Matching 5000
Not matching 5001
Not matching 6000
filter_size_lt check
Matching 4000
Matching 4999
Not matching 5000
Not matching 5001
Not matching 6000
filter_mode_and check
Matching 777
Not matching 666
Matching 111
filter_mode_eq check
Not matching 777
Not matching 666
Matching 111
negation check (using filter_mode_eq)
Matching 777
Matching 666
Not matching 111
