Conditions test
Condition::name check
match 2.1
Condition::name_start check
match 3.1
match 3.2
Condition::name_end check
match 4.1
Condition::name_regex check
match 5.1
Condition::path check
match 6.1
Condition::path_start check
match 7.1
Condition::path_end check
match 8.1
Condition::path_regex check
match 9.1
Condition::size_ge check
Not matching 4000
Not matching 4999
Matching 5000
Matching 5001
Matching 6000
Condition::size_gt check
Not matching 4000
Not matching 4999
Not matching 5000
Matching 5001
Matching 6000
Condition::size_le check
Matching 4000
Matching 4999
Matching 5000
Not matching 5001
Not matching 6000
Condition::size_lt check
Matching 4000
Matching 4999
Not matching 5000
Not matching 5001
Not matching 6000
Condition::mode_and check
Matching 777
Not matching 666
Matching 111
Condition::mode_eq check
Not matching 777
Not matching 666
Matching 111
negation check (using Condition::mode_eq)
Matching 777
Matching 666
Not matching 111
