Conditions test
Condition::name check
Condition: name 'to a file.txt'
Condition::name (no case) check
Condition: no case name 'to a file.txt'
Condition: no case name 'TO A FILE.TXT'
Condition::name_start check
Condition: name_start 'to a file.txt'
Condition: name_start 'to a file'
Condition::name_start (no case) check
Condition: no case name_start 'to a file.txt'
Condition: no case name_start 'to a file'
Condition: no case name_start 'TO A FILE.TXT'
Condition: no case name_start 'TO A FILE'
Condition::name_end check
Condition: name_end '.txt'
Condition::name_end (no case) check
Condition: no case name_end '.txt'
Condition: no case name_end '.TXT'
Condition::name_regex check
Condition: name_regex '^.*\.txt'
Condition::path check
Condition: path 'this is/a path/to a file.txt'
Condition::path (no case) check
Condition: no case path 'this is/a path/to a file.txt'
Condition: no case path 'THIS IS/A PATH/TO A FILE.TXT'
Condition::path_start check
Condition: path_start 'this is/a'
Condition::path_start (no case) check
Condition: no case path_start 'this is/a'
Condition: no case path_start 'THIS IS/A'
Condition::path_end check
Condition: path_end '.txt'
Condition::path_end (no case) check
Condition: no case path_end '.txt'
Condition: no case path_end '.TXT'
Condition::path_regex check
Condition: path_regex '^this.*path/.*\.txt'
Condition::size_ge check
Not matching 4000
Not matching 4999
Matching 5000
Matching 5001
Matching 6000
Condition::size_gt check
Not matching 4000
Not matching 4999
Not matching 5000
Matching 5001
Matching 6000
Condition::size_le check
Matching 4000
Matching 4999
Matching 5000
Not matching 5001
Not matching 6000
Condition::size_lt check
Matching 4000
Matching 4999
Not matching 5000
Not matching 5001
Not matching 6000
Condition::mode_and check
Matching 777
Not matching 666
Matching 111
Condition::mode_eq check
Not matching 777
Not matching 666
Matching 111
negation check (using Condition::mode_eq)
Matching 777
Matching 666
Not matching 111
