
Test: client configuration
Syntax:
  expire, occ.: optional, max = 1; params: min = max = 1
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  path, occ.: min = 1, no max; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    ignore, occ.: optional, max = 1; params: min = max = 1
    no_compress, occ.: optional, max = 1; params: min = max = 1
    parser, occ.: optional, no max; params: min = 1, max = 2
  users, occ.: optional, max = 1; params: min = 1, no max
Error: after line: 0: missing keyword 'path'
Error: at line: 5: found CR character, aborting
Config:
2:   filter and subdir
3:     condition path_start subdir
4:     condition !size< 100
6:   users biloute machin
8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Test: server configuration
Syntax:
  client, occ.: min = 1, no max; params: min = 1, max = 2
    config, occ.: optional, max = 1; params: min = max = 1
    expire, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    hostname, occ.: optional, max = 1; params: min = max = 1
    ignore, occ.: optional, max = 1; params: min = max = 1
    option, occ.: optional, no max; params: min = 1, max = 2
    path, occ.: optional, no max; params: min = max = 1
      compress, occ.: optional, max = 1; params: min = max = 1
      filter, occ.: optional, no max; params: min = max = 2
        condition, occ.: min = 1, no max; params: min = max = 2
      ignore, occ.: optional, max = 1; params: min = max = 1
      no_compress, occ.: optional, max = 1; params: min = max = 1
      parser, occ.: optional, no max; params: min = 1, max = 2
    protocol, occ.: min = 1, max = 1; params: min = max = 1
    report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
    timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
    users, occ.: optional, max = 1; params: min = 1, no max
  db, occ.: optional, max = 1; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
  timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
Config:
1:   db test_db
2:     compress auto
4:   filter all nothing
5:     condition type pipe
6:     condition size> 10
8:   ignore nothing
10:   filter all backup
11:     condition type file
12:     condition path_end ~
14:   filter any test_or
15:     condition filter backup
16:     condition !size< 1000
18:   client myClient xp
19:     protocol smb
20:     users backup
21:     config C:\Backup\Backup.LST
23:   client myClient
24:     protocol nfs
25:     users backup root
26:     hostname myClient
27:     config /home/User/hbackup.list
29:   client other
30:     protocol ssh
31:     hostname otherClient
32:     config /home/backup/Backup.list
34:     filter and subdir
35:       condition path_start subdir
36:       condition !size< 100
38:     filter and bigfile
39:       condition size>= 10
40:       condition type file
42:     expire 1
44:     path test2//
46:     path test1
48:       filter and not_object
49:         condition !path_end .o
51:       filter or to_be_ignored
52:         condition filter subdir
53:         condition filter backup
54:         condition !filter not_object
56:       ignore to_be_ignored
58:       compress bigfile
60:       parser cvs controlled
61:       parser svn modified
63:   client myhost
64:     report_copy_error_once
65:     protocol file
66:     hostname myhost.mynetwork.lan
67:     timeout_nowarning
68:     config etc/localhost.list
69:     expire 1
71:   client client xp
72:     ignore backup
73:     protocol smb
74:     option username Myself
75:     option password flesyM
76:     option nocase
77:     hostname myClient
78:     config C:\Backup\Backup.LST
80:   client aClient vista
81:     protocol smb
82:     filter and huge_file
83:       condition !filter backup
84:       condition !size< 100
86:     path C:\Test Dir
87:       filter and compress_m
88:         condition !filter huge_file
89:       compress compress_m
90:       ignore backup
91:       parser svn modified
92:     report_copy_error_once
Test: configuration save
Config:
1:   db test_db
2:     compress auto
3:   filter all nothing
4:     condition type pipe
5:     condition size> 10
6:   ignore nothing
7:   filter all backup
8:     condition type file
9:     condition path_end ~
10:   filter any test_or
11:     condition filter backup
12:     condition !size< 1000
13:   client myClient xp
14:     protocol smb
15:     users backup
16:     config C:\Backup\Backup.LST
17:   client myClient
18:     protocol nfs
19:     users backup root
20:     hostname myClient
21:     config /home/User/hbackup.list
22:   client other
23:     protocol ssh
24:     hostname otherClient
25:     config /home/backup/Backup.list
26:     filter and subdir
27:       condition path_start subdir
28:       condition !size< 100
29:     filter and bigfile
30:       condition size>= 10
31:       condition type file
32:     expire 1
33:     path test2//
34:     path test1
35:       filter and not_object
36:         condition !path_end .o
37:       filter or to_be_ignored
38:         condition filter subdir
39:         condition filter backup
40:         condition !filter not_object
41:       ignore to_be_ignored
42:       compress bigfile
43:       parser cvs controlled
44:       parser svn modified
45:   client myhost
46:     report_copy_error_once
47:     protocol file
48:     hostname myhost.mynetwork.lan
49:     timeout_nowarning
50:     config etc/localhost.list
51:     expire 1
52:   client client xp
53:     ignore backup
54:     protocol smb
55:     option username Myself
56:     option password flesyM
57:     option nocase
58:     hostname myClient
59:     config C:\Backup\Backup.LST
60:   client aClient vista
61:     protocol smb
62:     filter and huge_file
63:       condition !filter backup
64:       condition !size< 100
65:     path C:\Test Dir
66:       filter and compress_m
67:         condition !filter huge_file
68:       compress compress_m
69:       ignore backup
70:       parser svn modified
71:     report_copy_error_once
Test: broken configuration
Error: after line: 0: need at most 1 occurence(s) of keyword 'db'
Error: after line: 0: need at most 1 occurence(s) of keyword 'report_copy_error_once'
Error: after line: 0: need at most 1 occurence(s) of keyword 'timeout_nowarning'
Error: at line: 10: keyword 'filter' requires 2 parameter(s), found 1
Error: after line: 14: missing keyword 'condition'
Error: after line: 16: need at most 1 occurence(s) of keyword 'ignore'
Error: at line: 18: keyword 'users' requires at least 1 parameter(s), found 0
Error: at line: 20: keyword 'ignore' requires 1 parameter(s), found 0
Error: after line: 22: need at most 1 occurence(s) of keyword 'config'
Error: after line: 22: need at most 1 occurence(s) of keyword 'expire'
Error: after line: 22: need at most 1 occurence(s) of keyword 'hostname'
Error: at line: 26: keyword 'option' requires at most 2 parameter(s), found 3
Error: at line: 27: keyword 'option' requires at least 1 parameter(s), found 0
Error: at line: 35: keyword 'filter' requires 2 parameter(s), found 3
Error: at line: 36: keyword 'condition' requires 2 parameter(s), found 3
Error: at line: 37: keyword 'condition' requires 2 parameter(s), found 1
Error: at line: 40: keyword 'expire' requires 1 parameter(s), found 2
Error: after line: 44: need at most 1 occurence(s) of keyword 'compress'
Error: after line: 44: need at most 1 occurence(s) of keyword 'ignore'
Error: after line: 54: missing keyword 'condition'
Error: at line: 56: keyword 'filter' requires 2 parameter(s), found 1
Error: after line: 56: missing keyword 'condition'
Error: after line: 68: missing keyword 'protocol'
Error: at line: 74: keyword 'ignore' requires 1 parameter(s), found 2
Error: at line: 75: keyword 'compress' requires 1 parameter(s), found 2
Error: at line: 88: keyword 'ignore' requires 1 parameter(s), found 0
Error: at line: 89: keyword 'compress' requires 1 parameter(s), found 0
Error: at line: 91: keyword 'what_the_f...?' incorrect or misplaced, aborting
Config:
1:   db test_db
2:   db blah
4:   timeout_nowarning
5:   timeout_nowarning
7:   report_copy_error_once
8:   report_copy_error_once
10:   filter all
11:     condition type file
12:     condition path_end ~
14:   filter any test_or
16:   client myClient
17:     protocol nfs
18:     users
19:     ignore test_or
20:     ignore
22:   client other
23:     protocol ssh
24:     hostname otherClient
25:     hostname 192.168.0.132
26:     option I am happy
27:     option
28:     config /home/backup/Backup.list
29:     config /home/backup/Backup2.list
31:     filter and subdir
32:       condition path_start subdir
33:       condition !size< 100
35:     filter and bigfile 3
36:       condition size>= 10 yeah
37:       condition type
39:     expire 1
40:     expire 2 3
42:     path test2//
44:     path test1
46:       filter and not_object
47:         condition !path_end .o
49:       filter or to_be_ignored
50:         condition filter subdir
51:         condition filter backup
52:         condition !filter not_object
54:       filter and blah
56:       filter or
59:       ignore to_be_ignored
60:       ignore to_be_ignored2
62:       compress bigfile
63:       compress bigfile2
65:       parser cvs controlled
66:       parser svn modified
68:   client myhost
69:     hostname myhost.mynetwork.lan
70:     config etc/localhost.list
71:     expire 1
73:     path blah
74:       ignore 2 3
75:       compress 4 5
77:   client client xp
78:     protocol smb
79:     option username Myself
80:     option password flesyM
81:     option nocase
82:     hostname myClient
83:     config C:\Backup\Backup.LST
85:     path C:\Crash"
86:     path C:\Crash
87:     path blah
88:       ignore
89:       compress
