Test: server configuration
Items:
  client, occ.: min = 1, no max; params: min params = 1, max params = 2
    config, occ.: min = 1, max = 1; params: min params = 1, max params = 1
    expire, occ.: optional, max = 1; params: min params = 1, max params = 1
    hostname, occ.: optional, max = 1; params: min params = 1, max params = 1
    option, occ.: optional, no max; params: min params = 1, max params = 2
    protocol, occ.: min = 1, max = 1; params: min params = 1, max params = 1
  db, occ.: optional, max = 1; params: min params = 1, max params = 1
  filter, occ.: optional, no max; params: min params = 2, max params = 2
    condition, occ.: min = 1, no max; params: min params = 2, max params = 2
  trash, occ.: optional, max = 1; params: min params = 1, max params = 1
Lines:
1:   db test_db
3:   filter all backup
4:     condition type file
5:     condition path_end ~
7:   filter any test_or
8:     condition filter backup
9:     condition !size< 1000
11:   client myClient
12:     protocol nfs
13:     hostname myClient
14:     config /home/User/hbackup.list
16:   client other
17:     protocol ssh
18:     hostname otherClient
19:     config /home/backup/Backup.list
21:   client myhost
22:     protocol file
23:     hostname myhost.mynetwork.lan
24:     config etc/localhost.list
25:     expire 1
27:   client client xp
28:     protocol smb
29:     option username Myself
30:     option password flesyM
31:     option nocase
32:     hostname myClient
33:     config C:\Backup\Backup.LST

Test: client configuration
Error: after line: 0: missing keyword 'path'
Error: at line: 5: found CR character, aborting
Items:
  expire, occ.: optional, max = 1; params: min params = 1, max params = 1
  filter, occ.: optional, no max; params: min params = 2, max params = 2
    condition, occ.: min = 1, no max; params: min params = 2, max params = 2
  path, occ.: min = 1, no max; params: min params = 1, max params = 1
    compress, occ.: optional, max = 1; params: min params = 1, max params = 1
    filter, occ.: optional, no max; params: min params = 2, max params = 2
      condition, occ.: min = 1, no max; params: min params = 2, max params = 2
    ignore, occ.: optional, max = 1; params: min params = 1, max params = 1
    parser, occ.: optional, no max; params: min params = 1, max params = 2
Lines:
2:   filter and subdir
3:     condition path_start subdir
4:     condition !size< 100
6:   filter and bigfile
7:     condition size>= 10
8:     condition type file
10:   expire 1
12:   path test2//
14:   path test1
16:     filter and not_object
17:       condition !path_end .o
19:     filter or to_be_ignored
20:       condition filter subdir
21:       condition filter backup
22:       condition !filter not_object
24:     ignore to_be_ignored
26:     compress bigfile
28:     parser cvs controlled
29:     parser svn modified
Test: general configuration
Items:
  client, occ.: min = 1, no max; params: min params = 2, max params = 2
    config, occ.: min = 1, max = 1; params: min params = 1, max params = 1
    expire, occ.: optional, max = 1; params: min params = 1, max params = 1
    filter, occ.: optional, no max; params: min params = 2, max params = 2
      condition, occ.: min = 1, no max; params: min params = 2, max params = 2
    hostname, occ.: optional, max = 1; params: min params = 1, max params = 1
    option, occ.: optional, no max; params: min params = 1, max params = 2
    path, occ.: optional, no max; params: min params = 1, max params = 1
      compress, occ.: optional, max = 1; params: min params = 1, max params = 1
      filter, occ.: optional, no max; params: min params = 2, max params = 2
        condition, occ.: min = 1, no max; params: min params = 2, max params = 2
      ignore, occ.: optional, max = 1; params: min params = 1, max params = 1
      parser, occ.: optional, no max; params: min params = 1, max params = 2
  db, occ.: optional, max = 1; params: min params = 1, max params = 1
  filter, occ.: optional, no max; params: min params = 2, max params = 2
    condition, occ.: min = 1, no max; params: min params = 2, max params = 2
  trash, occ.: optional, max = 1; params: min params = 1, max params = 1
Lines:
1:   db test_db
3:   filter all backup
4:     condition type file
5:     condition path_end ~
7:   filter any test_or
8:     condition filter backup
9:     condition !size< 1000
11:   client nfs myClient
12:     hostname myClient
13:     config /home/User/hbackup.list
15:   client ssh other
16:     hostname otherClient
17:     config /home/backup/Backup.list
19:     filter and subdir
20:       condition path_start subdir
21:       condition !size< 100
23:     filter and bigfile
24:       condition size>= 10
25:       condition type file
27:     expire 1
29:     path test2//
31:     path test1
33:       filter and not_object
34:         condition !path_end .o
36:       filter or to_be_ignored
37:         condition filter subdir
38:         condition filter backup
39:         condition !filter not_object
41:       ignore to_be_ignored
43:       compress bigfile
45:       parser cvs controlled
46:       parser svn modified
48:   client file myhost
49:     hostname myhost.mynetwork.lan
50:     config etc/localhost.list
51:     expire 1
53:   client smb client
54:     option username Myself
55:     option password flesyM
56:     option nocase
57:     hostname myClient
58:     config C:\Backup\Backup.LST
Test: broken configuration
Error: after line: 0: need at most 1 occurence(s) of keyword 'db'
Error: at line: 4: keyword 'filter' requires 2 parameter(s), found 1
Error: after line: 8: missing keyword 'condition'
Error: after line: 10: missing keyword 'config'
Error: after line: 12: need at most 1 occurence(s) of keyword 'config'
Error: after line: 12: need at most 1 occurence(s) of keyword 'expire'
Error: after line: 12: need at most 1 occurence(s) of keyword 'hostname'
Error: at line: 15: keyword 'option' requires at most 2 parameter(s), found 3
Error: at line: 16: keyword 'option' requires at least 1 parameter(s), found 0
Error: at line: 24: keyword 'filter' requires 2 parameter(s), found 3
Error: at line: 25: keyword 'condition' requires 2 parameter(s), found 3
Error: at line: 26: keyword 'condition' requires 2 parameter(s), found 1
Error: at line: 29: keyword 'expire' requires 1 parameter(s), found 2
Error: after line: 33: need at most 1 occurence(s) of keyword 'compress'
Error: after line: 33: need at most 1 occurence(s) of keyword 'ignore'
Error: after line: 43: missing keyword 'condition'
Error: at line: 45: keyword 'filter' requires 2 parameter(s), found 1
Error: after line: 45: missing keyword 'condition'
Error: at line: 63: keyword 'ignore' requires 1 parameter(s), found 2
Error: at line: 64: keyword 'compress' requires 1 parameter(s), found 2
Error: at line: 76: keyword 'ignore' requires 1 parameter(s), found 0
Error: at line: 77: keyword 'compress' requires 1 parameter(s), found 0
Error: at line: 79: keyword 'what_the_f...?' incorrect or misplaced, aborting
Items:
  client, occ.: min = 1, no max; params: min params = 2, max params = 2
    config, occ.: min = 1, max = 1; params: min params = 1, max params = 1
    expire, occ.: optional, max = 1; params: min params = 1, max params = 1
    filter, occ.: optional, no max; params: min params = 2, max params = 2
      condition, occ.: min = 1, no max; params: min params = 2, max params = 2
    hostname, occ.: optional, max = 1; params: min params = 1, max params = 1
    option, occ.: optional, no max; params: min params = 1, max params = 2
    path, occ.: optional, no max; params: min params = 1, max params = 1
      compress, occ.: optional, max = 1; params: min params = 1, max params = 1
      filter, occ.: optional, no max; params: min params = 2, max params = 2
        condition, occ.: min = 1, no max; params: min params = 2, max params = 2
      ignore, occ.: optional, max = 1; params: min params = 1, max params = 1
      parser, occ.: optional, no max; params: min params = 1, max params = 2
  db, occ.: optional, max = 1; params: min params = 1, max params = 1
  filter, occ.: optional, no max; params: min params = 2, max params = 2
    condition, occ.: min = 1, no max; params: min params = 2, max params = 2
  trash, occ.: optional, max = 1; params: min params = 1, max params = 1
Lines:
1:   db test_db
2:   db blah
4:   filter all
5:     condition type file
6:     condition path_end ~
8:   filter any test_or
10:   client nfs myClient
12:   client ssh other
13:     hostname otherClient
14:     hostname 192.168.0.132
15:     option I am happy
16:     option
17:     config /home/backup/Backup.list
18:     config /home/backup/Backup2.list
20:     filter and subdir
21:       condition path_start subdir
22:       condition !size< 100
24:     filter and bigfile 3
25:       condition size>= 10 yeah
26:       condition type
28:     expire 1
29:     expire 2 3
31:     path test2//
33:     path test1
35:       filter and not_object
36:         condition !path_end .o
38:       filter or to_be_ignored
39:         condition filter subdir
40:         condition filter backup
41:         condition !filter not_object
43:       filter and blah
45:       filter or
48:       ignore to_be_ignored
49:       ignore to_be_ignored2
51:       compress bigfile
52:       compress bigfile2
54:       parser cvs controlled
55:       parser svn modified
57:   client file myhost
58:     hostname myhost.mynetwork.lan
59:     config etc/localhost.list
60:     expire 1
62:     path blah
63:       ignore 2 3
64:       compress 4 5
66:   client smb client
67:     option username Myself
68:     option password flesyM
69:     option nocase
70:     hostname myClient
71:     config C:\Backup\Backup.LST
73:     path C:\Crash"
74:     path C:\Crash
75:     path blah
76:       ignore
77:       compress
