
Only consider controlled files
test1 is not controlled
 -> Parsing CVS entries
 --> dir space: D
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
test1/cvs/nofile will be ignored
test1/cvs/filenew.c will not be ignored
test1/cvs/filemod.o will not be ignored
test1/cvs/fileutd.h will not be ignored
test1/cvs/fileoth will be ignored
test1/cvs/dirutd will not be ignored
test1/cvs/dirbad will not be ignored
test1/cvs/CVS will not be ignored
test1/cvs/CVS/Entries will not be ignored
test1/cvs/CVS/Root will not be ignored
test1/cvs/CVS/Whatever will be ignored
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Parsing CVS entries
 --> fileutd: 1159985080
test1/cvs/dirutd/fileutd will not be ignored
test1/cvs/dirutd/fileoth will be ignored
test1/cvs/diroth is not controlled
test1/cvs/CVS is not controlled

Only consider controlled modified files
test1 is not controlled
 -> Parsing CVS entries
 --> dir space: D
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
test1/cvs/nofile will be ignored
test1/cvs/filenew.c will not be ignored
test1/cvs/filemod.o will not be ignored
test1/cvs/fileutd.h will be ignored
test1/cvs/fileoth will be ignored
test1/cvs/dirutd will not be ignored
test1/cvs/dirbad will not be ignored
test1/cvs/CVS will not be ignored
test1/cvs/CVS/Entries will not be ignored
test1/cvs/CVS/Root will not be ignored
test1/cvs/CVS/Whatever will be ignored
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Parsing CVS entries
 --> fileutd: 1159985080
test1/cvs/dirutd/fileutd will not be ignored
test1/cvs/dirutd/fileoth will be ignored
test1/cvs/diroth is not controlled
test1/cvs/CVS is not controlled

Only consider controlled modified and non-controlled files
test1 is not controlled
 -> Parsing CVS entries
 --> dir space: D
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
test1/cvs/nofile will not be ignored
test1/cvs/filenew.c will not be ignored
test1/cvs/filemod.o will not be ignored
test1/cvs/fileutd.h will be ignored
test1/cvs/fileoth will not be ignored
test1/cvs/dirutd will not be ignored
test1/cvs/dirbad will not be ignored
test1/cvs/CVS will not be ignored
test1/cvs/CVS/Entries will not be ignored
test1/cvs/CVS/Root will not be ignored
test1/cvs/CVS/Whatever will be ignored
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Parsing CVS entries
 --> fileutd: 1159985080
test1/cvs/dirutd/fileutd will not be ignored
test1/cvs/dirutd/fileoth will not be ignored
test1/cvs/diroth is not controlled
test1/cvs/CVS is not controlled

Only consider non-controlled files
test1 is not controlled
 -> Parsing CVS entries
 --> dir space: D
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
test1/cvs/nofile will not be ignored
test1/cvs/filenew.c will be ignored
test1/cvs/filemod.o will be ignored
test1/cvs/fileutd.h will be ignored
test1/cvs/fileoth will not be ignored
test1/cvs/dirutd will be ignored
test1/cvs/dirbad will be ignored
test1/cvs/CVS will not be ignored
test1/cvs/CVS/Entries will not be ignored
test1/cvs/CVS/Root will not be ignored
test1/cvs/CVS/Whatever will be ignored
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Parsing CVS entries
 --> fileutd: 1159985080
test1/cvs/dirutd/fileutd will be ignored
test1/cvs/dirutd/fileoth will not be ignored
test1/cvs/diroth is not controlled
test1/cvs/CVS is not controlled
