test1 is not under CVS control
Parsing CVS entries
 -> f filenew.c
 -> f filemod.o
 -> f fileutd.h
 -> d dirbad
 -> d dirutd
List: 5 file(s)
-> filenew.c (f)
-> filemod.o (f)
-> fileutd.h (f)
-> dirbad (d)
-> dirutd (d)
test1/cvs/nofile is not under CVS control
test1/cvs/fileoth is not under CVS control
test1/cvs/diroth is not under CVS control
test1/cvs/CVS is not under CVS control
Directory should be under CVS control: test1/cvs/diroth
Parsing CVS entries
 -> f fileutd
List: 1 file(s)
-> fileutd (f)
test1/cvs/dirutd/fileoth is not under CVS control
test1/cvs/dirbad is not under CVS control
test1/cvs/CVS is not under CVS control
