db::open status 1

Test: getdir
Check test_db/data dir: 0
febatest1 status: 0, getdir_path: test_db/data/fe/ba/test1
fe98test2 status: 0, getdir_path: test_db/data/fe/98/test2
fe98test3 status: 1, getdir_path: test_db/data/fe/98/test3
fetest4 status: 1, getdir_path: test_db/data/fe/te/st4
fedc76test5 status: 1, getdir_path: test_db/data/fe/dc/76/test5
fedc76test6 status: 1, getdir_path: test_db/data/fe/dc/76/test6
fedc76test6 status: 0, getdir_path: test_db/data/fe/dc/76/test6

Test: write and read back with auto-compression
Checking data, sizes: f=13 z=33 (33)
Adding uncompressed data for 59ca0efa9f5633cb0371bbc0355478d8-0
59ca0efa9f5633cb0371bbc0355478d8-0  test1/testfile
Meta file contents: 
13	+
59ca0efa9f5633cb0371bbc0355478d8-0 13\r
59ca0efa9f5633cb0371bbc0355478d8-0  test_db/blah

Test: write and read back with forbidden compression
59ca0efa9f5633cb0371bbc0355478d8-0  test1/testfile
Meta file contents: 
13	-
59ca0efa9f5633cb0371bbc0355478d8-0 13\r
59ca0efa9f5633cb0371bbc0355478d8-0  test_db/blah

Test: write and read back with compression
                                     \r
Adding compressed data for 59ca0efa9f5633cb0371bbc0355478d8-0
59ca0efa9f5633cb0371bbc0355478d8-0  test1/testfile
Meta file contents: 
13	 
Warning: 59ca0efa9f5633cb0371bbc0355478d8-0: Adding missing metadata
59ca0efa9f5633cb0371bbc0355478d8-0 13 33\r
Size reported: 13
Meta file contents: 
13	 
59ca0efa9f5633cb0371bbc0355478d8-0 13 33\r
                                        \r
Replacing with uncompressed data for 59ca0efa9f5633cb0371bbc0355478d8-0
59ca0efa9f5633cb0371bbc0355478d8-0  test_db/blah

Test: organise
Lesser:
test_db/data/zz:
000001

test_db/data/zz/000001:
Equal:
test_db/data/zz:
00
.nofiles

test_db/data/zz/00:
0001
0002

test_db/data/zz/00/0001:

test_db/data/zz/00/0002:
Greater:
test_db/data/zz:
00
.nofiles

test_db/data/zz/00:
00
.nofiles

test_db/data/zz/00/00:
01
02
03

test_db/data/zz/00/00/01:

test_db/data/zz/00/00/02:

test_db/data/zz/00/00/03:

Test: read-only mode

Test: do nothing

Test: scan - metadata check/correct
 * missing
Warning: 59ca0efa9f5633cb0371bbc0355478d8-0: Adding missing metadata
59ca0efa9f5633cb0371bbc0355478d8-0 13 38\r
 * check
59ca0efa9f5633cb0371bbc0355478d8-0 13 38\r
 * missing
                                        \r
Warning: d41d8cd98f00b204e9800998ecf8427e: Setting missing metadata
d41d8cd98f00b204e9800998ecf8427e 0\r
 * check
d41d8cd98f00b204e9800998ecf8427e 0\r

Test: check - metadata check/correct
 * missing
                                  \r
Warning: 59ca0efa9f5633cb0371bbc0355478d8-0: Adding missing metadata
59ca0efa9f5633cb0371bbc0355478d8-0 13 38\r
 * wrong
                                        \r
Error: 59ca0efa9f5633cb0371bbc0355478d8-0: -1: Correcting wrong metadata
59ca0efa9f5633cb0371bbc0355478d8-0 13 38\r
 * check
59ca0efa9f5633cb0371bbc0355478d8-0 13 38\r
 * missing
                                        \r
Warning: d41d8cd98f00b204e9800998ecf8427e: Adding missing metadata
d41d8cd98f00b204e9800998ecf8427e 0\r
 * wrong
                                  \r
Error: d41d8cd98f00b204e9800998ecf8427e: -1: Correcting wrong metadata
d41d8cd98f00b204e9800998ecf8427e 0\r
 * check
d41d8cd98f00b204e9800998ecf8427e 0\r
