Error: Cannot initialize in read-only mode
db::open error status -1
Error: Given DB path does not exist: test_db
db::open error status -1
Error: Given DB path does not exist: test_db
db::open error status -1
Error: Given DB path does not contain a database: test_db
db::open error status -1
Error: Given DB path does not contain a database: test_db
See help for information on how to initialize the DB
db::open error status -1
Database initialized in test_db
Database open in read/write mode

Test: scan & check
Found 0 checksums
Crawling through DB
                                  \r
Found 0 valid and 0 broken data files
Database closed
Database open in read/write mode
File data gone
Found 0 checksums
Crawling through DB
59ca0efa9f5633cb0371bbc0355478d8-0\r
Error: Data missing for: 59ca0efa9f5633cb0371bbc0355478d8-0
                                  \r
Found 0 valid and 1 broken data files
Database closed
Database open in read/write mode
File data corrupted, surficial scan
Found 0 checksums
Crawling through DB
59ca0efa9f5633cb0371bbc0355478d8-0\r
                                  \r
Found 1 valid and 0 broken data files
Checksum(s) with data:
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
Obsolete checksum(s): 1
 -> 59ca0efa9f5633cb0371bbc0355478d8-0: removed
Database closed
Database open in read/write mode
Found 0 checksums
Crawling through DB
                                  \r
Found 0 valid and 0 broken data files
File data corrupted, thorough scan
Database closed
Database open in read-only mode
Crawling through DB data
59ca0efa9f5633cb0371bbc0355478d8-0\r
Error: Data corrupted for: 59ca0efa9f5633cb0371bbc0355478d8-0
                                  \r
Found 0 valid and 1 broken data files
Database closed
Database open in read/write mode
Found 0 checksums
Crawling through DB
59ca0efa9f5633cb0371bbc0355478d8-0\r
Corrupted data for: 59ca0efa9f5633cb0371bbc0355478d8-0 removed
                                  \r
Found 0 valid and 1 broken data files
Scan again
Database closed

Test: lock
Database open in read/write mode
Database closed
Warning: Lock reset
Database open in read/write mode
Database closed
Error: Lock taken by process with pid 1
Error: Lock taken by an unidentified process!
Error: Lock taken by an unidentified process!

Test: read-only mode
Database open in read-only mode
Database closed

Test: fill in DB
Database open in read/write mode
Reading list of missing checksums
Created myClient's list
Database client myClient open in read/write mode
Adding compressed file data to DB in: test_db/data/285b35198a5e188b3a0df3ed33f93a26-0
Adding file data to DB in: test_db/data/d41d8cd98f00b204e9800998ecf8427e-0
Adding file data to DB in: test_db/data/59ca0efa9f5633cb0371bbc0355478d8-0
Adding file data to DB in: test_db/data/3d546a1ce46c6ae10ad34ab8a81c542e-0
Database client myClient modified
Database client myClient closed
Database closed
[ 1] /client_path/subdir            d      0 755
[ 2] /client_path/subdir/testfile   f     12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 3] /client_path/subdir/testfile2  f     12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 4] /client_path/test space        f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] /client_path/testfile          f     13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 6] other_path/testdir             d      0 755
[ 7] other_path/testfile            f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0

Test: do nothing
Database open in read/write mode
Database closed
[ 1] /client_path/subdir            d      0 755
[ 2] /client_path/subdir/testfile   f     12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 3] /client_path/subdir/testfile2  f     12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 4] /client_path/test space        f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] /client_path/testfile          f     13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 6] other_path/testdir             d      0 755
[ 7] other_path/testfile            f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0

Test: read clients
Database open in read-only mode
Database closed
List of clients: 1
 -> myClient

Test: read paths in myClient
Database open in read-only mode
Database client myClient open in read-only mode
Database client myClient closed
List of paths: 2
 -> /client_path
 -> other_path

Test: read paths in myClient below /client_path
Database client myClient open in read-only mode
Database client myClient closed
List of paths: 3
 -> /client_path/subdir
 -> /client_path/test space
 -> /client_path/testfile

Test: read paths in myClient below other_path
Database client myClient open in read-only mode
Database client myClient closed
List of paths: 2
 -> other_path/testdir
 -> other_path/testfile

Test: read paths in myClient below /client_path/subdir
Database client myClient open in read-only mode
Database client myClient closed
List of paths: 2
 -> /client_path/subdir/testfile
 -> /client_path/subdir/testfile2
Database closed

Test: scan
Database open in read/write mode
Reading myClient's list
Found 4 checksums
Crawling through DB
285b35198a5e188b3a0df3ed33f93a26-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
Error: Data missing for: 3d546a1ce46c6ae10ad34ab8a81c542e-0
59ca0efa9f5633cb0371bbc0355478d8-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
e5ed795e721b69c53a52482d6bdcb149-0\r
                                  \r
Found 4 valid and 1 broken data files
Checksum(s) from list:
 -> 285b35198a5e188b3a0df3ed33f93a26-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
Checksum(s) with data:
 -> 285b35198a5e188b3a0df3ed33f93a26-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> e5ed795e721b69c53a52482d6bdcb149-0
Obsolete checksum(s): 1
 -> e5ed795e721b69c53a52482d6bdcb149-0: removed
Warning: Missing checksum(s): 1
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
List of missing checksums contains 1 item(s)
Database closed

Test: concurrent access
Database open in read/write mode
Database open in read-only mode
Database client myClient open in read-only mode
Reading list of missing checksums
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
Database client myClient open in read/write mode
D /client_path/subdir
D /client_path/subdir/testfile
D /client_path/subdir/testfile2
D /client_path/test space
D /client_path/testfile
D other_path/testdir
D other_path/testfile
Database client myClient modified
Database client myClient closed
Database client myClient closed
Database closed
[ 8] /client_path/new_link          l      8 777 testfile
[ 9] /client_path/subdir            [rm]
[11] /client_path/subdir/testfile   [rm]
[13] /client_path/subdir/testfile2  [rm]
[15] /client_path/test space        [rm]
[17] /client_path/testfile          [rm]
[19] other_path/testdir             [rm]
[21] other_path/testfile            [rm]
List of paths: 3
 -> /client_path/subdir
 -> /client_path/test space
 -> /client_path/testfile
Database open in read-only mode
Database client myClient open in read-only mode
Database client myClient closed
Database closed
List of paths: 4
 -> /client_path/new_link
 -> /client_path/subdir
 -> /client_path/test space
 -> /client_path/testfile

Test: convert list(s) format
Converting database list
Conversion successful
Listing client: client
[1195557261] C:/Test/File.TXT               f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
Listing client: hisClient
[1195557261] test1/dir space                d      0 755
[1195557261] test1/dir space/file space     f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] test1/test space               f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] test1/testdir                  d      0 755
[1195557261] test1/testfile                 f     13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[1195557261] test1/testlink                 l      8 777 testfile
[1195557261] test1/testpipe                 p      0 644
Listing client: leClient
[1195557261] test2/testdir                  d      0 755
[1195557261] test2/testfile                 f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[1195557261] test2/testfile2                f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[1195557261] test2/testfile~                f 524288 644 59071590099d21dd439896592338bf95-0
[1195557261] test2/testlink                 l      8 777 testfile
Listing client: leClient:1
[1195557261] C:/test2/testdir               d      0 755
[1195557261] C:/test2/testfile              f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[1195557261] C:/test2/testfile2             f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[1195557261] C:/test2/testfile~             f 524288 644 59071590099d21dd439896592338bf95-0
[1195557261] C:/test2/testlink              l      8 777 testfile
Listing client: myClient
[1195557261] /home/User/test/File2.txt      f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
Listing client: myhost
[1195557261] test1/cvs                      d      0 755
[1195557261] test1/cvs/CVS                  d      0 755
[1195557261] test1/cvs/CVS/Entries          f    141 644 63b52e85e7a255c09df5cca819b74a88-0
[1195557261] test1/cvs/dirbad               d      0 755
[1195557261] test1/cvs/dirutd               d      0 755
[1195557261] test1/cvs/dirutd/CVS           d      0 755
[1195557261] test1/cvs/dirutd/CVS/Entries   f     42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[1195557261] test1/cvs/dirutd/fileutd       f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] test1/cvs/filenew.c            f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] test1/cvs/fileutd.h            f      0 644 d41d8cd98f00b204e9800998ecf8427e-0
