Database initialized in test_db
 -> Database open in read/write mode

Test: check
Scanning database contents thoroughly: 0 files
File data gone
Error: data missing for 59ca0efa9f5633cb0371bbc0355478d8-0
File data corrupted, surficial scan
File data corrupted, thorough scan
Error: data corrupted for 59ca0efa9f5633cb0371bbc0355478d8-0
 -> Journal is empty, not merging
 -> Database closed

Test: lock
 -> Database open in read/write mode
 -> Journal is empty, not merging
 -> Database closed
Warning: lock reset
 -> Database open in read/write mode
 -> Journal is empty, not merging
 -> Database closed
Error: lock taken by process with pid 1
Error: lock taken by an unidentified process!
Error: lock taken by an unidentified process!

Test: read-only mode
 -> Database open in read-only mode
 -> Database closed

Test: fill in DB
 -> Database open in read/write mode
Adding compressed file data to DB in: test_db/data/285b35198a5e188b3a0df3ed33f93a26-0
Adding file data to DB in: test_db/data/d41d8cd98f00b204e9800998ecf8427e-0
Adding file data to DB in: test_db/data/59ca0efa9f5633cb0371bbc0355478d8-1
Adding file data to DB in: test_db/data/3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> Database closed
[ 1] myClient         /client_path/subdir                d     0 755
[ 2] myClient         /client_path/subdir/testfile       f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 3] myClient         /client_path/subdir/testfile2      f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 4] myClient         /client_path/test space            f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] myClient         /client_path/testfile              f    13 644 59ca0efa9f5633cb0371bbc0355478d8-1
[ 6] myClient         other_path/testdir                 d     0 755
[ 7] myClient         other_path/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0

Test: do nothing
 -> Database open in read/write mode
 -> Journal is empty, not merging
 -> Database closed
[ 1] myClient         /client_path/subdir                d     0 755
[ 2] myClient         /client_path/subdir/testfile       f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 3] myClient         /client_path/subdir/testfile2      f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 4] myClient         /client_path/test space            f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] myClient         /client_path/testfile              f    13 644 59ca0efa9f5633cb0371bbc0355478d8-1
[ 6] myClient         other_path/testdir                 d     0 755
[ 7] myClient         other_path/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0

Test: read clients
 -> Database open in read-only mode
 -> Database closed
List of clients: 1
 -> myClient

Test: read paths in myClient
 -> Database open in read-only mode
 -> Database closed
List of paths: 2
 -> /client_path
 -> other_path

Test: read paths in myClient below /client_path
 -> Database open in read-only mode
 -> Database closed
List of paths: 3
 -> /client_path/subdir
 -> /client_path/test space
 -> /client_path/testfile

Test: read paths in myClient below other_path
 -> Database open in read-only mode
 -> Database closed
List of paths: 2
 -> other_path/testdir
 -> other_path/testfile

Test: read paths in myClient below /client_path/subdir
 -> Database open in read-only mode
 -> Database closed
List of paths: 2
 -> /client_path/subdir/testfile
 -> /client_path/subdir/testfile2

Test: crawl
 -> Database open in read/write mode
 -> checking: 285b35198a5e188b3a0df3ed33f93a26-0
 -> checking: 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> checking: 59ca0efa9f5633cb0371bbc0355478d8-0
Error: data corrupted for 59ca0efa9f5633cb0371bbc0355478d8-0
 -> checking: 59ca0efa9f5633cb0371bbc0355478d8-1
 -> checking: d41d8cd98f00b204e9800998ecf8427e-0
 -> Journal is empty, not merging
 -> Database closed
List of valid checksums
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-1
 -> d41d8cd98f00b204e9800998ecf8427e-0

Test: concurrent access
 -> Database open in read/write mode
 -> Database open in read-only mode
D /client_path/subdir
D /client_path/subdir/testfile
D /client_path/subdir/testfile2
D /client_path/test space
D /client_path/testfile
D other_path/testdir
D other_path/testfile
 -> Database closed
 -> Database closed
[ 8] myClient         /client_path/new_link              l     8 777 testfile
[ 9] myClient         /client_path/subdir                [rm]
[11] myClient         /client_path/subdir/testfile       [rm]
[13] myClient         /client_path/subdir/testfile2      [rm]
[15] myClient         /client_path/test space            [rm]
[17] myClient         /client_path/testfile              [rm]
[19] myClient         other_path/testdir                 [rm]
[21] myClient         other_path/testfile                [rm]
List of paths: 3
 -> /client_path/subdir
 -> /client_path/test space
 -> /client_path/testfile
 -> Database open in read-only mode
 -> Database closed
List of paths: 4
 -> /client_path/new_link
 -> /client_path/subdir
 -> /client_path/test space
 -> /client_path/testfile

Test: check format
Converting database list
Clients found: 6
 smb://client -> client$
 nfs://hisClient -> hisClient#
DB list rewinded
 nfs://leClient -> leClient#
 smb://leClient -> leClient$
 nfs://myClient -> myClient#
DB list rewinded
 file://myhost -> myhost#
DB list rewinded
Conversion successful
 -> Database open in read/write mode
 -> Journal is empty, not merging
 -> Database closed
[1195557261] client$          C:/Test/File.TXT                   f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] hisClient#       test1/dir space                    d     0 755
[1195557261] hisClient#       test1/dir space/file space         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] hisClient#       test1/test space                   f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] hisClient#       test1/testdir                      d     0 755
[1195557261] hisClient#       test1/testfile                     f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[1195557261] hisClient#       test1/testlink                     l     8 777 testfile
[1195557261] hisClient#       test1/testpipe                     p     0 644
[1195557261] leClient#        test2/testdir                      d     0 755
[1195557261] leClient#        test2/testfile                     f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[1195557261] leClient#        test2/testfile2                    f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[1195557261] leClient#        test2/testfile~                    f 524288 644 59071590099d21dd439896592338bf95-0
[1195557261] leClient#        test2/testlink                     l     8 777 testfile
[1195557261] leClient$        C:/test2/testdir                   d     0 755
[1195557261] leClient$        C:/test2/testfile                  f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[1195557261] leClient$        C:/test2/testfile2                 f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[1195557261] leClient$        C:/test2/testfile~                 f 524288 644 59071590099d21dd439896592338bf95-0
[1195557261] leClient$        C:/test2/testlink                  l     8 777 testfile
[1195557261] myClient#        /home/User/test/File2.txt          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] myhost#          test1/cvs                          d     0 755
[1195557261] myhost#          test1/cvs/CVS                      d     0 755
[1195557261] myhost#          test1/cvs/CVS/Entries              f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[1195557261] myhost#          test1/cvs/dirbad                   d     0 755
[1195557261] myhost#          test1/cvs/dirutd                   d     0 755
[1195557261] myhost#          test1/cvs/dirutd/CVS               d     0 755
[1195557261] myhost#          test1/cvs/dirutd/CVS/Entries       f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[1195557261] myhost#          test1/cvs/dirutd/fileutd           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] myhost#          test1/cvs/filenew.c                f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] myhost#          test1/cvs/fileutd.h                f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
