Database initialized
 -> Database open in read/write mode

Test: getdir
Check test_db/data dir: 0
febatest1 status: 0, getdir_path: test_db/data/fe/ba/test1
fe98test2 status: 0, getdir_path: test_db/data/fe/98/test2
fe98test3 status: 1, getdir_path: test_db/data/fe/98/test3
fetest4 status: 1, getdir_path: test_db/data/fe/te/st4
fedc76test5 status: 1, getdir_path: test_db/data/fe/dc/76/test5
fedc76test6 status: 1, getdir_path: test_db/data/fe/dc/76/test6
fedc76test6 status: 0, getdir_path: test_db/data/fe/dc/76/test6

Test: write and read back
Adding file data to DB in: test_db/data/59/ca0efa9f5633cb0371bbc0355478d8-0
59ca0efa9f5633cb0371bbc0355478d8-0  test1/testfile
59ca0efa9f5633cb0371bbc0355478d8-0  test_db/blah

Test: write and read back with compression
59ca0efa9f5633cb0371bbc0355478d8-0  test1/testfile
59ca0efa9f5633cb0371bbc0355478d8-0  test_db/blah

Test: check
db.check: Structure needs cleaning
db.check: Structure needs cleaning
db.check: Invalid argument
Scanning database contents thoroughly: 0 files
File data gone
Error: data missing for 59ca0efa9f5633cb0371bbc0355478d8-0
db.check: No such file or directory
File data corrupted, surficial scan
File data corrupted, thorough scan
Error: data corrupted for 59ca0efa9f5633cb0371bbc0355478d8-0
db.check: Structure needs cleaning

Test: organise
Lesser:
test_db/data/zz:
000001

test_db/data/zz/000001:
Equal:
test_db/data/zz:
00
.nofiles

test_db/data/zz/00:
0001
0002

test_db/data/zz/00/0001:

test_db/data/zz/00/0002:
Greater:
test_db/data/zz:
00
.nofiles

test_db/data/zz/00:
00
.nofiles

test_db/data/zz/00/00:
01
02
03

test_db/data/zz/00/00/01:

test_db/data/zz/00/00/02:

test_db/data/zz/00/00/03:
 -> Journal is empty, not merging
 -> Database closed

Test: lock
 -> Database open in read/write mode
 -> Journal is empty, not merging
 -> Database closed
Warning: lock reset
 -> Database open in read/write mode
 -> Journal is empty, not merging
 -> Database closed
Error: lock taken by process with pid 1
Error: lock taken by an unidentified process!
Error: lock taken by an unidentified process!

Test: read-only mode
 -> Database open in read-only mode
 -> Database closed

Test: fill in DB
 -> Database open in read/write mode
Adding file data to DB in: test_db/data/d4/1d8cd98f00b204e9800998ecf8427e-0
Adding file data to DB in: test_db/data/59/ca0efa9f5633cb0371bbc0355478d8-1
Adding compressed file data to DB in: test_db/data/28/5b35198a5e188b3a0df3ed33f93a26-0
Adding file data to DB in: test_db/data/3d/546a1ce46c6ae10ad34ab8a81c542e-0
 -> Database closed
[ 1] myClient         /client_path/test space            f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 2] myClient         /client_path/testfile              f    13 644 59ca0efa9f5633cb0371bbc0355478d8-1
[ 3] myClient         /client_path/subdir                d     0 755
[ 4] myClient         /client_path/subdir/testfile       f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] myClient         /client_path/subdir/testfile2      f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 6] myClient         other_path/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[ 7] myClient         other_path/testdir                 d     0 755

Test: do nothing
 -> Database open in read/write mode
 -> Journal is empty, not merging
 -> Database closed
[ 1] myClient         /client_path/test space            f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 2] myClient         /client_path/testfile              f    13 644 59ca0efa9f5633cb0371bbc0355478d8-1
[ 3] myClient         /client_path/subdir                d     0 755
[ 4] myClient         /client_path/subdir/testfile       f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] myClient         /client_path/subdir/testfile2      f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 6] myClient         other_path/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[ 7] myClient         other_path/testdir                 d     0 755

Test: read clients
 -> Database open in read-only mode
 -> Database closed
List of clients: 1
 -> myClient

Test: read paths in myClient
 -> Database open in read-only mode
 -> Database closed
List of paths: 2
 -> /client_path
 -> other_path

Test: read paths in myClient below /client_path
 -> Database open in read-only mode
 -> Database closed
List of paths: 3
 -> /client_path/test space
 -> /client_path/testfile
 -> /client_path/subdir

Test: read paths in myClient below other_path
 -> Database open in read-only mode
 -> Database closed
List of paths: 2
 -> other_path/testfile
 -> other_path/testdir

Test: read paths in myClient below /client_path/subdir
 -> Database open in read-only mode
 -> Database closed
List of paths: 2
 -> /client_path/subdir/testfile
 -> /client_path/subdir/testfile2

Test: crawl
 -> Database open in read/write mode
 -> checking: 285b35198a5e188b3a0df3ed33f93a26-0
 -> checking: 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> checking: 59ca0efa9f5633cb0371bbc0355478d8-0
File data corrupted for 59ca0efa9f5633cb0371bbc0355478d8-0, removed
 -> checking: 59ca0efa9f5633cb0371bbc0355478d8-1
 -> checking: d41d8cd98f00b204e9800998ecf8427e-0
 -> checking: fe98test2
No such file or directory: fe98test2
 -> checking: febatest1
No such file or directory: febatest1
 -> checking: fedc76test6
No such file or directory: fedc76test6
 -> checking: zz000001
No such file or directory: zz000001
 -> checking: zz000002
No such file or directory: zz000002
 -> checking: zz000003
No such file or directory: zz000003
 -> Journal is empty, not merging
 -> Database closed
List of valid checksums
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-1
 -> d41d8cd98f00b204e9800998ecf8427e-0

Test: concurrent access
 -> Database open in read/write mode
 -> Database open in read-only mode
D /client_path/test space
D /client_path/testfile
D /client_path/subdir
D /client_path/subdir/testfile
D /client_path/subdir/testfile2
D other_path/testfile
D other_path/testdir
 -> Database closed
 -> Database closed
[ 8] myClient         /client_path/new_link              l     8 777 testfile
[ 9] myClient         /client_path/test space            [rm]
[11] myClient         /client_path/testfile              [rm]
[13] myClient         /client_path/subdir                [rm]
[15] myClient         /client_path/subdir/testfile       [rm]
[17] myClient         /client_path/subdir/testfile2      [rm]
[19] myClient         other_path/testfile                [rm]
[21] myClient         other_path/testdir                 [rm]
List of paths: 3
 -> /client_path/test space
 -> /client_path/testfile
 -> /client_path/subdir
 -> Database open in read-only mode
 -> Database closed
List of paths: 4
 -> /client_path/new_link
 -> /client_path/test space
 -> /client_path/testfile
 -> /client_path/subdir

Test: check format
Converting database list
Clients found: 6
 smb://client -> client$
 nfs://hisClient -> hisClient#
DB list rewinded
 nfs://leClient -> leClient#
 smb://leClient -> leClient$
 nfs://myClient -> myClient#
DB list rewinded
 file://myhost -> myhost#
DB list rewinded
Conversion successful
 -> Database open in read/write mode
 -> Journal is empty, not merging
 -> Database closed
[1195557261] client$          C:/Test/File.TXT                   f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] hisClient#       test1/dir space                    d     0 755
[1195557261] hisClient#       test1/dir space/file space         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] hisClient#       test1/test space                   f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] hisClient#       test1/testdir                      d     0 755
[1195557261] hisClient#       test1/testfile                     f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[1195557261] hisClient#       test1/testlink                     l     8 777 testfile
[1195557261] hisClient#       test1/testpipe                     p     0 644
[1195557261] leClient#        test2/testdir                      d     0 755
[1195557261] leClient#        test2/testfile                     f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[1195557261] leClient#        test2/testfile2                    f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[1195557261] leClient#        test2/testfile~                    f 524288 644 59071590099d21dd439896592338bf95-0
[1195557261] leClient#        test2/testlink                     l     8 777 testfile
[1195557261] leClient$        C:/test2/testdir                   d     0 755
[1195557261] leClient$        C:/test2/testfile                  f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[1195557261] leClient$        C:/test2/testfile2                 f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[1195557261] leClient$        C:/test2/testfile~                 f 524288 644 59071590099d21dd439896592338bf95-0
[1195557261] leClient$        C:/test2/testlink                  l     8 777 testfile
[1195557261] myClient#        /home/User/test/File2.txt          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] myhost#          test1/cvs                          d     0 755
[1195557261] myhost#          test1/cvs/CVS                      d     0 755
[1195557261] myhost#          test1/cvs/CVS/Entries              f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[1195557261] myhost#          test1/cvs/dirbad                   d     0 755
[1195557261] myhost#          test1/cvs/dirutd                   d     0 755
[1195557261] myhost#          test1/cvs/dirutd/CVS               d     0 755
[1195557261] myhost#          test1/cvs/dirutd/CVS/Entries       f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[1195557261] myhost#          test1/cvs/dirutd/fileutd           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] myhost#          test1/cvs/filenew.c                f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[1195557261] myhost#          test1/cvs/fileutd.h                f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
