Tools Test
Our mask = 0022

Test: path
a/b
c
d

Test: file read (no cache)
read size: 10485760 (10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file write (with cache)
write size: 7 (7), checksum: aa5f704d9a0eccde71070d8697a8c1ff
123abc

Test: file copy (read + write (no cache))
read size: 10485760 (10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10485760 (10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file compress (read + compress write), with last zero-size write call
read size: 10485760 (10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size (wrong): 8214 (10208), checksum: b7350db49d036137b2ef752a82145e91

Test: file uncompress (uncompress read + write)
read size: 10485760 (10208), checksum: b7350db49d036137b2ef752a82145e91
write size: 10485760 (10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file compress (read + compress write)
read size: 10485760 (10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size (wrong): 8214 (10208), checksum: b7350db49d036137b2ef752a82145e91

Test: file recompress (uncompress read + compress write), no closing
read size: 10485760 (10208), checksum: b7350db49d036137b2ef752a82145e91
write size (wrong): 8214 (10208), checksum: b7350db49d036137b2ef752a82145e91

Test: file compare (both compressed)
  whole files
files are equal
  exact size
files are equal
  first 2000 bytes
files are equal
  first 100 bytes
files are equal

Test: file compare (one compressed)
  whole files
files differ
  exact size
files differ
  first 2000 bytes
files differ
  first 100 bytes
files differ

Test: computeChecksum
Checksum: 59ca0efa9f5633cb0371bbc0355478d8

Test: copy
checksum in: b7350db49d036137b2ef752a82145e91
checksum out: f1c9645dbc14efddc7d8a322685f26eb

Test: interrupted copy
Error copying file: Operation canceled

Test: getLine
Reading empty file:
Reading uncompressed file:
Line: abcdef

Line: ghi

Reading compressed file:
Line: abcdef

Line: ghi

Reading compressed file (line length = 600):
Line: 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890

Line: 123456789

readline
readline(a): 0
a

readline( 	a 	b): 0
a
b

readline(	 ab): 0
ab

readline(	 ab cd): 0
ab
cd

readline(	 ab cd	ef # blah): 0
ab
cd
ef

readline(	 'ab' 'cd'	'ef' # blah): 0
ab
cd
ef

readline(	 "ab" 'cd'	"ef" # blah): 0
ab
cd
ef

readline(	 ab cd	ef 'gh ij	kl' "mn op	qr" 	# blah): 0
ab
cd
ef
gh ij	kl
mn op	qr

readline(	 ab cd	ef 'gh "ij\'	kl' "mn 'op\"	qr" 	# blah): 0
ab
cd
ef
gh "ij'	kl
mn 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr" 	# blah): 0
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl): 1
a\b
cd
ef
g\h "ij'	kl

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr): 1
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

Name: testfile, path = test1/testfile, type = f, mtime = 1, size = 13, uid = 1, gid = 1, mode = 644
Name: testlink, path = test1/testlink, type = l, mtime = 1, size = 8, uid = 1, gid = 1, mode = 777, link = testfile
 > Dir.: testdir, path = test1/testdir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 > Dir.: subdir, path = test1/subdir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 -> Oth.: testfile, path = test1/subdir/testfile, type = f, mtime = 1, size = 12, uid = 1, gid = 1, mode = 644
 -> Oth.: testfile1, path = test1/subdir/testfile1, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> Oth.: testfile2, path = test1/subdir/testfile2, type = f, mtime = 1, size = 12, uid = 1, gid = 1, mode = 644

Validity tests
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 1

Creation tests
File is file? 0
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 0
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0
Create
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0
Create again
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0

Parsing test
 > Dir.: test1, path = test1, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 -> Dir.: cvs, path = test1/cvs, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 --> Dir.: CVS, path = test1/cvs/CVS, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 ---> File: Entries, path = test1/cvs/CVS/Entries, type = f, mtime = 1, size = 161, uid = 1, gid = 1, mode = 644
 --> Dir.: dirbad, path = test1/cvs/dirbad, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 ---> File: fileoth, path = test1/cvs/dirbad/fileoth, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 ---> File: fileutd, path = test1/cvs/dirbad/fileutd, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 --> Dir.: diroth, path = test1/cvs/diroth, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 --> Dir.: dirutd, path = test1/cvs/dirutd, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 ---> Dir.: CVS, path = test1/cvs/dirutd/CVS, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 ----> File: Entries, path = test1/cvs/dirutd/CVS/Entries, type = f, mtime = 1, size = 42, uid = 1, gid = 1, mode = 644
 ---> File: fileoth, path = test1/cvs/dirutd/fileoth, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 ---> File: fileutd, path = test1/cvs/dirutd/fileutd, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 --> File: filemod.o, path = test1/cvs/filemod.o, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 --> File: filenew.c, path = test1/cvs/filenew.c, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 --> File: fileoth, path = test1/cvs/fileoth, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 --> File: fileutd.h, path = test1/cvs/fileutd.h, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> Dir.: dir space, path = test1/dir space, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 --> File: file space, path = test1/dir space/file space, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> File: rwfile_dest, path = test1/rwfile_dest, type = f, mtime = 1, size = 409600, uid = 1, gid = 1, mode = 644
 -> File: rwfile_source, path = test1/rwfile_source, type = f, mtime = 1, size = 10208, uid = 1, gid = 1, mode = 644
 -> Dir.: subdir, path = test1/subdir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 --> File: testfile, path = test1/subdir/testfile, type = f, mtime = 1, size = 12, uid = 1, gid = 1, mode = 644
 --> File: testfile1, path = test1/subdir/testfile1, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 --> File: testfile2, path = test1/subdir/testfile2, type = f, mtime = 1, size = 12, uid = 1, gid = 1, mode = 644
 -> File: test space, path = test1/test space, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> Dir.: testdir, path = test1/testdir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 -> File: testfile, path = test1/testfile, type = f, mtime = 1, size = 13, uid = 1, gid = 1, mode = 644
 -> File: testfile~, path = test1/testfile~, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> Link: testlink, path = test1/testlink, type = l, mtime = 1, size = 8, uid = 1, gid = 1, mode = 777, link = testfile
 -> Oth.: testpipe, path = test1/testpipe, type = p, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> Dir.: toucheddir, path = test1/toucheddir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 -> File: touchedfile, path = test1/touchedfile, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644

Difference test
f1 and f2 are identical
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
l1 and l2 are identical
l1 and l2 differ
l1 and l2 differ

End of tests
