Tools Test
Our mask = 0022

Test: constructors
0: 
0: 
3: 123
7: 123/456
4: /789
11: 123/456/789
15: 123/456/789/159
25: //1123//456/7899//11599//

Test: basename and dirname
this/is a path/to a/file -> base: file, dir: this/is a path/to a
this is a file -> base: this is a file, dir: .
this is a path/ -> base: , dir: this is a path

Test: fromDos
a:\backup\ -> A:/backup/
z:/backup -> z:/backup
1:/backup -> 1:/backup
f;/backup -> f;/backup
l:|backup -> l:|backup
this\is a path/ Unix\ cannot cope with/\ -> this/is a path/ Unix/ cannot cope with//
this/is a path/ Unix/ cannot cope with// -> this/is a path/ Unix/ cannot cope with//

Test: noTrailingSlashes
this/is a path/ Unix/ cannot cope with// -> this/is a path/ Unix/ cannot cope with
this/is a path/ Unix/ cannot cope with -> this/is a path/ Unix/ cannot cope with
 -> 
/ -> 

Test: compare
a <> a: 0
a <> b: -1
b <> a: 1
a1 <> b: -1
b <> a1: 1
a1 <> a: 1
a <> a1: -1
a/ <> a: 1
a <> a/: -1
a	 <> a/: -1
a/ <> a	 1
a	 <> a	 0
a
 <> a/: -1
a/ <> a
 1
a
 <> a
 0
a/ <> a.: -1
a. <> a/: 1
a/ <> a-: -1
a- <> a/: 1
a/ <> a/: 0
abcd <> abce, 3: 0
abcd <> abce, 4: -1
abcd <> abce, 5: -1

Test: file original size
write size: 4 (38, 4), checksum: ec10746b8b223bf069e7a8e2424e2cf0
getOriginalSize: 25
originalSize: 25
write size: 4 (38, 4), checksum: dbcc0668f8a7ff2e7ff0765df343169d
getOriginalSize: 1147797409030816545
originalSize: 1147797409030816545

Test: file read (no cache)
Done:  10.0%
Done:  20.0%
Done:  30.0%
Done:  40.0%
Done:  50.0%
Done:  60.0%
Done:  70.0%
Done:  80.0%
Done:  90.0%
Done: 100.0%
read size: 10485760 (10485760, 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file write (with cache)
write size: 32 (32, 32), checksum: dabae94f9178f07f6e03ae89fd827c82
123abc
line
this is a long line

Test: file copy (read (cache) + write (no cache))
Done:   3.9%
Done:   7.8%
Done:  11.7%
Done:  15.6%
Done:  19.5%
Done:  23.4%
Done:  27.3%
Done:  31.3%
Done:  35.2%
Done:  39.1%
Done:  43.0%
Done:  46.9%
Done:  50.8%
Done:  54.7%
Done:  58.6%
Done:  62.5%
Done:  66.4%
Done:  70.3%
Done:  74.2%
Done:  78.1%
Done:  82.0%
Done:  85.9%
Done:  89.8%
Done:  93.8%
Done:  97.7%
Done: 100.0%
read size: 10485760 (10485760, 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10485760 (10485760, 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file compress (read + default compress write), with last zero-size write call
read size: 10485760 (10485760, 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10485760 (10208, 10485760), checksum: b7350db49d036137b2ef752a82145e91
getOriginalSize: Function not implemented
originalSize: failed

Test: file uncompress (uncompress read + write)
read size: 10485760 (10208, 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10485760 (10485760, 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: file compress (cached read + cached compress write)
read size: 10485760 (10485760, 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10485760 (10222, 10485760), checksum: 9fdf55642cb89bbff68b4fec9f8332d2
getOriginalSize: 10485760
originalSize: 10485760

Test: file recompress (cached uncompress read + uncached compress write), no closing
read size: 10485760 (10222, 10485760), checksum: f1c9645dbc14efddc7d8a322685f26eb
write size: 10485760 (10222, 10485760), checksum: ee7dc9a2bf10a13517b3bbcac5c4604c
getOriginalSize: 10222
originalSize: 10222

Test: file compare (both compressed)
  whole files
files are equal
  exact size
files are equal
  first 2000 bytes
files are equal
  first 100 bytes
files are equal

Test: file compare (one compressed)
  whole files
files differ
  exact size
files differ
  first 2000 bytes
files differ
  first 100 bytes
files differ

Test: computeChecksum
default read
Checksum: 59ca0efa9f5633cb0371bbc0355478d8
default read
Done:  70.4%
Done: 100.0%
Checksum: f81f70dceaca8b0cec354f33fa3f0909
default decompress read
Done:  70.4%
Done: 100.0%
Checksum: 81db27b3763d3c48ea035c54b8ebeaa3
default getLine
Done:  70.4%
Done: 100.0%
Checksum: f81f70dceaca8b0cec354f33fa3f0909
Size: 145461
default decompress getLine
Done:  70.4%
Done: 100.0%
Checksum: 81db27b3763d3c48ea035c54b8ebeaa3
Size: 145408
default decompress read
Checksum: f1c9645dbc14efddc7d8a322685f26eb

Test: copy
checksum in: f1c9645dbc14efddc7d8a322685f26eb
checksum out: f1c9645dbc14efddc7d8a322685f26eb
size in: 10222
size out: 10485760
checksum in: f1c9645dbc14efddc7d8a322685f26eb
checksum out: f1c9645dbc14efddc7d8a322685f26eb
size in: 10485760
size out: 10485760
checksum in: f1c9645dbc14efddc7d8a322685f26eb
checksum out: b7350db49d036137b2ef752a82145e91
size in: 10485760
size out: 10208

Test: interrupted copy
Error copying file: Operation canceled

Test: double copy
checksum in: f1c9645dbc14efddc7d8a322685f26eb
checksum out: b7350db49d036137b2ef752a82145e91
checksum out 2: b7350db49d036137b2ef752a82145e91
data in: 10485760
data out: 10485760
data out 2: 10485760
file out: 10208
file out 2: 10208

Test: getLine
Checksum: d41d8cd98f00b204e9800998ecf8427e
Reading empty file:
Checksum: d41d8cd98f00b204e9800998ecf8427e
Checksum: caf39f98439e467d895585e0740f015e
Reading uncompressed file:
Line: abcdef
Line: ghi
Checksum: caf39f98439e467d895585e0740f015e
Checksum: 6bb64092bb3d5dc7d3b2d4932f77199e
Reading compressed file:
Line: abcdef
Line: ghi
Checksum: caf39f98439e467d895585e0740f015e
Checksum: c118d6329b1675a9a72c296c2c58f0f4
Reading compressed file (line length = 600):
Line: 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
Line: 123456789
Checksum: 56a8cc63a390016b292f117c17addb5c
Reading compressed file (line length = 600), no checksum:
Line: 123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
Line: 123456789
Checksum: 

extractParams
readline(a): 0
a

readline( 	a 	b): 0
a
b

readline(	 ab): 0
ab

readline(	 ab cd): 0
ab
cd

readline(	 ab cd	ef # blah): 0
ab
cd
ef

readline(	 'ab' 'cd'	'ef' # blah): 0
ab
cd
ef

readline(	 "ab" 'cd'	"ef" # blah): 0
ab
cd
ef

readline(	 ab cd	ef 'gh ij	kl' "mn op	qr" 	# blah): 0
ab
cd
ef
gh ij	kl
mn op	qr

readline(	 ab cd	ef 'gh "ij\'	kl' "mn 'op\"	qr" 	# blah): 0
ab
cd
ef
gh "ij'	kl
mn 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr" 	# blah): 0
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl): 1
a\b
cd
ef
g\h "ij'	kl

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr): 1
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(path "C:\Backup\"): 1
path
C:\Backup"

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path
C:\Backup



and

spaces
matter


readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path

readline(		f	blah	''): 0


f
blah


readline(		f	blah	'): 1


f
blah


readline(		f	blah		): 0


f
blah




File types
Name: testfile, path = test1/testfile, type = f, mtime = 1, size = 13, uid = 1, gid = 1, mode = 750
Name: testlink, path = test1/testlink, type = l, mtime = 1, size = 8, uid = 1, gid = 1, mode = 777, link = testfile
 > Dir.: testdir, path = test1/testdir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 > Dir.: subdir, path = test1/subdir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 -> File: testfile, path = test1/subdir/testfile, type = f, mtime = 1, size = 12, uid = 1, gid = 1, mode = 644
 -> File: testfile1, path = test1/subdir/testfile1, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> File: testfile2, path = test1/subdir/testfile2, type = f, mtime = 1, size = 12, uid = 1, gid = 1, mode = 644

Validity tests
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 1

Creation tests
File is file? 0
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 0
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0
Create
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0
Create again
failed to create file: File exists
failed to create dir: File exists
File is file? 1
File is dir? 0
File is link? 0
Dir is file? 0
Dir is dir? 1
Dir is link? 0
Link is file? 0
Link is dir? 0
Link is link? 0

Parsing test
 > Dir.: test1, path = test1, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 -> File: big_file, path = test1/big_file, type = f, mtime = 1, size = 10485760, uid = 1, gid = 1, mode = 644
 -> Dir.: dir space, path = test1/dir space, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 --> File: file space, path = test1/dir space/file space, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> File: rwfile_source, path = test1/rwfile_source, type = f, mtime = 1, size = 10222, uid = 1, gid = 1, mode = 644
 -> Dir.: subdir, path = test1/subdir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 --> File: testfile, path = test1/subdir/testfile, type = f, mtime = 1, size = 12, uid = 1, gid = 1, mode = 644
 --> File: testfile1, path = test1/subdir/testfile1, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 --> File: testfile2, path = test1/subdir/testfile2, type = f, mtime = 1, size = 12, uid = 1, gid = 1, mode = 644
 -> File: test space, path = test1/test space, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> Dir.: testdir, path = test1/testdir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 -> File: testfile, path = test1/testfile, type = f, mtime = 1, size = 13, uid = 1, gid = 1, mode = 750
 -> File: testfile~, path = test1/testfile~, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644
 -> Link: testlink, path = test1/testlink, type = l, mtime = 1, size = 8, uid = 1, gid = 1, mode = 777, link = testfile
 -> Oth.: testpipe, path = test1/testpipe, type = p, mtime = 1, size = 0, uid = 1, gid = 1, mode = 600
 -> Dir.: toucheddir, path = test1/toucheddir, type = d, mtime = 1, size = 1, uid = 1, gid = 1, mode = 755
 -> File: touchedfile, path = test1/touchedfile, type = f, mtime = 1, size = 0, uid = 1, gid = 1, mode = 644

Difference test
f1 and f2 are identical
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
f1 and f2 differ
l1 and l2 are identical
l1 and l2 differ
l1 and l2 differ

getParams
db	test_db	

compress_auto	

filter	all	backup	
condition	type	file	
condition	path_end	~	

filter	any	test_or	
condition	filter	backup	
condition	!size<	1000	

client	myClient	xp	
protocol	smb	
config	C:\Backup\Backup.LST	

client	myClient	
protocol	nfs	
hostname	myClient	
config	/home/User/hbackup.list	

client	other	
protocol	ssh	
hostname	otherClient	
config	/home/backup/Backup.list	

filter	and	subdir	
condition	path_start	subdir	
condition	!size<	100	

filter	and	bigfile	
condition	size>=	10	
condition	type	file	

expire	1	

path	test2//	

path	test1	

filter	and	not_object	
condition	!path_end	.o	

filter	or	to_be_ignored	
condition	filter	subdir	
condition	filter	backup	
condition	!filter	not_object	

ignore	to_be_ignored	

compress	bigfile	

parser	cvs	controlled	
parser	svn	modified	

client	myhost	
report_copy_error_once	
protocol	file	
hostname	myhost.mynetwork.lan	
timeout_nowarning	
config	etc/localhost.list	
expire	1	

client	client	xp	
protocol	smb	
option	username	Myself	
option	password	flesyM	
option	nocase	
hostname	myClient	
config	C:\Backup\Backup.LST	

client	aClient	vista	
protocol	smb	
filter	and	huge_file	
condition	!filter	backup	
condition	!size<	100	

path	C:\Test Dir	
filter	and	compress_m	
condition	!filter	huge_file	
compress	compress_m	
ignore	backup	
parser	svn	modified	
report_copy_error_once	

Stream select
Not found.
Found (1): data.gz
Found (0): data

End of tests
