
Simple rules test
>List 1 rule(s):
-> List 1 condition(s)
--> ^/to a.*\.txt 24
>List 2 rule(s):
-> List 1 condition(s)
--> ^/to a.*\.txt 24
-> List 1 condition(s)
--> ^/to a.*\.t.t 24
Not matching 3
Not matching +1
Not matching +2
Not matching +3
>List 1 rule(s):
-> List 1 condition(s)
--> ^/to a.*\.txt 24
>List 2 rule(s):
-> List 1 condition(s)
--> ^/to a.*\.txt 24
-> List 1 condition(s)
--> ^/to a.*\.t.t 24
Not matching +3
Not matching 3
Not matching 0
Not matching 1000
Not matching 1000000
>List 1 rule(s):
-> List 1 condition(s)
--> 500 33
Matching 0
Not matching 1000
Not matching 1000000
>List 2 rule(s):
-> List 1 condition(s)
--> 500 33
-> List 1 condition(s)
--> 5000 31
Matching 0
Not matching 1000
Matching 1000000

Complex rules test
>List 0 rule(s):
>List 1 rule(s):
-> List 1 condition(s)
--> 500 33
>List 1 rule(s):
-> List 2 condition(s)
--> 500 33
--> 400 31
Not matching 600
Matching 500
Matching 450
Matching 400
Not matching 300
OR filter test
my_filter_or
Not matching 4

AND filter test
my_filter_and
Not matching 2
Not matching 3
Not matching 4

Sub-filter test
my_subfilter
my_filter_and
Not matching 1
Not matching 1
Not matching 2
Not matching 3
Not matching 4
