
Test: wrong config file
Error: : No such file or directory: Opening file

Test: backup, not initialized
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Error: Given DB path does not exist: test_db

Test: check config
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
 -> Reading client configuration file
Configuration:
 -> Client: localhost
 --> Protocol: file
 --> Config: test_user/.hbackup/config
 --> Expiry: none
 --> Paths: 
 ---> Path: test_user/testuser

Test: typical backup
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database initialized: test_db
Database open in read/write mode
Trying client 'aClient.vista' using protocol 'smb'
Backing up client
Reading list of missing checksums
List created: aClient.vista
Database open r/w: aClient.vista
Backup path: C:/Test Dir
 -> mount -t cifs -o ro,noatime,nocase //aClient/C$ test_db/.mount
A       C:/Test Dir/My Dir
 -> Dir: My Dir
Adding compressed file data to DB for b026324c6904b2a9cb4b88d6d61c81d1-0
A z     C:/Test Dir/My Dir/a File.TXT
Adding compressed file data to DB for 26ab0db90d72e28ad0ba1e22ee510510-0
A z     C:/Test Dir/My Dir/another File.TXT
Adding compressed file data to DB for d41d8cd98f00b204e9800998ecf8427e-0
A z     C:/Test Dir/My File.TXT
Database modified: aClient.vista
Database closed: aClient.vista
 -> umount -fl test_db/.mount
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
List created: client.xp
Database open r/w: client.xp
Backup path: C:/Test Dir
A       C:/Test Dir/My Dir
 -> Dir: My Dir
A       C:/Test Dir/My Dir/a File.TXT
A       C:/Test Dir/My Dir/another File.TXT
A       C:/Test Dir/My File.TXT
Database modified: client.xp
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ----> Filter: or compress
 -----> Condition: name File2.txt
 -----> Condition: path dir/file3.txt
 ----> Compress filter: compress
Backing up client
List created: myClient
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
A       /home/User/test/File2.txt
A       /home/User/test/dir
 -> Dir: dir
Adding compressed file data to DB for 6d7fce9fee471194aa8b5b6e47267f03-0
A z     /home/User/test/dir/file3.txt
Database modified: myClient
Database closed: myClient
 -> umount -fl test_db/.mount
Trying client 'myClient.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Subset: xp
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
List created: myClient.xp
Database open r/w: myClient.xp
Backup path: C:/Test Dir
A       C:/Test Dir/My Dir
 -> Dir: My Dir
A       C:/Test Dir/My Dir/a File.TXT
A       C:/Test Dir/My Dir/another File.TXT
A       C:/Test Dir/My File.TXT
Database modified: myClient.xp
Database closed: myClient.xp
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
List created: myhost
Database open r/w: myhost
Backup path: test1
Done:   3.9%\r
Done:   7.8%\r
Done:  11.7%\r
Done:  15.6%\r
Done:  19.5%\r
Done:  23.4%\r
Done:  27.3%\r
Done:  31.2%\r
Done:  35.2%\r
Done:  39.1%\r
Done:  43.0%\r
Done:  46.9%\r
Done:  50.8%\r
Done:  54.7%\r
Done:  58.6%\r
Done:  62.5%\r
Done:  66.4%\r
Done:  70.3%\r
Done:  74.2%\r
Done:  78.1%\r
Done:  82.0%\r
Done:  85.9%\r
Done:  89.8%\r
Done:  93.8%\r
Done:  97.7%\r
            \r
Adding compressed file data to DB for f1c9645dbc14efddc7d8a322685f26eb-0
A z     test1/big_file
A       test1/cvs
 -> Dir: cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
A       test1/cvs/CVS
 -> Dir: cvs/CVS
Adding compressed file data to DB for fef51838cd3cfe8ed96355742eb71fbd-0
A z     test1/cvs/CVS/Entries
Adding compressed file data to DB for b90f8fa56ea1d39881d4a199c7a81d35-0
A z     test1/cvs/CVS/Root
A       test1/cvs/dirbad
 -> Dir: cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
A       test1/cvs/dirutd
 -> Dir: cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
A       test1/cvs/dirutd/CVS
 -> Dir: cvs/dirutd/CVS
Adding compressed file data to DB for 5252f242d27b8c2c9fdbdcbb33545d07-0
A z     test1/cvs/dirutd/CVS/Entries
Adding compressed file data to DB for eb75fb33b2019ef3c840eb5ccdc2e795-0
A z     test1/cvs/dirutd/CVS/Root
A       test1/cvs/dirutd/fileutd
A       test1/cvs/filenew.c
A       test1/cvs/fileutd.h
A       test1/dir space
 -> Dir: dir space
A       test1/dir space/file space
A       test1/svn
 -> Dir: svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
A       test1/svn/.svn
 -> Dir: svn/.svn
Adding compressed file data to DB for 0f2ea973d77135dc3d06c8e68da6dc59-0
A z     test1/svn/.svn/entries
A       test1/svn/dirbad
 -> Dir: svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
A       test1/svn/dirutd
 -> Dir: svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
A       test1/svn/dirutd/.svn
 -> Dir: svn/dirutd/.svn
Adding compressed file data to DB for 8bdef5751e46ed57d237cbe3f4a5061c-0
A z     test1/svn/dirutd/.svn/entries
A       test1/svn/dirutd/fileutd
A       test1/svn/filenew.c
A       test1/test space
A       test1/testdir
 -> Dir: testdir
Adding compressed file data to DB for 59ca0efa9f5633cb0371bbc0355478d8-0
A z     test1/testfile
A       test1/testlink
A       test1/testpipe
Backup path: test2
A       test2/testdir
 -> Dir: testdir
Adding file data to DB for 3d546a1ce46c6ae10ad34ab8a81c542e-0
A f     test2/testfile
Adding file data to DB for fb00cd74a5f35e89a7fbdd3c1d05375a-0
A f     test2/testfile2
Done:  78.1%\r
            \r
Adding file data to DB for 59071590099d21dd439896592338bf95-0
A f     test2/testfile~
A       test2/testlink
Database modified: myhost
Database closed: myhost
Trying client 'other' using protocol 'ssh'
Error: other: Protocol not supported: ssh
Database closed

Test: same backup
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Trying client 'aClient.vista' using protocol 'smb'
Backing up client
Reading list of missing checksums
Database open r/w: aClient.vista
Backup path: C:/Test Dir
 -> mount -t cifs -o ro,noatime,nocase //aClient/C$ test_db/.mount
 -> Dir: My Dir
Database closed: aClient.vista
 -> umount -fl test_db/.mount
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: client.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ----> Filter: or compress
 -----> Condition: name File2.txt
 -----> Condition: path dir/file3.txt
 ----> Compress filter: compress
Backing up client
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
 -> Dir: dir
Database closed: myClient
 -> umount -fl test_db/.mount
Trying client 'myClient.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Subset: xp
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: myClient.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: myClient.xp
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Database open r/w: myhost
Backup path: test1
 -> Dir: cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir: cvs/CVS
 -> Dir: cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir: cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir: cvs/dirutd/CVS
 -> Dir: dir space
 -> Dir: svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
 -> Dir: svn/.svn
 -> Dir: svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
 -> Dir: svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
 -> Dir: svn/dirutd/.svn
 -> Dir: testdir
Backup path: test2
 -> Dir: testdir
Database closed: myhost
Trying client 'other' using protocol 'ssh'
Error: other: Protocol not supported: ssh
Database closed

Test: interrupted backup
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Trying client 'aClient.vista' using protocol 'smb'
Backing up client
Reading list of missing checksums
Database open r/w: aClient.vista
Backup path: C:/Test Dir
 -> mount -t cifs -o ro,noatime,nocase //aClient/C$ test_db/.mount
 -> Dir: My Dir
Database closed: aClient.vista
 -> umount -fl test_db/.mount
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: client.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ----> Filter: or compress
 -----> Condition: name File2.txt
 -----> Condition: path dir/file3.txt
 ----> Compress filter: compress
Backing up client
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
 -> Dir: dir
Database closed: myClient
 -> umount -fl test_db/.mount
Trying client 'myClient.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Subset: xp
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: myClient.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: myClient.xp
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Database open r/w: myhost
Backup path: test1
 -> Dir: cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir: cvs/CVS
 -> Dir: cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir: cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir: cvs/dirutd/CVS
 -> Dir: dir space
Done:  80.0%\r
Killing trigger reached: 2
Error: test_db/myhost/data: Operation canceled: Copying write file
A !     test1/dir space/big_file
Database closed: myhost
Database closed

Test: specify clients
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Warning: Previous backup interrupted: myhost
Database modified: myhost
Database open in read/write mode
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Reading list of missing checksums
Database open r/w: client.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Database open r/w: myhost
Backup path: test1
 -> Dir: cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir: cvs/CVS
 -> Dir: cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir: cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir: cvs/dirutd/CVS
 -> Dir: dir space
Done:  80.0%\r
            \r
Adding compressed file data to DB for 816df6f64deba63b029ca19d880ee10a-0
! z     test1/dir space/big_file
 -> Dir: svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
 -> Dir: svn/.svn
 -> Dir: svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
 -> Dir: svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
 -> Dir: svn/dirutd/.svn
 -> Dir: testdir
Backup path: test2
 -> Dir: testdir
Database modified: myhost
Database closed: myhost
Database closed

Test: scan DB
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
0f2ea973d77135dc3d06c8e68da6dc59-0\r
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
59ca0efa9f5633cb0371bbc0355478d8-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
b90f8fa56ea1d39881d4a199c7a81d35-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
fef51838cd3cfe8ed96355742eb71fbd-0\r
                                  \r
Found 16 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Database closed

Test: check DB
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Crawling through DB data
0f2ea973d77135dc3d06c8e68da6dc59-0\r
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
59ca0efa9f5633cb0371bbc0355478d8-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
b90f8fa56ea1d39881d4a199c7a81d35-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
fef51838cd3cfe8ed96355742eb71fbd-0\r
                                  \r
Found 16 valid and 0 broken data files
Database closed

Test: list clients
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database closed
List of clients: 5
 -> aClient.vista
 -> client.xp
 -> myClient
 -> myClient.xp
 -> myhost

Test: list paths in UNIX client
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient
Database closed: myClient
Database closed
List of paths in 'myClient': 1
 -> /home

Test: list paths in DOS client
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: client.xp
Database closed: client.xp
Database closed
List of paths in 'client.xp': 1
 -> C:

Test: restore file
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myhost
U test_r/test2/testfile
Database closed: myhost
Database closed

Test: restore dir
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myhost
U test_r/test1/big_file
U test_r/test1/cvs
U test_r/test1/cvs/CVS
U test_r/test1/cvs/CVS/Entries
U test_r/test1/cvs/CVS/Root
U test_r/test1/cvs/dirbad
U test_r/test1/cvs/dirutd
U test_r/test1/cvs/dirutd/CVS
U test_r/test1/cvs/dirutd/CVS/Entries
U test_r/test1/cvs/dirutd/CVS/Root
U test_r/test1/cvs/dirutd/fileutd
U test_r/test1/cvs/filenew.c
U test_r/test1/cvs/fileutd.h
U test_r/test1/dir space
U test_r/test1/dir space/big_file
U test_r/test1/dir space/file space
U test_r/test1/svn
U test_r/test1/svn/.svn
U test_r/test1/svn/.svn/entries
U test_r/test1/svn/dirbad
U test_r/test1/svn/dirutd
U test_r/test1/svn/dirutd/.svn
U test_r/test1/svn/dirutd/.svn/entries
U test_r/test1/svn/dirutd/fileutd
U test_r/test1/svn/filenew.c
U test_r/test1/test space
U test_r/test1/testdir
U test_r/test1/testfile
U test_r/test1/testlink
U test_r/test1/testpipe
Database closed: myhost
Database closed
test1/testfile metadata: gid = 24, mtime = 1161475200, perms = 0750

Test: restore subdir
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myhost
U test_r/test1/cvs
U test_r/test1/cvs/CVS
U test_r/test1/cvs/CVS/Entries
U test_r/test1/cvs/CVS/Root
U test_r/test1/cvs/dirbad
U test_r/test1/cvs/dirutd
U test_r/test1/cvs/dirutd/CVS
U test_r/test1/cvs/dirutd/CVS/Entries
U test_r/test1/cvs/dirutd/CVS/Root
U test_r/test1/cvs/dirutd/fileutd
U test_r/test1/cvs/filenew.c
U test_r/test1/cvs/fileutd.h
Database closed: myhost
Database closed

Test: restore client
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myhost
U test_r/test1/big_file
U test_r/test1/cvs
U test_r/test1/cvs/CVS
U test_r/test1/cvs/CVS/Entries
U test_r/test1/cvs/CVS/Root
U test_r/test1/cvs/dirbad
U test_r/test1/cvs/dirutd
U test_r/test1/cvs/dirutd/CVS
U test_r/test1/cvs/dirutd/CVS/Entries
U test_r/test1/cvs/dirutd/CVS/Root
U test_r/test1/cvs/dirutd/fileutd
U test_r/test1/cvs/filenew.c
U test_r/test1/cvs/fileutd.h
U test_r/test1/dir space
U test_r/test1/dir space/big_file
U test_r/test1/dir space/file space
U test_r/test1/svn
U test_r/test1/svn/.svn
U test_r/test1/svn/.svn/entries
U test_r/test1/svn/dirbad
U test_r/test1/svn/dirutd
U test_r/test1/svn/dirutd/.svn
U test_r/test1/svn/dirutd/.svn/entries
U test_r/test1/svn/dirutd/fileutd
U test_r/test1/svn/filenew.c
U test_r/test1/test space
U test_r/test1/testdir
U test_r/test1/testfile
U test_r/test1/testlink
U test_r/test1/testpipe
U test_r/test2/testdir
U test_r/test2/testfile
U test_r/test2/testfile2
U test_r/test2/testfile~
Done:  78.1%\r
            \r
U test_r/test2/testlink
Database closed: myhost
Database closed

Test: typical backup
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Trying client 'aClient.vista' using protocol 'smb'
Backing up client
Reading list of missing checksums
Database open r/w: aClient.vista
Backup path: C:/Test Dir
 -> mount -t cifs -o ro,noatime,nocase //aClient/C$ test_db/.mount
 -> Dir: My Dir
Database closed: aClient.vista
 -> umount -fl test_db/.mount
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: client.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ----> Filter: or compress
 -----> Condition: name File2.txt
 -----> Condition: path dir/file3.txt
 ----> Compress filter: compress
Backing up client
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
 -> Dir: dir
Database closed: myClient
 -> umount -fl test_db/.mount
Trying client 'myClient.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Subset: xp
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: myClient.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: myClient.xp
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Database open r/w: myhost
Backup path: test1
 -> Dir: cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir: cvs/CVS
 -> Dir: cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir: cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir: cvs/dirutd/CVS
 -> Dir: dir space
 -> Dir: svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
 -> Dir: svn/.svn
 -> Dir: svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
 -> Dir: svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
 -> Dir: svn/dirutd/.svn
 -> Dir: testdir
Backup path: test2
 -> Dir: testdir
Database closed: myhost
Trying client 'other' using protocol 'ssh'
Error: other: Protocol not supported: ssh
Database closed

Test: specify clients
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Reading list of missing checksums
Database open r/w: client.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ----> Filter: or compress
 -----> Condition: name File2.txt
 -----> Condition: path dir/file3.txt
 ----> Compress filter: compress
Backing up client
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
 -> Dir: dir
Database closed: myClient
 -> umount -fl test_db/.mount
Database closed

Test: user-mode backup
Database initialized: test_user/.hbackup
Database open in read/write mode
 -> Reading client configuration file
Configuration:
 -> Client: localhost
 --> Protocol: file
 --> Config: test_user/.hbackup/config
 --> Expiry: none
 --> Paths: 
 ---> Path: test_user/testuser
Backing up client
Reading list of missing checksums
List created: localhost
Database open r/w: localhost
Backup path: test_user/testuser
Adding file data to DB for 31d30eea8d0968d6458e0ad0027c9f80-0
A f     test_user/testuser/f1.txt
A       test_user/testuser/subdir
 -> Dir: subdir
Adding file data to DB for dbbf8220893d497d403bb9cdf49db7a4-0
A f     test_user/testuser/subdir/f2.txt
A       test_user/testuser/subdir2
 -> Dir: subdir2
Adding file data to DB for d5b4c7d9b06b60a7846c4529834c9812-0
A f     test_user/testuser/subdir2/f3.txt
Adding file data to DB for 90e2a51705594d033a3abe9d77b2b7ad-0
A f     test_user/testuser/subdir2/f4.txt
Database modified: localhost
Database closed: localhost
Database closed

Test: list clients
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database closed
List of clients: 5
 -> aClient.vista
 -> client.xp
 -> myClient
 -> myClient.xp
 -> myhost

Test: list paths in DOS client
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient.xp
Database closed: myClient.xp
Database closed
List of paths in 'myClient.xp': 1
 -> C:

Test: list paths in dual-boot client
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database closed
Selected client: myClient
Selected client: myClient.xp
Database open in read-only mode
Database open r-o: myClient
Database closed: myClient
Database open r-o: myClient.xp
Database closed: myClient.xp
Database closed
List of paths in 'myClient*': 2
 -> /home
 -> C:

Test: list sub-paths in UNIX client
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient
Database closed: myClient
Database closed
List of paths in 'myClient': 1
 -> /home/User

Test: list sub-paths in DOS client
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient.xp
Database closed: myClient.xp
Database closed
List of paths in 'myClient.xp', 'C:': 1
 -> C:/Test Dir

Test: restore file (UNIX)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient
U test_r//home/User/test/File2.txt
Database closed: myClient
Database closed

Test: restore subdir (UNIX)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient
U test_r//home/User/test/File2.txt
U test_r//home/User/test/dir
U test_r//home/User/test/dir/file3.txt
Database closed: myClient
Database closed

Test: restore dir (UNIX)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient
U test_r//home/User/test/File2.txt
U test_r//home/User/test/dir
U test_r//home/User/test/dir/file3.txt
Database closed: myClient
Database closed

Test: restore client (UNIX)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient
U test_r//home/User/test/File2.txt
U test_r//home/User/test/dir
U test_r//home/User/test/dir/file3.txt
Database closed: myClient
Database closed

Test: restore file (DOS)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient.xp
U test_r/C:/Test Dir/My File.TXT
Database closed: myClient.xp
Database closed

Test: restore subdir (DOS)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient.xp
U test_r/C:/Test Dir/My Dir
U test_r/C:/Test Dir/My Dir/a File.TXT
U test_r/C:/Test Dir/My Dir/another File.TXT
Database closed: myClient.xp
Database closed

Test: restore dir (DOS)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient.xp
U test_r/C:/Test Dir/My Dir
U test_r/C:/Test Dir/My Dir/a File.TXT
U test_r/C:/Test Dir/My Dir/another File.TXT
U test_r/C:/Test Dir/My File.TXT
Database closed: myClient.xp
Database closed

Test: restore client (DOS)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database open r-o: myClient.xp
U test_r/C:/Test Dir/My Dir
U test_r/C:/Test Dir/My Dir/a File.TXT
U test_r/C:/Test Dir/My Dir/another File.TXT
U test_r/C:/Test Dir/My File.TXT
Database closed: myClient.xp
Database closed

Test: restore client (dual-boot)
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read-only mode
Database closed
Selected client: myClient
Selected client: myClient.xp
Database open in read-only mode
Database open r-o: myClient
U test_r//home/User/test/File2.txt
U test_r//home/User/test/dir
U test_r//home/User/test/dir/file3.txt
Database closed: myClient
Database open r-o: myClient.xp
U test_r/C:/Test Dir/My Dir
U test_r/C:/Test Dir/My Dir/a File.TXT
U test_r/C:/Test Dir/My Dir/another File.TXT
U test_r/C:/Test Dir/My File.TXT
Database closed: myClient.xp
Database closed

Test: check for corrupted data
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Check
Database open in read-only mode
Crawling through DB data
0f2ea973d77135dc3d06c8e68da6dc59-0\r
                                  \r
Error: 0f2ea973d77135dc3d06c8e68da6dc59-0: Data corrupted
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
59ca0efa9f5633cb0371bbc0355478d8-0\r
                                  \r
Error: 59ca0efa9f5633cb0371bbc0355478d8-0: Data missing
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
b90f8fa56ea1d39881d4a199c7a81d35-0\r
                                  \r
Error: b90f8fa56ea1d39881d4a199c7a81d35-0: Data corrupted
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
fef51838cd3cfe8ed96355742eb71fbd-0\r
                                  \r
Error: fef51838cd3cfe8ed96355742eb71fbd-0: Data corrupted
Found 12 valid and 4 broken data files
Database closed

Test: scan for missing data
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Just scan
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
0f2ea973d77135dc3d06c8e68da6dc59-0\r
                                  \r
Error: 0f2ea973d77135dc3d06c8e68da6dc59-0: Data missing
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
59ca0efa9f5633cb0371bbc0355478d8-0\r
                                  \r
Error: 59ca0efa9f5633cb0371bbc0355478d8-0: Data missing
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
b90f8fa56ea1d39881d4a199c7a81d35-0\r
                                  \r
b90f8fa56ea1d39881d4a199c7a81d35-0: Remove corrupted data
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
fef51838cd3cfe8ed96355742eb71fbd-0\r
                                  \r
fef51838cd3cfe8ed96355742eb71fbd-0: Remove corrupted data
Found 12 valid and 4 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
Warning: Missing checksum(s): 4
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Missing checksums list modified
List of missing checksums contains 4 item(s)
Database closed
Just scan again
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
                                  \r
Found 12 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
Warning: Missing checksum(s): 4
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Missing checksums list modified
List of missing checksums contains 4 item(s)
Database closed

Test: scan for obsolete data, case1
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Just scan
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
00000000000000000000000000000000-0\r
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
88888888888888888888888888888888-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
ffffffffffffffffffffffffffffffff-0\r
                                  \r
Found 15 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 00000000000000000000000000000000-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 88888888888888888888888888888888-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> ffffffffffffffffffffffffffffffff-0
Obsolete checksum(s): 3
 -> 00000000000000000000000000000000-0
 -> 88888888888888888888888888888888-0
 -> ffffffffffffffffffffffffffffffff-0
Warning: Missing checksum(s): 4
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Missing checksums list modified
List of missing checksums contains 4 item(s)
Database closed
Scan and remove
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
00000000000000000000000000000000-0\r
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
88888888888888888888888888888888-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
ffffffffffffffffffffffffffffffff-0\r
                                  \r
Found 15 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 00000000000000000000000000000000-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 88888888888888888888888888888888-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> ffffffffffffffffffffffffffffffff-0
Obsolete checksum(s): 3
 -> 00000000000000000000000000000000-0: removed
 -> 88888888888888888888888888888888-0: removed
 -> ffffffffffffffffffffffffffffffff-0: removed
Warning: Missing checksum(s): 4
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Missing checksums list modified
List of missing checksums contains 4 item(s)
Database closed
Just scan again
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
                                  \r
Found 12 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
Warning: Missing checksum(s): 4
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Missing checksums list modified
List of missing checksums contains 4 item(s)
Database closed

Test: scan for obsolete data, case 2
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Just scan
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
26ab0db90d72e28ad0ba1e22ee510510-0\r
33333333333333333333333333333333-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
77777777777777777777777777777777-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
dddddddddddddddddddddddddddddddd-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
                                  \r
Found 15 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 33333333333333333333333333333333-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 77777777777777777777777777777777-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> dddddddddddddddddddddddddddddddd-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
Obsolete checksum(s): 3
 -> 33333333333333333333333333333333-0
 -> 77777777777777777777777777777777-0
 -> dddddddddddddddddddddddddddddddd-0
Warning: Missing checksum(s): 4
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Missing checksums list modified
List of missing checksums contains 4 item(s)
Database closed
Scan and remove
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
26ab0db90d72e28ad0ba1e22ee510510-0\r
33333333333333333333333333333333-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
77777777777777777777777777777777-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
dddddddddddddddddddddddddddddddd-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
                                  \r
Found 15 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 33333333333333333333333333333333-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 77777777777777777777777777777777-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> dddddddddddddddddddddddddddddddd-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
Obsolete checksum(s): 3
 -> 33333333333333333333333333333333-0: removed
 -> 77777777777777777777777777777777-0: removed
 -> dddddddddddddddddddddddddddddddd-0: removed
Warning: Missing checksum(s): 4
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Missing checksums list modified
List of missing checksums contains 4 item(s)
Database closed
Just scan again
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
                                  \r
Found 12 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
Warning: Missing checksum(s): 4
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Missing checksums list modified
List of missing checksums contains 4 item(s)
Database closed

Test: backup recovers missing checksums
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Trying client 'aClient.vista' using protocol 'smb'
Backing up client
Reading list of missing checksums
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Database open r/w: aClient.vista
Backup path: C:/Test Dir
 -> mount -t cifs -o ro,noatime,nocase //aClient/C$ test_db/.mount
 -> Dir: My Dir
Database closed: aClient.vista
 -> umount -fl test_db/.mount
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: client.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ----> Filter: or compress
 -----> Condition: name File2.txt
 -----> Condition: path dir/file3.txt
 ----> Compress filter: compress
Backing up client
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
 -> Dir: dir
Database closed: myClient
 -> umount -fl test_db/.mount
Trying client 'myClient.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Subset: xp
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: myClient.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: myClient.xp
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Database open r/w: myhost
Backup path: test1
 -> Dir: cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir: cvs/CVS
Adding compressed file data to DB for fef51838cd3cfe8ed96355742eb71fbd-0
R z     test1/cvs/CVS/Entries
Adding compressed file data to DB for b90f8fa56ea1d39881d4a199c7a81d35-0
R z     test1/cvs/CVS/Root
 -> Dir: cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir: cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir: cvs/dirutd/CVS
 -> Dir: dir space
 -> Dir: svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
 -> Dir: svn/.svn
Adding compressed file data to DB for 0f2ea973d77135dc3d06c8e68da6dc59-0
R z     test1/svn/.svn/entries
 -> Dir: svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
 -> Dir: svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
 -> Dir: svn/dirutd/.svn
 -> Dir: testdir
D       test1/testfile
Backup path: test2
 -> Dir: testdir
Database modified: myhost
Database closed: myhost
Trying client 'other' using protocol 'ssh'
Error: other: Protocol not supported: ssh
Missing checksums list modified
List of missing checksums contains 1 item(s)
Database closed
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Trying client 'aClient.vista' using protocol 'smb'
Backing up client
Reading list of missing checksums
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
Database open r/w: aClient.vista
Backup path: C:/Test Dir
 -> mount -t cifs -o ro,noatime,nocase //aClient/C$ test_db/.mount
 -> Dir: My Dir
Database closed: aClient.vista
 -> umount -fl test_db/.mount
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: client.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ----> Filter: or compress
 -----> Condition: name File2.txt
 -----> Condition: path dir/file3.txt
 ----> Compress filter: compress
Backing up client
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
 -> Dir: dir
Database closed: myClient
 -> umount -fl test_db/.mount
Trying client 'myClient.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Subset: xp
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: myClient.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: myClient.xp
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Database open r/w: myhost
Backup path: test1
 -> Dir: cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir: cvs/CVS
 -> Dir: cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir: cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir: cvs/dirutd/CVS
 -> Dir: dir space
 -> Dir: svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
 -> Dir: svn/.svn
 -> Dir: svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
 -> Dir: svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
 -> Dir: svn/dirutd/.svn
 -> Dir: testdir
Backup path: test2
 -> Dir: testdir
Database closed: myhost
Trying client 'other' using protocol 'ssh'
Error: other: Protocol not supported: ssh
List of missing checksums contains 1 item(s)
Database closed
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Reading list: aClient.vista
Reading list: client.xp
Reading list: myClient
Reading list: myClient.xp
Reading list: myhost
Found 16 checksums
Crawling through DB
0f2ea973d77135dc3d06c8e68da6dc59-0\r
26ab0db90d72e28ad0ba1e22ee510510-0\r
3d546a1ce46c6ae10ad34ab8a81c542e-0\r
5252f242d27b8c2c9fdbdcbb33545d07-0\r
59071590099d21dd439896592338bf95-0\r
6d7fce9fee471194aa8b5b6e47267f03-0\r
816df6f64deba63b029ca19d880ee10a-0\r
8bdef5751e46ed57d237cbe3f4a5061c-0\r
b026324c6904b2a9cb4b88d6d61c81d1-0\r
b90f8fa56ea1d39881d4a199c7a81d35-0\r
d41d8cd98f00b204e9800998ecf8427e-0\r
eb75fb33b2019ef3c840eb5ccdc2e795-0\r
f1c9645dbc14efddc7d8a322685f26eb-0\r
fb00cd74a5f35e89a7fbdd3c1d05375a-0\r
fef51838cd3cfe8ed96355742eb71fbd-0\r
                                  \r
Found 15 valid and 0 broken data files
Checksum(s) from list:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Checksum(s) with data:
 -> 0f2ea973d77135dc3d06c8e68da6dc59-0
 -> 26ab0db90d72e28ad0ba1e22ee510510-0
 -> 3d546a1ce46c6ae10ad34ab8a81c542e-0
 -> 5252f242d27b8c2c9fdbdcbb33545d07-0
 -> 59071590099d21dd439896592338bf95-0
 -> 6d7fce9fee471194aa8b5b6e47267f03-0
 -> 816df6f64deba63b029ca19d880ee10a-0
 -> 8bdef5751e46ed57d237cbe3f4a5061c-0
 -> b026324c6904b2a9cb4b88d6d61c81d1-0
 -> b90f8fa56ea1d39881d4a199c7a81d35-0
 -> d41d8cd98f00b204e9800998ecf8427e-0
 -> eb75fb33b2019ef3c840eb5ccdc2e795-0
 -> f1c9645dbc14efddc7d8a322685f26eb-0
 -> fb00cd74a5f35e89a7fbdd3c1d05375a-0
 -> fef51838cd3cfe8ed96355742eb71fbd-0
Warning: Missing checksum(s): 1
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
Missing checksums list modified
List of missing checksums contains 1 item(s)
Database closed
 -> Reading configuration file: etc/hbackup.conf
Configuration:
 -> DB path: test_db
 -> Clients:
 --> Client: aClient
 ---> Protocol: smb
 ---> Expiry: none
 ---> Filter: and huge_file
 ----> Condition: not filter backup
 ----> Condition: not size< 100
 ---> Paths: 
 ----> Path: C:/Test Dir
 -----> Filter: and compress_m
 ------> Condition: not filter huge_file
 -----> Parser: Subversion
 -----> Compress filter: compress_m
 -----> Ignore filter: backup
 ---> Required subset: vista
 --> Client: client
 ---> Protocol: smb
 ---> Hostname: myClient
 ---> Options: username=Myself password=flesyM nocase 
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myClient
 ---> Protocol: nfs
 ---> Config: /home/User/hbackup.list
 ---> Expiry: none
 --> Client: myClient
 ---> Protocol: smb
 ---> Config: C:/Backup/Backup.LST
 ---> Expiry: none
 ---> Required subset: xp
 --> Client: myhost
 ---> Protocol: file
 ---> Hostname: myhost.mynetwork.lan
 ---> Config: etc/localhost.list
 ---> Expiry: 86400s (1d)
 --> Client: other
 ---> Protocol: ssh
 ---> Hostname: otherClient
 ---> Config: /home/backup/Backup.list
 ---> Expiry: 86400s (1d)
 ---> Filter: and subdir
 ----> Condition: path_start subdir
 ----> Condition: not size< 100
 ---> Filter: and bigfile
 ----> Condition: size>= 10
 ----> Condition: type f
 ---> Paths: 
 ----> Path: test1
 -----> Filter: and not_object
 ------> Condition: not path_end .o
 -----> Filter: or to_be_ignored
 ------> Condition: filter subdir
 ------> Condition: filter backup
 ------> Condition: not filter not_object
 -----> Parser: CVS
 -----> Parser: Subversion
 -----> Compress filter: bigfile
 -----> Ignore filter: to_be_ignored
 ----> Path: test2
 -> Filter: and backup
 --> Condition: type f
 --> Condition: path_end ~
 -> Filter: or test_or
 --> Condition: filter backup
 --> Condition: not size< 1000
Database open in read/write mode
Trying client 'aClient.vista' using protocol 'smb'
Backing up client
Reading list of missing checksums
 -> 59ca0efa9f5633cb0371bbc0355478d8-0
Database open r/w: aClient.vista
Backup path: C:/Test Dir
 -> mount -t cifs -o ro,noatime,nocase //aClient/C$ test_db/.mount
 -> Dir: My Dir
Database closed: aClient.vista
 -> umount -fl test_db/.mount
Trying client 'client.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase,username=Myself,password=flesyM,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: client
 --> Subset: xp
 --> Protocol: smb
 --> Hostname: myClient
 --> Options: username=Myself password=flesyM nocase 
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: client.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: client.xp
 -> umount -fl test_db/.mount
Trying client 'myClient' using protocol 'nfs'
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Protocol: nfs
 --> Config: /home/User/hbackup.list
 --> Expiry: none
 --> Paths: 
 ---> Path: /home/User/test
 ----> Filter: or compress
 -----> Condition: name File2.txt
 -----> Condition: path dir/file3.txt
 ----> Compress filter: compress
Backing up client
Database open r/w: myClient
Backup path: /home/User/test
 -> umount -fl test_db/.mount
 -> mount -t nfs -o ro,noatime,nolock,soft,timeo=30,intr myClient:/home/User/test test_db/.mount
 -> Dir: dir
Database closed: myClient
 -> umount -fl test_db/.mount
Trying client 'myClient.xp' using protocol 'smb'
 -> mount -t cifs -o ro,noatime,nocase //myClient/C$ test_db/.mount
 -> Reading client configuration file
Configuration:
 -> Client: myClient
 --> Subset: xp
 --> Protocol: smb
 --> Config: C:/Backup/Backup.LST
 --> Expiry: none
 --> Paths: 
 ---> Path: C:/Test Dir
 ----> Filter: and silly
 -----> Condition: filter backup
 -----> Condition: type p
 -----> Condition: name a
 -----> Condition: name_start b
 -----> Condition: name_end c
 -----> Condition: name_regex d
 -----> Condition: path e
 -----> Condition: path_start f
 -----> Condition: path_end g
 -----> Condition: name_regex h
 -----> Condition: size>= 1
 -----> Condition: size> 2048
 -----> Condition: size<= 3000000
 -----> Condition: size< 4294967296
 -----> Condition: mode& 777
 -----> Condition: mode= 644
Backing up client
Database open r/w: myClient.xp
Backup path: C:/Test Dir
 -> Dir: My Dir
Database closed: myClient.xp
 -> umount -fl test_db/.mount
Trying client 'myhost' using protocol 'file'
 -> Reading client configuration file
Configuration:
 -> Client: myhost
 --> Protocol: file
 --> Hostname: myhost.mynetwork.lan
 --> Config: etc/localhost.list
 --> Expiry: 86400s (1d)
 --> Filter: and subdir
 ---> Condition: path_start subdir
 ---> Condition: not size< 100
 --> Filter: and bigfile
 ---> Condition: size>= 10
 ---> Condition: type f
 --> Paths: 
 ---> Path: test1
 ----> Filter: and not_object
 -----> Condition: not path_end .o
 ----> Filter: or to_be_ignored
 -----> Condition: filter subdir
 -----> Condition: filter backup
 -----> Condition: not filter not_object
 ----> Parser: CVS
 ----> Parser: Subversion
 ----> Compress filter: bigfile
 ----> Ignore filter: to_be_ignored
 ---> Path: test2
Backing up client
Database open r/w: myhost
Backup path: test1
 -> Dir: cvs
 -> Parsing CVS entries
 --> dirbad: D
 --> dirutd: D
 --> filemod.o: 1159806431
 --> filenew.c: 0
 --> fileutd.h: 1159985080
 -> Dir: cvs/CVS
 -> Dir: cvs/dirbad
Warning: test1/cvs/dirbad: Directory should be under CVS control
 -> Dir: cvs/dirutd
 -> Parsing CVS entries
 --> fileutd: 1159985080
 -> Dir: cvs/dirutd/CVS
 -> Dir: dir space
 -> Dir: svn
 -> Parsing Subversion entries
 --> diroth: o
 --> filemod.o: m
 --> filenew.c: m
 --> fileoth: i
 -> Dir: svn/.svn
 -> Dir: svn/dirbad
Warning: test1/svn/dirbad: Directory should be under Subversion control
 -> Dir: svn/dirutd
 -> Parsing Subversion entries
 --> fileoth: o
 --> fileutd: m
 -> Dir: svn/dirutd/.svn
 -> Dir: testdir
Backup path: test2
 -> Dir: testdir
Database closed: myhost
Trying client 'other' using protocol 'ssh'
Error: other: Protocol not supported: ssh
List of missing checksums contains 1 item(s)
Database closed
