(0) default c'tor: bf 1 in 1 cp 128 sz 0 ''
(1) copy c'tor: bf 1 in 2 cp 128 sz 0 ''
(2) const char* constructor: bf 2 in 1 cp 128 sz 1 'a'
(3) const char* constructor: bf 3 in 1 cp 128 sz 3 'def'
(4) copy constructor: bf 2 in 2 cp 128 sz 1 'a'
copy:  bf 3 in 2 cp 128 sz 3 'def'
copy:  bf 4 in 1 cp 128 sz 1 'g'
copy:  bf 4 in 1 cp 128 sz 7 'hijklmn'
operator[0]: hijklmn
operator[3]: klmn
erase(5): hijkl bf 4 in 1 cp 128 sz 5 'hijkl'
find('j'): 2, size = 5
find('z'): -1, size = 5
find('j', 1): 2, size = 5
find('j', 4): -1, size = 5
append("op"): hijklop bf 4 in 1 cp 128 sz 7 'hijklop'
append("qr", 3): hijqr bf 4 in 1 cp 128 sz 5 'hijqr'
append("stuv", 4): hijqstuv bf 4 in 1 cp 128 sz 8 'hijqstuv'
append("wxy", 6): hijqstwxy bf 4 in 1 cp 128 sz 9 'hijqstwxy'
replace end of line
(0) new line: bf 5 in 1 cp 128 sz 11 '	0	new line'
(1) old line: bf 1 in 1 cp 128 sz 15 '	12345	old line'
second tab: 6
end line: 	12345	new line bf 1 in 1 cp 128 sz 15 '	12345	new line'
(5) default c'tor bf 6 in 1 cp 128 sz 0 ''
+= bf 6 in 1 cp 128 sz 9 '123456789'
+= bf 6 in 1 cp 128 sz 19 '1234567891234567890'
+= bf 6 in 1 cp 128 sz 28 '1234567891234567890123456789'
+= bf 6 in 1 cp 128 sz 37 '1234567891234567890123456789123456789'

No-copy
Construct line from string
line bf 7 in 1 cp 128 sz 6 'abcdef'
Modify line
line bf 7 in 1 cp 128 sz 6 'defghi'
Append to line
line bf 7 in 1 cp 128 sz 12 'defghijklmno'

Copy-construct line2
line bf 7 in 2 cp 128 sz 12 'defghijklmno'
line2 bf 7 in 2 cp 128 sz 12 'defghijklmno'
Modify line
line bf 8 in 1 cp 128 sz 6 'stuvwx'
line2 bf 7 in 1 cp 128 sz 12 'defghijklmno'
Delete line
line2 bf 7 in 1 cp 128 sz 12 'defghijklmno'
Default-construct line
line bf 9 in 1 cp 128 sz 0 ''
line2 bf 7 in 1 cp 128 sz 12 'defghijklmno'
Copy line2 into line
line bf 7 in 2 cp 128 sz 12 'defghijklmno'
line2 bf 7 in 2 cp 128 sz 12 'defghijklmno'
Append to line
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'
line2 bf 7 in 1 cp 128 sz 12 'defghijklmno'
Append line to line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'
line2 bf 7 in 1 cp 128 sz 26 'defghijklmnodefghijklmnoyz'
Copy line into line2
line bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
line2 bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
Erase from line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'
line2 bf 7 in 1 cp 128 sz 4 'defg'
Delete line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'

Erase
Copy-construct line2
line bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
line2 bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
Erase from line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'
line2 bf 10 in 1 cp 128 sz 4 'defg'
Delete line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'

Append
Copy-construct line2
line bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
line2 bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
Append to line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'
line2 bf 12 in 1 cp 128 sz 18 'defghijklmnoyzABCD'
Delete line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'

Get instance
Copy-construct line2
line bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
line2 bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
Get instance of line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'
line2 bf 13 in 1 cp 128 sz 14 'defghijklmnoyz'
Delete line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'

Replace extra buffer with bigger one
Copy-construct line2
line bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
line2 bf 9 in 2 cp 128 sz 14 'defghijklmnoyz'
Set value to line2
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'
line2 bf 14 in 1 cp 128 sz 15 'this is a line '
Increase line2 to more than 128
line bf 9 in 1 cp 128 sz 14 'defghijklmnoyz'
line2 bf 14 in 1 cp 256 sz 140 'this is a line this is a increased line this is a increased line this is a increased line this is a increased line this is a increased line '
Another buffer for line
line bf 15 in 1 cp 128 sz 20 'this is another line'
line2 bf 14 in 1 cp 256 sz 140 'this is a line this is a increased line this is a increased line this is a increased line this is a increased line this is a increased line '
Another buffer for line2
line bf 15 in 1 cp 128 sz 20 'this is another line'
line2 bf 16 in 1 cp 128 sz 22 'this is another line 2'
Yet another buffer for line2 (=> delete main buffer)
line bf 15 in 1 cp 128 sz 20 'this is another line'
line2 bf 17 in 1 cp 128 sz 25 'this is yet another line '
Copy line2 into line (=> same buffer)
line bf 17 in 2 cp 128 sz 25 'this is yet another line '
line2 bf 17 in 2 cp 128 sz 25 'this is yet another line '
Modify line2 (=> re-use big buffer)
line bf 17 in 1 cp 128 sz 25 'this is yet another line '
line2 bf 14 in 1 cp 256 sz 3 'abc'
Copy line2 into line (=> give big buffer)
line bf 14 in 2 cp 256 sz 3 'abc'
line2 bf 14 in 2 cp 256 sz 3 'abc'
Delete line2
line bf 14 in 1 cp 256 sz 3 'abc'
Another buffer for line (=> replace extra buffer)
line bf 18 in 1 cp 128 sz 20 'this is another line'
Delete line (=> two buffers deleted)

end of tests
