Test: DB lists

Test: journal write

Test: journal read
[ 1] file sp          f     0 644 
[ 1] file_gone        [rm]
[ 1] file_new         f    13 750 59ca0efa9f5633cb0371bbc0355478d8
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755

Test: journal merge into empty list
List is empty

Test: merge read
[ 1] file sp          f     0 644 
[ 1] file_gone        [rm]
[ 1] file_new         f    13 750 59ca0efa9f5633cb0371bbc0355478d8
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755

Test: journal write again

Test: journal read
[ 0] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325

Test: journal merge into list

Test: merge read
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] file_new         f    13 750 59ca0efa9f5633cb0371bbc0355478d8
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755

Test: get all paths
file sp
file sp: f
file_gone
file_gone: -
file_new
file_new: f
link
link: l
path
path: d

Test: journal path out of order

Test: journal read
[10] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[10] file_gone        f    20 750 12fec763b7f0a7d6acfc8bfe7606c325

Test: journal merge into list
Error: journal: 3: Path out of order
Failed to merge

Test: merge read
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[10] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325

Test: expire
List:
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] file_new         f    13 750 59ca0efa9f5633cb0371bbc0355478d8
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755
Date: 4
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755
Date: 0
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755

Test: copy all data
List:
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] file_new         f    13 750 59ca0efa9f5633cb0371bbc0355478d8
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755
Merge:
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] file_new         f    13 750 59ca0efa9f5633cb0371bbc0355478d8
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755
Merge tail:
# end

Test: get latest entry only
List:
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[13] file_new         f    22 750 246dccb0301976d765609dfb0efd68f9
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] file_new         f    13 750 59ca0efa9f5633cb0371bbc0355478d8
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755

Test: last entries data
List:
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[13] file_new         f    22 750 246dccb0301976d765609dfb0efd68f9
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755

Test: entries for given date
Date: 5
List:
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[ 1] file_gone        [rm]
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] link             l     8 777 testfile
[ 1] path             d     0 755

Test: journal write

Test: journal read
[14] file sp          f     0 644 
[14] file_gone        [rm]
[14] file_new         f    22 750 246dccb0301976d765609dfb0efd68f9
[14] link             l     8 777 testfile
[14] path             d     0 755
Error: Unexpected end of file
Failed to read journal

Test: broken journal merge
Warning: Unexpected end of journal

Test: merge read
[14] file sp          f     0 644 
[ 1] file sp          f     0 644 d41d8cd98f00b204e9800998ecf8427e
[14] file_gone        [rm]
[ 1] file_gone        [rm]
[14] file_new         f    22 750 246dccb0301976d765609dfb0efd68f9
[13] file_new         f    22 750 246dccb0301976d765609dfb0efd68f9
[ 5] file_new         f    20 750 12fec763b7f0a7d6acfc8bfe7606c325
[ 1] file_new         f    13 750 59ca0efa9f5633cb0371bbc0355478d8
[14] link             l     8 777 testfile
[ 1] link             l     8 777 testfile
[14] path             d     0 755
[ 1] path             d     0 755
