Test: DB lists

Test: journal write

Test: journal read
Prefix: prefix
Path:   file_gone
TS:     1
Type:   removed

Prefix: prefix2
Path:   file_new
TS:     1
Type:   file
Name:   file_new
Size:   13
Chcksm: 59ca0efa9f5633cb0371bbc0355478d8

Prefix: prefix3
Path:   link
TS:     1
Type:   link
Name:   link
Size:   8
Link:   testfile

Prefix: prefix5
Path:   path
TS:     1
Type:   other
Name:   path
Size:   0


Test: journal merge into empty list
List is empty

Test: merge read
Prefix: prefix
Path:   file_gone
TS:     1
Type:   removed

Prefix: prefix2
Path:   file_new
TS:     1
Type:   file
Name:   file_new
Size:   13
Chcksm: 59ca0efa9f5633cb0371bbc0355478d8

Prefix: prefix3
Path:   link
TS:     1
Type:   link
Name:   link
Size:   8
Link:   testfile

Prefix: prefix5
Path:   path
TS:     1
Type:   other
Name:   path
Size:   0


Test: journal write again

Test: journal read
Prefix: prefix
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix4
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325


Test: journal merge into list

Test: merge read
Prefix: prefix
Path:   file_gone
TS:     1
Type:   removed

Prefix: prefix
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_new
TS:     1
Type:   file
Name:   file_new
Size:   13
Chcksm: 59ca0efa9f5633cb0371bbc0355478d8

Prefix: prefix3
Path:   link
TS:     1
Type:   link
Name:   link
Size:   8
Link:   testfile

Prefix: prefix4
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix5
Path:   path
TS:     1
Type:   other
Name:   path
Size:   0


Test: journal prefix out of order

Test: journal read
Prefix: prefix4
Path:   file_new
TS:     9
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_new
TS:     9
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325


Test: journal merge into list
Prefix out of order in journal, line 4
Failed to merge: Structure needs cleaning

Test: merge read
Prefix: prefix
Path:   file_gone
TS:     1
Type:   removed

Prefix: prefix
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_new
TS:     1
Type:   file
Name:   file_new
Size:   13
Chcksm: 59ca0efa9f5633cb0371bbc0355478d8

Prefix: prefix3
Path:   link
TS:     1
Type:   link
Name:   link
Size:   8
Link:   testfile

Prefix: prefix4
Path:   file_new
TS:     9
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325


Test: journal path out of order

Test: journal read
Prefix: prefix2
Path:   file_new
TS:     13
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_gone
TS:     13
Type:   file
Name:   file_gone
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325


Test: journal merge into list
Path out of order in journal, line 5
Failed to merge: Structure needs cleaning

Test: merge read
Prefix: prefix
Path:   file_gone
TS:     1
Type:   removed

Prefix: prefix
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_new
TS:     13
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325


Test: prefix find
prefix 'path' not found
Prefix: prefix
Path:   file_gone
TS:     1
Type:   removed

Prefix: prefix
Path:   file_new
TS:     5
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

Prefix: prefix2
Path:   file_new
TS:     13
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

prefix 'silly' not found
prefix 'prefix2' found
Prefix: prefix2
Path:   file_new
TS:     13
Type:   file
Name:   file_new
Size:   20
Chcksm: 12fec763b7f0a7d6acfc8bfe7606c325

