Owner tests
Name: client
Path: test_db/client

First operation
Register created: client
Register modified: client
Register:
[11] /remote/path/testfile          f       13 750 
# version 4
/remote/path/testfile
	11	f	    13	750
# end
Dir contents:
test_db:
client

test_db/client:
journal~
list
list~

Update
Register modified: client
Register:
[12] /remote/path/testfile          f   145408 644 
[11] /remote/path/testfile          f       13 750 
Dir contents:
test_db:
client

test_db/client:
journal~
list
list~

Abort client
Register modified: client
Register:
[13] /remote/path/testfile          f       13 750 
[12] /remote/path/testfile          f   145408 644 
[11] /remote/path/testfile          f       13 750 
Dir contents:
test_db:
client

test_db/client:
journal~
list
list~

Abort backup
Register:
[13] /remote/path/testfile          f       13 750 
[12] /remote/path/testfile          f   145408 644 
[11] /remote/path/testfile          f       13 750 
Dir contents:
test_db:
client

test_db/client:
journal
journal~
list
list~

Recover client
Warning: Previous backup interrupted: client
Register modified: client
Register:
[14] /remote/path/testfile          f   145408 644 checksum test
[13] /remote/path/testfile          f       13 750 
[12] /remote/path/testfile          f   145408 644 
[11] /remote/path/testfile          f       13 750 
Dir contents:
test_db:
client

test_db/client:
journal~
list
list~

Recover client (empty journal)
Warning: Previous backup interrupted: client
Register:
[14] /remote/path/testfile          f   145408 644 checksum test
[13] /remote/path/testfile          f       13 750 
[12] /remote/path/testfile          f   145408 644 
[11] /remote/path/testfile          f       13 750 
Dir contents:
test_db:
client

test_db/client:
journal~
list
list~

Recover client (empty, not closed journal)
Warning: Previous backup interrupted: client
Register:
[14] /remote/path/testfile          f   145408 644 checksum test
[13] /remote/path/testfile          f       13 750 
[12] /remote/path/testfile          f   145408 644 
[11] /remote/path/testfile          f       13 750 
Dir contents:
test_db:
client

test_db/client:
journal~
list
list~

Get checksums
Register:
 -> checksum test, 145408
Dir contents:
test_db:
client

test_db/client:
journal~
list
list~

End of tests
