Database initialized
 -> Database open
first with subdir/testfile NOT readable
A /home/User/àccénts_test (0 B)
Adding file data to DB in: test_db/data/d41d8cd98f00b204e9800998ecf8427e-0
A /home/User/cvs
 -> Entering cvs
A /home/User/cvs/CVS
 -> Entering cvs/CVS
A /home/User/cvs/CVS/Entries (141 B)
Adding file data to DB in: test_db/data/63b52e85e7a255c09df5cca819b74a88-0
 -> Leaving cvs/CVS
A /home/User/cvs/dirbad
 -> Entering cvs/dirbad
A /home/User/cvs/dirbad/fileoth (0 B)
A /home/User/cvs/dirbad/fileutd (0 B)
 -> Leaving cvs/dirbad
A /home/User/cvs/diroth
 -> Entering cvs/diroth
 -> Leaving cvs/diroth
A /home/User/cvs/dirutd
 -> Entering cvs/dirutd
A /home/User/cvs/dirutd/CVS
 -> Entering cvs/dirutd/CVS
A /home/User/cvs/dirutd/CVS/Entries (42 B)
Adding file data to DB in: test_db/data/5252f242d27b8c2c9fdbdcbb33545d07-0
 -> Leaving cvs/dirutd/CVS
A /home/User/cvs/dirutd/fileoth (0 B)
A /home/User/cvs/dirutd/fileutd (0 B)
 -> Leaving cvs/dirutd
A /home/User/cvs/filemod.o (0 B)
A /home/User/cvs/filenew.c (0 B)
A /home/User/cvs/fileoth (0 B)
A /home/User/cvs/fileutd.h (0 B)
 -> Leaving cvs
A /home/User/dir space
 -> Entering dir space
A /home/User/dir space/file space (0 B)
 -> Leaving dir space
A /home/User/subdir
 -> Entering subdir
A /home/User/subdir/testfile (12 B)
Permission denied: test1/subdir/testfile
A /home/User/subdir/testfile1 (0 B)
A /home/User/subdir/testfile2 (12 B)
Adding file data to DB in: test_db/data/285b35198a5e188b3a0df3ed33f93a26-0
 -> Leaving subdir
A /home/User/subdir-file (0 B)
A /home/User/subdirfile (0 B)
A /home/User/test space (0 B)
A /home/User/testdir
 -> Entering testdir
 -> Leaving testdir
A /home/User/testfile (13 B)
Adding file data to DB in: test_db/data/59ca0efa9f5633cb0371bbc0355478d8-0
A /home/User/testfile~ (0 B)
A /home/User/testlink
A /home/User/testpipe
Parsed 31 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 1] d     0 755
	/home/User/subdir/testfile
[ 1] f    12 000 
	/home/User/subdir/testfile1
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 1] d     0 755
	/home/User/subdir/testfile
[ 1] f    12 000 
	/home/User/subdir/testfile1
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644
 -> Database open
as previous
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
 -> Leaving cvs/dirbad
 -> Entering cvs/diroth
 -> Leaving cvs/diroth
 -> Entering cvs/dirutd
 -> Entering cvs/dirutd/CVS
 -> Leaving cvs/dirutd/CVS
 -> Leaving cvs/dirutd
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering subdir
! /home/User/subdir/testfile (12 B)
Permission denied: test1/subdir/testfile
 -> Leaving subdir
 -> Entering testdir
 -> Leaving testdir
Parsed 31 file(s)
 -> Journal is empty, not merging
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 1] d     0 755
	/home/User/subdir/testfile
[ 1] f    12 000 
	/home/User/subdir/testfile1
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 1] d     0 755
	/home/User/subdir/testfile
[ 1] f    12 000 
	/home/User/subdir/testfile1
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644
 -> Database open
as previous with new big_file, interrupted
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
A /home/User/cvs/big_file (512 kB)
Killing during write
Operation canceled: test1/cvs/big_file
 -> Leaving cvs
Parsed 5 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 1] d     0 755
	/home/User/subdir/testfile
[ 1] f    12 000 
	/home/User/subdir/testfile1
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/cvs/big_file
[ 3] f 512000 644 
Previous crash detected, attempting recovery
 -> Database open
as previous with subdir/testfile readable
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
! /home/User/cvs/big_file (512 kB)
Adding file data to DB in: test_db/data/816df6f64deba63b029ca19d880ee10a-0
 -> Entering cvs/dirbad
 -> Leaving cvs/dirbad
 -> Entering cvs/diroth
 -> Leaving cvs/diroth
 -> Entering cvs/dirutd
 -> Entering cvs/dirutd/CVS
 -> Leaving cvs/dirutd/CVS
 -> Leaving cvs/dirutd
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering subdir
~ /home/User/subdir/testfile (12 B)
 -> Leaving subdir
 -> Entering testdir
 -> Leaving testdir
Parsed 32 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 1] d     0 755
	/home/User/subdir/testfile
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/cvs/big_file
[ 0] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/subdir/testfile
[ 0] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
 -> Database open
as previous with subdir/testfile in ignore list
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
 -> Leaving cvs/dirbad
 -> Entering cvs/diroth
 -> Leaving cvs/diroth
 -> Entering cvs/dirutd
 -> Entering cvs/dirutd/CVS
 -> Leaving cvs/dirutd/CVS
 -> Leaving cvs/dirutd
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering subdir
D /home/User/subdir/testfile
 -> Leaving subdir
 -> Entering testdir
 -> Leaving testdir
Parsed 31 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/subdir/testfile
[ 5] -
 -> Database open
as previous with subdir in ignore list
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
 -> Leaving cvs/dirbad
 -> Entering cvs/diroth
 -> Leaving cvs/diroth
 -> Entering cvs/dirutd
 -> Entering cvs/dirutd/CVS
 -> Leaving cvs/dirutd/CVS
 -> Leaving cvs/dirutd
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
D /home/User/subdir
D /home/User/subdir/testfile1
D /home/User/subdir/testfile2
 -> Entering testdir
 -> Leaving testdir
Parsed 28 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/subdir
[ 6] -
	/home/User/subdir/testfile1
[ 6] -
	/home/User/subdir/testfile2
[ 6] -
 -> Database open
as previous with testlink modified
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
 -> Leaving cvs/dirbad
 -> Entering cvs/diroth
 -> Leaving cvs/diroth
 -> Entering cvs/dirutd
 -> Entering cvs/dirutd/CVS
 -> Leaving cvs/dirutd/CVS
 -> Leaving cvs/dirutd
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering testdir
 -> Leaving testdir
M /home/User/testlink
Parsed 28 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/testlink
[ 7] l     8 777 testnull
 -> Database open
as previous with testlink in ignore list
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
 -> Leaving cvs/dirbad
 -> Entering cvs/diroth
 -> Leaving cvs/diroth
 -> Entering cvs/dirutd
 -> Entering cvs/dirutd/CVS
 -> Leaving cvs/dirutd/CVS
 -> Leaving cvs/dirutd
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering testdir
 -> Leaving testdir
D /home/User/testlink
Parsed 27 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/testlink
[ 8] -
 -> Database open
as previous with CVS parser
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
D /home/User/cvs/big_file
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
D /home/User/cvs/dirbad/fileoth
D /home/User/cvs/dirbad/fileutd
D /home/User/cvs/diroth
 -> Entering cvs/dirutd
 -> Entering cvs/dirutd/CVS
 -> Leaving cvs/dirutd/CVS
D /home/User/cvs/dirutd/fileoth
 -> Leaving cvs/dirutd
D /home/User/cvs/fileoth
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering testdir
 -> Leaving testdir
Parsed 21 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/cvs/big_file
[ 9] -
	/home/User/cvs/dirbad/fileoth
[ 9] -
	/home/User/cvs/dirbad/fileutd
[ 9] -
	/home/User/cvs/diroth
[ 9] -
	/home/User/cvs/dirutd/fileoth
[ 9] -
	/home/User/cvs/fileoth
[ 9] -
 -> Database open
as previous
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
 -> Entering cvs/dirutd
 -> Entering cvs/dirutd/CVS
 -> Leaving cvs/dirutd/CVS
 -> Leaving cvs/dirutd
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering testdir
 -> Leaving testdir
Parsed 21 file(s)
 -> Journal is empty, not merging
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/cvs/big_file
[ 9] -
	/home/User/cvs/dirbad/fileoth
[ 9] -
	/home/User/cvs/dirbad/fileutd
[ 9] -
	/home/User/cvs/diroth
[ 9] -
	/home/User/cvs/dirutd/fileoth
[ 9] -
	/home/User/cvs/fileoth
[ 9] -
 -> Database open
as previous with cvs/dirutd in ignore list
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
D /home/User/cvs/dirutd
D /home/User/cvs/dirutd/CVS
D /home/User/cvs/dirutd/CVS/Entries
D /home/User/cvs/dirutd/fileutd
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering testdir
 -> Leaving testdir
Parsed 17 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[ 1] p     0 644

Journal:
file://localhost
	/home/User/cvs/dirutd
[11] -
	/home/User/cvs/dirutd/CVS
[11] -
	/home/User/cvs/dirutd/CVS/Entries
[11] -
	/home/User/cvs/dirutd/fileutd
[11] -
 -> Database open
as previous with testpipe gone
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering testdir
 -> Leaving testdir
Parsed 16 file(s)
D /home/User/testpipe
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[12] -
[ 1] p     0 644

Journal:
file://localhost
	/home/User/testpipe
[12] -
 -> Database open
as previous with testfile mode changed
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering testdir
 -> Leaving testdir
~ /home/User/testfile (13 B)
Parsed 16 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[12] -
[ 1] p     0 644

Journal:
file://localhost
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
 -> Database open
as previous with cvs/filenew.c touched and testpipe restored
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
M /home/User/cvs/filenew.c (5 B)
Adding file data to DB in: test_db/data/0d599f0ec05c3bda8c3b8a68c32a1b47-0
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering testdir
 -> Leaving testdir
A /home/User/testpipe
Parsed 17 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[14] f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[14] p     0 644
[12] -
[ 1] p     0 644

Journal:
file://localhost
	/home/User/cvs/filenew.c
[14] f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
	/home/User/testpipe
[14] p     0 644
 -> Database open
some troublesome past cases
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
A /home/User/docbook-xml
 -> Entering docbook-xml
A /home/User/docbook-xml/3.1.7
 -> Entering docbook-xml/3.1.7
A /home/User/docbook-xml/3.1.7/dbgenent.ent (0 B)
 -> Leaving docbook-xml/3.1.7
A /home/User/docbook-xml/4.0
 -> Entering docbook-xml/4.0
A /home/User/docbook-xml/4.0/dbgenent.ent (0 B)
 -> Leaving docbook-xml/4.0
A /home/User/docbook-xml/4.1.2
 -> Entering docbook-xml/4.1.2
A /home/User/docbook-xml/4.1.2/dbgenent.mod (0 B)
 -> Leaving docbook-xml/4.1.2
A /home/User/docbook-xml/4.2
 -> Entering docbook-xml/4.2
A /home/User/docbook-xml/4.2/dbgenent.mod (0 B)
 -> Leaving docbook-xml/4.2
A /home/User/docbook-xml/4.3
 -> Entering docbook-xml/4.3
A /home/User/docbook-xml/4.3/dbgenent.mod (0 B)
 -> Leaving docbook-xml/4.3
A /home/User/docbook-xml/4.4
 -> Entering docbook-xml/4.4
A /home/User/docbook-xml/4.4/dbgenent.mod (0 B)
 -> Leaving docbook-xml/4.4
 -> Leaving docbook-xml
A /home/User/docbook-xml.cat (0 B)
A /home/User/docbook-xml.cat.old (0 B)
 -> Entering testdir
A /home/User/testdir/biblio
 -> Entering testdir/biblio
A /home/User/testdir/biblio/biblio.dbf (0 B)
A /home/User/testdir/biblio/biblio.dbt (0 B)
 -> Leaving testdir/biblio
A /home/User/testdir/biblio.odb (0 B)
A /home/User/testdir/evolocal.odb (0 B)
 -> Leaving testdir
Parsed 37 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[14] f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml
[15] d     0 755
	/home/User/docbook-xml/3.1.7
[15] d     0 755
	/home/User/docbook-xml/3.1.7/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.0
[15] d     0 755
	/home/User/docbook-xml/4.0/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.1.2
[15] d     0 755
	/home/User/docbook-xml/4.1.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.2
[15] d     0 755
	/home/User/docbook-xml/4.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.3
[15] d     0 755
	/home/User/docbook-xml/4.3/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.4
[15] d     0 755
	/home/User/docbook-xml/4.4/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat.old
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testdir/biblio
[15] d     0 755
	/home/User/testdir/biblio/biblio.dbf
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio/biblio.dbt
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/evolocal.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[14] p     0 644
[12] -
[ 1] p     0 644

Journal:
file://localhost
	/home/User/docbook-xml
[15] d     0 755
	/home/User/docbook-xml/3.1.7
[15] d     0 755
	/home/User/docbook-xml/3.1.7/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.0
[15] d     0 755
	/home/User/docbook-xml/4.0/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.1.2
[15] d     0 755
	/home/User/docbook-xml/4.1.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.2
[15] d     0 755
	/home/User/docbook-xml/4.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.3
[15] d     0 755
	/home/User/docbook-xml/4.3/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.4
[15] d     0 755
	/home/User/docbook-xml/4.4/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat.old
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio
[15] d     0 755
	/home/User/testdir/biblio/biblio.dbf
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio/biblio.dbt
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/evolocal.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
 -> Database open
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering docbook-xml
 -> Entering docbook-xml/3.1.7
 -> Leaving docbook-xml/3.1.7
 -> Entering docbook-xml/4.0
 -> Leaving docbook-xml/4.0
 -> Entering docbook-xml/4.1.2
 -> Leaving docbook-xml/4.1.2
 -> Entering docbook-xml/4.2
 -> Leaving docbook-xml/4.2
 -> Entering docbook-xml/4.3
 -> Leaving docbook-xml/4.3
 -> Entering docbook-xml/4.4
 -> Leaving docbook-xml/4.4
 -> Leaving docbook-xml
 -> Entering testdir
 -> Entering testdir/biblio
 -> Leaving testdir/biblio
 -> Leaving testdir
Parsed 37 file(s)
 -> Journal is empty, not merging
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[14] f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml
[15] d     0 755
	/home/User/docbook-xml/3.1.7
[15] d     0 755
	/home/User/docbook-xml/3.1.7/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.0
[15] d     0 755
	/home/User/docbook-xml/4.0/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.1.2
[15] d     0 755
	/home/User/docbook-xml/4.1.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.2
[15] d     0 755
	/home/User/docbook-xml/4.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.3
[15] d     0 755
	/home/User/docbook-xml/4.3/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.4
[15] d     0 755
	/home/User/docbook-xml/4.4/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat.old
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testdir/biblio
[15] d     0 755
	/home/User/testdir/biblio/biblio.dbf
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio/biblio.dbt
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/evolocal.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[14] p     0 644
[12] -
[ 1] p     0 644

Journal:
file://localhost
	/home/User/docbook-xml
[15] d     0 755
	/home/User/docbook-xml/3.1.7
[15] d     0 755
	/home/User/docbook-xml/3.1.7/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.0
[15] d     0 755
	/home/User/docbook-xml/4.0/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.1.2
[15] d     0 755
	/home/User/docbook-xml/4.1.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.2
[15] d     0 755
	/home/User/docbook-xml/4.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.3
[15] d     0 755
	/home/User/docbook-xml/4.3/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.4
[15] d     0 755
	/home/User/docbook-xml/4.4/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat.old
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio
[15] d     0 755
	/home/User/testdir/biblio/biblio.dbf
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio/biblio.dbt
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/evolocal.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0

List recovery after crash
 -> Database open
A /home/User/testdir
 -> Entering testdir
 -> Leaving testdir
A /home/User/testfile (145 kB)
Adding file data to DB in: test_db/data/3d546a1ce46c6ae10ad34ab8a81c542e-0
A /home/User/testfile2 (259 kB)
Adding file data to DB in: test_db/data/fb00cd74a5f35e89a7fbdd3c1d05375a-0
A /home/User/testfile~ (524 kB)
Adding file data to DB in: test_db/data/59071590099d21dd439896592338bf95-0
Parsed 4 file(s)
A /home/User/crash
 -> Entering crash
A /home/User/crash/file (0 B)
 -> Leaving crash
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering docbook-xml
 -> Entering docbook-xml/3.1.7
 -> Leaving docbook-xml/3.1.7
 -> Entering docbook-xml/4.0
 -> Leaving docbook-xml/4.0
 -> Entering docbook-xml/4.1.2
 -> Leaving docbook-xml/4.1.2
 -> Entering docbook-xml/4.2
 -> Leaving docbook-xml/4.2
 -> Entering docbook-xml/4.3
 -> Leaving docbook-xml/4.3
 -> Entering docbook-xml/4.4
 -> Leaving docbook-xml/4.4
 -> Leaving docbook-xml
M /home/User/test space (0 B)
D /home/User/testdir
D /home/User/testdir/biblio
D /home/User/testdir/biblio/biblio.dbf
D /home/User/testdir/biblio/biblio.dbt
D /home/User/testdir/biblio.odb
D /home/User/testdir/evolocal.odb
Parsed 33 file(s)
 -> Database closed

List:
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[14] f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml
[15] d     0 755
	/home/User/docbook-xml/3.1.7
[15] d     0 755
	/home/User/docbook-xml/3.1.7/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.0
[15] d     0 755
	/home/User/docbook-xml/4.0/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.1.2
[15] d     0 755
	/home/User/docbook-xml/4.1.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.2
[15] d     0 755
	/home/User/docbook-xml/4.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.3
[15] d     0 755
	/home/User/docbook-xml/4.3/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.4
[15] d     0 755
	/home/User/docbook-xml/4.4/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat.old
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[ 1] d     0 755
	/home/User/testdir/biblio
[15] d     0 755
	/home/User/testdir/biblio/biblio.dbf
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio/biblio.dbt
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/evolocal.odb
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[14] p     0 644
[12] -
[ 1] p     0 644

Journal:
file://host
	/home/User/testdir
[17] d     0 755
	/home/User/testfile
[17] f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
	/home/User/testfile2
[17] f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
	/home/User/testfile~
[17] f 524288 644 59071590099d21dd439896592338bf95-0
file://localhost
	/home/User/crash
[17] d     0 755
	/home/User/crash/file
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[17] -
	/home/User/testdir/biblio
[17] -
	/home/User/testdir/biblio/biblio.dbf
[17] -
	/home/User/testdir/biblio/biblio.dbt
[17] -
	/home/User/testdir/biblio.odb
[17] -
	/home/User/testdir/evolocal.odb
[17] -
Previous crash detected, attempting recovery
Unexpected end of journal, line 29
 -> Database open

List:
file://host
	/home/User/testdir
[17] d     0 755
	/home/User/testfile
[17] f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
	/home/User/testfile2
[17] f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
	/home/User/testfile~
[17] f 524288 644 59071590099d21dd439896592338bf95-0
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/crash
[17] d     0 755
	/home/User/crash/file
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[14] f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml
[15] d     0 755
	/home/User/docbook-xml/3.1.7
[15] d     0 755
	/home/User/docbook-xml/3.1.7/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.0
[15] d     0 755
	/home/User/docbook-xml/4.0/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.1.2
[15] d     0 755
	/home/User/docbook-xml/4.1.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.2
[15] d     0 755
	/home/User/docbook-xml/4.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.3
[15] d     0 755
	/home/User/docbook-xml/4.3/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.4
[15] d     0 755
	/home/User/docbook-xml/4.4/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat.old
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[17] -
[ 1] d     0 755
	/home/User/testdir/biblio
[17] -
[15] d     0 755
	/home/User/testdir/biblio/biblio.dbf
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio/biblio.dbt
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio.odb
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/evolocal.odb
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[14] p     0 644
[12] -
[ 1] p     0 644

Journal:
file://host
	/home/User/testdir
[17] d     0 755
	/home/User/testfile
[17] f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
	/home/User/testfile2
[17] f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
	/home/User/testfile~
[17] f 524288 644 59071590099d21dd439896592338bf95-0
file://localhost
	/home/User/crash
[17] d     0 755
	/home/User/crash/file
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[17] -
	/home/User/testdir/biblio
[17] -
	/home/User/testdir/biblio/biblio.dbf
[17] -
	/home/User/testdir/biblio/biblio.dbt
[17] -
	/home/User/testdir/biblio.odb
[17] -
	/home/User/testdir/evolocal.odb
[17] -
 -> Journal is empty, not merging
 -> Database closed
 -> Database open
 -> Journal is empty, not merging
 -> Database closed
 -> Database open
 -> Entering crash
 -> Leaving crash
 -> Entering cvs
 -> Entering cvs/CVS
 -> Leaving cvs/CVS
 -> Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
 -> Leaving cvs/dirbad
 -> Leaving cvs
 -> Entering dir space
 -> Leaving dir space
 -> Entering docbook-xml
 -> Entering docbook-xml/3.1.7
 -> Leaving docbook-xml/3.1.7
 -> Entering docbook-xml/4.0
 -> Leaving docbook-xml/4.0
 -> Entering docbook-xml/4.1.2
 -> Leaving docbook-xml/4.1.2
 -> Entering docbook-xml/4.2
 -> Leaving docbook-xml/4.2
 -> Entering docbook-xml/4.3
 -> Leaving docbook-xml/4.3
 -> Entering docbook-xml/4.4
 -> Leaving docbook-xml/4.4
 -> Leaving docbook-xml
Parsed 33 file(s)
 -> Journal is empty, not merging
 -> Database closed

List:
file://host
	/home/User/testdir
[17] d     0 755
	/home/User/testfile
[17] f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
	/home/User/testfile2
[17] f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
	/home/User/testfile~
[17] f 524288 644 59071590099d21dd439896592338bf95-0
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/crash
[17] d     0 755
	/home/User/crash/file
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[14] f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml
[15] d     0 755
	/home/User/docbook-xml/3.1.7
[15] d     0 755
	/home/User/docbook-xml/3.1.7/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.0
[15] d     0 755
	/home/User/docbook-xml/4.0/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.1.2
[15] d     0 755
	/home/User/docbook-xml/4.1.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.2
[15] d     0 755
	/home/User/docbook-xml/4.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.3
[15] d     0 755
	/home/User/docbook-xml/4.3/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.4
[15] d     0 755
	/home/User/docbook-xml/4.4/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat.old
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[17] -
[ 1] d     0 755
	/home/User/testdir/biblio
[17] -
[15] d     0 755
	/home/User/testdir/biblio/biblio.dbf
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio/biblio.dbt
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio.odb
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/evolocal.odb
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[14] p     0 644
[12] -
[ 1] p     0 644

Journal:
file://host
	/home/User/testdir
[17] d     0 755
	/home/User/testfile
[17] f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
	/home/User/testfile2
[17] f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
	/home/User/testfile~
[17] f 524288 644 59071590099d21dd439896592338bf95-0
file://localhost
	/home/User/crash
[17] d     0 755
	/home/User/crash/file
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[17] -
	/home/User/testdir/biblio
[17] -
	/home/User/testdir/biblio/biblio.dbf
[17] -
	/home/User/testdir/biblio/biblio.dbt
[17] -
	/home/User/testdir/biblio.odb
[17] -
	/home/User/testdir/evolocal.odb
[17] -
 -> Database open
 -> Entering testdir
 -> Leaving testdir
Parsed 4 file(s)
 -> Journal is empty, not merging
 -> Database closed

List:
file://host
	/home/User/testdir
[17] d     0 755
	/home/User/testfile
[17] f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
	/home/User/testfile2
[17] f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
	/home/User/testfile~
[17] f 524288 644 59071590099d21dd439896592338bf95-0
file://localhost
	/home/User/àccénts_test
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/crash
[17] d     0 755
	/home/User/crash/file
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs
[ 1] d     0 755
	/home/User/cvs/CVS
[ 1] d     0 755
	/home/User/cvs/CVS/Entries
[ 1] f   141 644 63b52e85e7a255c09df5cca819b74a88-0
	/home/User/cvs/big_file
[ 9] -
[ 3] f 512000 644 816df6f64deba63b029ca19d880ee10a-0
	/home/User/cvs/dirbad
[ 1] d     0 755
	/home/User/cvs/dirbad/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirbad/fileutd
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/diroth
[ 9] -
[ 1] d     0 755
	/home/User/cvs/dirutd
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS
[11] -
[ 1] d     0 755
	/home/User/cvs/dirutd/CVS/Entries
[11] -
[ 1] f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
	/home/User/cvs/dirutd/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/dirutd/fileutd
[11] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filemod.o
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/filenew.c
[14] f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileoth
[ 9] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/cvs/fileutd.h
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/dir space
[ 1] d     0 755
	/home/User/dir space/file space
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml
[15] d     0 755
	/home/User/docbook-xml/3.1.7
[15] d     0 755
	/home/User/docbook-xml/3.1.7/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.0
[15] d     0 755
	/home/User/docbook-xml/4.0/dbgenent.ent
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.1.2
[15] d     0 755
	/home/User/docbook-xml/4.1.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.2
[15] d     0 755
	/home/User/docbook-xml/4.2/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.3
[15] d     0 755
	/home/User/docbook-xml/4.3/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml/4.4
[15] d     0 755
	/home/User/docbook-xml/4.4/dbgenent.mod
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/docbook-xml.cat.old
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir
[ 6] -
[ 1] d     0 755
	/home/User/subdir/testfile
[ 5] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir/testfile1
[ 6] -
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdir/testfile2
[ 6] -
[ 1] f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
	/home/User/subdir-file
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/subdirfile
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[17] -
[ 1] d     0 755
	/home/User/testdir/biblio
[17] -
[15] d     0 755
	/home/User/testdir/biblio/biblio.dbf
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio/biblio.dbt
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/biblio.odb
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir/evolocal.odb
[17] -
[15] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testfile
[13] f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
	/home/User/testfile~
[ 1] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testlink
[ 8] -
[ 7] l     8 777 testnull
[ 1] l     8 777 testfile
	/home/User/testpipe
[14] p     0 644
[12] -
[ 1] p     0 644

Journal:
file://host
	/home/User/testdir
[17] d     0 755
	/home/User/testfile
[17] f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
	/home/User/testfile2
[17] f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
	/home/User/testfile~
[17] f 524288 644 59071590099d21dd439896592338bf95-0
file://localhost
	/home/User/crash
[17] d     0 755
	/home/User/crash/file
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/test space
[17] f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
	/home/User/testdir
[17] -
	/home/User/testdir/biblio
[17] -
	/home/User/testdir/biblio/biblio.dbf
[17] -
	/home/User/testdir/biblio/biblio.dbt
[17] -
	/home/User/testdir/biblio.odb
[17] -
	/home/User/testdir/evolocal.odb
[17] -
