Database initialized
first with subdir/testfile NOT readable
A /home/User/àccénts_test
A /home/User/cvs
Entering cvs
A /home/User/cvs/CVS
Entering cvs/CVS
A /home/User/cvs/CVS/Entries
Leaving cvs/CVS
A /home/User/cvs/dirbad
Entering cvs/dirbad
A /home/User/cvs/dirbad/fileoth
A /home/User/cvs/dirbad/fileutd
Leaving cvs/dirbad
A /home/User/cvs/diroth
Entering cvs/diroth
Leaving cvs/diroth
A /home/User/cvs/dirutd
Entering cvs/dirutd
A /home/User/cvs/dirutd/CVS
Entering cvs/dirutd/CVS
A /home/User/cvs/dirutd/CVS/Entries
Leaving cvs/dirutd/CVS
A /home/User/cvs/dirutd/fileoth
A /home/User/cvs/dirutd/fileutd
Leaving cvs/dirutd
A /home/User/cvs/filemod.o
A /home/User/cvs/filenew.c
A /home/User/cvs/fileoth
A /home/User/cvs/fileutd.h
Leaving cvs
A /home/User/dir space
Entering dir space
A /home/User/dir space/file space
Leaving dir space
A /home/User/subdir
Entering subdir
Permission denied: test1/subdir/testfile
A /home/User/subdir/testfile
A /home/User/subdir/testfile1
A /home/User/subdir/testfile2
Leaving subdir
A /home/User/subdir-file
A /home/User/subdirfile
A /home/User/test space
A /home/User/testdir
Entering testdir
Leaving testdir
A /home/User/testfile
A /home/User/testfile~
A /home/User/testlink
A /home/User/testpipe
Parsed 31 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 1] file://localhost /home/User/subdir/testfile         f    12 000 
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 1] file://localhost /home/User/subdir/testfile         f    12 000 
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644
as previous
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Leaving cvs/dirbad
Entering cvs/diroth
Leaving cvs/diroth
Entering cvs/dirutd
Entering cvs/dirutd/CVS
Leaving cvs/dirutd/CVS
Leaving cvs/dirutd
Leaving cvs
Entering dir space
Leaving dir space
Entering subdir
! /home/User/subdir/testfile
Permission denied: test1/subdir/testfile
Leaving subdir
Entering testdir
Leaving testdir
Parsed 31 file(s)
 ---> Journal is empty, not merging

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 1] file://localhost /home/User/subdir/testfile         f    12 000 
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
as previous with subdir/testfile readable
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Leaving cvs/dirbad
Entering cvs/diroth
Leaving cvs/diroth
Entering cvs/dirutd
Entering cvs/dirutd/CVS
Leaving cvs/dirutd/CVS
Leaving cvs/dirutd
Leaving cvs
Entering dir space
Leaving dir space
Entering subdir
~ /home/User/subdir/testfile
Leaving subdir
Entering testdir
Leaving testdir
Parsed 31 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[ 0] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
as previous with subdir/testfile in ignore list
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Leaving cvs/dirbad
Entering cvs/diroth
Leaving cvs/diroth
Entering cvs/dirutd
Entering cvs/dirutd/CVS
Leaving cvs/dirutd/CVS
Leaving cvs/dirutd
Leaving cvs
Entering dir space
Leaving dir space
Entering subdir
D /home/User/subdir/testfile
Leaving subdir
Entering testdir
Leaving testdir
Parsed 30 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[ 4] file://localhost /home/User/subdir/testfile         [rm]
as previous with subdir in ignore list
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Leaving cvs/dirbad
Entering cvs/diroth
Leaving cvs/diroth
Entering cvs/dirutd
Entering cvs/dirutd/CVS
Leaving cvs/dirutd/CVS
Leaving cvs/dirutd
Leaving cvs
Entering dir space
Leaving dir space
D /home/User/subdir
D /home/User/subdir/testfile1
D /home/User/subdir/testfile2
Entering testdir
Leaving testdir
Parsed 27 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[ 5] file://localhost /home/User/subdir                  [rm]
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
as previous with testlink modified
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Leaving cvs/dirbad
Entering cvs/diroth
Leaving cvs/diroth
Entering cvs/dirutd
Entering cvs/dirutd/CVS
Leaving cvs/dirutd/CVS
Leaving cvs/dirutd
Leaving cvs
Entering dir space
Leaving dir space
Entering testdir
Leaving testdir
M /home/User/testlink
Parsed 27 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
as previous with testlink in ignore list
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Leaving cvs/dirbad
Entering cvs/diroth
Leaving cvs/diroth
Entering cvs/dirutd
Entering cvs/dirutd/CVS
Leaving cvs/dirutd/CVS
Leaving cvs/dirutd
Leaving cvs
Entering dir space
Leaving dir space
Entering testdir
Leaving testdir
D /home/User/testlink
Parsed 26 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[ 7] file://localhost /home/User/testlink                [rm]
as previous with CVS parser
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
D /home/User/cvs/dirbad/fileoth
D /home/User/cvs/dirbad/fileutd
D /home/User/cvs/diroth
Entering cvs/dirutd
Entering cvs/dirutd/CVS
Leaving cvs/dirutd/CVS
D /home/User/cvs/dirutd/fileoth
Leaving cvs/dirutd
D /home/User/cvs/fileoth
Leaving cvs
Entering dir space
Leaving dir space
Entering testdir
Leaving testdir
Parsed 21 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
as previous
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
Entering cvs/dirutd
Entering cvs/dirutd/CVS
Leaving cvs/dirutd/CVS
Leaving cvs/dirutd
Leaving cvs
Entering dir space
Leaving dir space
Entering testdir
Leaving testdir
Parsed 21 file(s)
 ---> Journal is empty, not merging

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
as previous with cvs/dirutd in ignore list
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
D /home/User/cvs/dirutd
D /home/User/cvs/dirutd/CVS
D /home/User/cvs/dirutd/CVS/Entries
D /home/User/cvs/dirutd/fileutd
Leaving cvs
Entering dir space
Leaving dir space
Entering testdir
Leaving testdir
Parsed 17 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[10] file://localhost /home/User/cvs/dirutd              [rm]
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
as previous with testpipe gone
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
Leaving cvs
Entering dir space
Leaving dir space
Entering testdir
Leaving testdir
Parsed 16 file(s)
D /home/User/testpipe

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[11] file://localhost /home/User/testpipe                [rm]
as previous with testfile mode changed
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
Leaving cvs
Entering dir space
Leaving dir space
Entering testdir
Leaving testdir
~ /home/User/testfile
Parsed 16 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
as previous with cvs/filenew.c touched
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
M /home/User/cvs/filenew.c
Leaving cvs
Entering dir space
Leaving dir space
Entering testdir
Leaving testdir
Parsed 16 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[13] file://localhost /home/User/cvs/filenew.c           f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[13] file://localhost /home/User/cvs/filenew.c           f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
some troublesome past cases
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
Leaving cvs
Entering dir space
Leaving dir space
A /home/User/docbook-xml
Entering docbook-xml
A /home/User/docbook-xml/3.1.7
Entering docbook-xml/3.1.7
A /home/User/docbook-xml/3.1.7/dbgenent.ent
Leaving docbook-xml/3.1.7
A /home/User/docbook-xml/4.0
Entering docbook-xml/4.0
A /home/User/docbook-xml/4.0/dbgenent.ent
Leaving docbook-xml/4.0
A /home/User/docbook-xml/4.1.2
Entering docbook-xml/4.1.2
A /home/User/docbook-xml/4.1.2/dbgenent.mod
Leaving docbook-xml/4.1.2
A /home/User/docbook-xml/4.2
Entering docbook-xml/4.2
A /home/User/docbook-xml/4.2/dbgenent.mod
Leaving docbook-xml/4.2
A /home/User/docbook-xml/4.3
Entering docbook-xml/4.3
A /home/User/docbook-xml/4.3/dbgenent.mod
Leaving docbook-xml/4.3
A /home/User/docbook-xml/4.4
Entering docbook-xml/4.4
A /home/User/docbook-xml/4.4/dbgenent.mod
Leaving docbook-xml/4.4
Leaving docbook-xml
A /home/User/docbook-xml.cat
A /home/User/docbook-xml.cat.old
Entering testdir
A /home/User/testdir/biblio
Entering testdir/biblio
A /home/User/testdir/biblio/biblio.dbf
A /home/User/testdir/biblio/biblio.dbt
Leaving testdir/biblio
A /home/User/testdir/biblio.odb
A /home/User/testdir/evolocal.odb
Leaving testdir
Parsed 36 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[13] file://localhost /home/User/cvs/filenew.c           f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml             d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7       d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.0         d     0 755
[14] file://localhost /home/User/docbook-xml/4.0/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.1.2       d     0 755
[14] file://localhost /home/User/docbook-xml/4.1.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.2         d     0 755
[14] file://localhost /home/User/docbook-xml/4.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.3         d     0 755
[14] file://localhost /home/User/docbook-xml/4.3/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.4         d     0 755
[14] file://localhost /home/User/docbook-xml/4.4/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat.old     f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[14] file://localhost /home/User/testdir/biblio          d     0 755
[14] file://localhost /home/User/testdir/biblio/biblio.dbf f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio/biblio.dbt f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio.odb      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/evolocal.odb    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[14] file://localhost /home/User/docbook-xml             d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7       d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.0         d     0 755
[14] file://localhost /home/User/docbook-xml/4.0/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.1.2       d     0 755
[14] file://localhost /home/User/docbook-xml/4.1.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.2         d     0 755
[14] file://localhost /home/User/docbook-xml/4.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.3         d     0 755
[14] file://localhost /home/User/docbook-xml/4.3/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.4         d     0 755
[14] file://localhost /home/User/docbook-xml/4.4/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat.old     f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio          d     0 755
[14] file://localhost /home/User/testdir/biblio/biblio.dbf f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio/biblio.dbt f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio.odb      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/evolocal.odb    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
Leaving cvs
Entering dir space
Leaving dir space
Entering docbook-xml
Entering docbook-xml/3.1.7
Leaving docbook-xml/3.1.7
Entering docbook-xml/4.0
Leaving docbook-xml/4.0
Entering docbook-xml/4.1.2
Leaving docbook-xml/4.1.2
Entering docbook-xml/4.2
Leaving docbook-xml/4.2
Entering docbook-xml/4.3
Leaving docbook-xml/4.3
Entering docbook-xml/4.4
Leaving docbook-xml/4.4
Leaving docbook-xml
Entering testdir
Entering testdir/biblio
Leaving testdir/biblio
Leaving testdir
Parsed 36 file(s)
 ---> Journal is empty, not merging

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[13] file://localhost /home/User/cvs/filenew.c           f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml             d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7       d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.0         d     0 755
[14] file://localhost /home/User/docbook-xml/4.0/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.1.2       d     0 755
[14] file://localhost /home/User/docbook-xml/4.1.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.2         d     0 755
[14] file://localhost /home/User/docbook-xml/4.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.3         d     0 755
[14] file://localhost /home/User/docbook-xml/4.3/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.4         d     0 755
[14] file://localhost /home/User/docbook-xml/4.4/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat.old     f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[14] file://localhost /home/User/testdir/biblio          d     0 755
[14] file://localhost /home/User/testdir/biblio/biblio.dbf f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio/biblio.dbt f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio.odb      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/evolocal.odb    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:

List recovery after crash
A /home/User/testdir
Entering testdir
Leaving testdir
A /home/User/testfile
A /home/User/testfile2
A /home/User/testfile~
Parsed 4 file(s)
A /home/User/crash
Entering crash
A /home/User/crash/file
Leaving crash
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
Leaving cvs
Entering dir space
Leaving dir space
Entering docbook-xml
Entering docbook-xml/3.1.7
Leaving docbook-xml/3.1.7
Entering docbook-xml/4.0
Leaving docbook-xml/4.0
Entering docbook-xml/4.1.2
Leaving docbook-xml/4.1.2
Entering docbook-xml/4.2
Leaving docbook-xml/4.2
Entering docbook-xml/4.3
Leaving docbook-xml/4.3
Entering docbook-xml/4.4
Leaving docbook-xml/4.4
Leaving docbook-xml
M /home/User/test space
D /home/User/testdir
D /home/User/testdir/biblio
D /home/User/testdir/biblio/biblio.dbf
D /home/User/testdir/biblio/biblio.dbt
D /home/User/testdir/biblio.odb
D /home/User/testdir/evolocal.odb
Parsed 32 file(s)

List:
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[13] file://localhost /home/User/cvs/filenew.c           f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml             d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7       d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.0         d     0 755
[14] file://localhost /home/User/docbook-xml/4.0/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.1.2       d     0 755
[14] file://localhost /home/User/docbook-xml/4.1.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.2         d     0 755
[14] file://localhost /home/User/docbook-xml/4.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.3         d     0 755
[14] file://localhost /home/User/docbook-xml/4.3/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.4         d     0 755
[14] file://localhost /home/User/docbook-xml/4.4/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat.old     f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/testdir                 d     0 755
[14] file://localhost /home/User/testdir/biblio          d     0 755
[14] file://localhost /home/User/testdir/biblio/biblio.dbf f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio/biblio.dbt f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/biblio.odb      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/testdir/evolocal.odb    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[16] file://host      /home/User/testdir                 d     0 755
[16] file://host      /home/User/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[16] file://host      /home/User/testfile2               f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[16] file://host      /home/User/testfile~               f 524288 644 59071590099d21dd439896592338bf95-0
[16] file://localhost /home/User/crash                   d     0 755
[16] file://localhost /home/User/crash/file              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir                 [rm]
[16] file://localhost /home/User/testdir/biblio          [rm]
[16] file://localhost /home/User/testdir/biblio/biblio.dbf [rm]
[16] file://localhost /home/User/testdir/biblio/biblio.dbt [rm]
[16] file://localhost /home/User/testdir/biblio.odb      [rm]
[16] file://localhost /home/User/testdir/evolocal.odb    [rm]
unexpected end of file
Previous crash detected, attempting recovery
Unexpected end of journal, line 29

List:
[16] file://host      /home/User/testdir                 d     0 755
[16] file://host      /home/User/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[16] file://host      /home/User/testfile2               f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[16] file://host      /home/User/testfile~               f 524288 644 59071590099d21dd439896592338bf95-0
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/crash                   d     0 755
[16] file://localhost /home/User/crash/file              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[13] file://localhost /home/User/cvs/filenew.c           f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml             d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7       d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.0         d     0 755
[14] file://localhost /home/User/docbook-xml/4.0/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.1.2       d     0 755
[14] file://localhost /home/User/docbook-xml/4.1.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.2         d     0 755
[14] file://localhost /home/User/docbook-xml/4.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.3         d     0 755
[14] file://localhost /home/User/docbook-xml/4.3/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.4         d     0 755
[14] file://localhost /home/User/docbook-xml/4.4/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat.old     f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir                 [rm]
[ 1] file://localhost /home/User/testdir                 d     0 755
[16] file://localhost /home/User/testdir/biblio          [rm]
[14] file://localhost /home/User/testdir/biblio          d     0 755
[16] file://localhost /home/User/testdir/biblio/biblio.dbf [rm]
[14] file://localhost /home/User/testdir/biblio/biblio.dbf f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/biblio/biblio.dbt [rm]
[14] file://localhost /home/User/testdir/biblio/biblio.dbt f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/biblio.odb      [rm]
[14] file://localhost /home/User/testdir/biblio.odb      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/evolocal.odb    [rm]
[14] file://localhost /home/User/testdir/evolocal.odb    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
[16] file://host      /home/User/testdir                 d     0 755
[16] file://host      /home/User/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[16] file://host      /home/User/testfile2               f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[16] file://host      /home/User/testfile~               f 524288 644 59071590099d21dd439896592338bf95-0
[16] file://localhost /home/User/crash                   d     0 755
[16] file://localhost /home/User/crash/file              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir                 [rm]
[16] file://localhost /home/User/testdir/biblio          [rm]
[16] file://localhost /home/User/testdir/biblio/biblio.dbf [rm]
[16] file://localhost /home/User/testdir/biblio/biblio.dbt [rm]
[16] file://localhost /home/User/testdir/biblio.odb      [rm]
[16] file://localhost /home/User/testdir/evolocal.odb    [rm]
unexpected end of file
 ---> Journal is empty, not merging
 ---> Journal is empty, not merging
Entering crash
Leaving crash
Entering cvs
Entering cvs/CVS
Leaving cvs/CVS
Entering cvs/dirbad
Directory should be under CVS control: test1/cvs/dirbad
Leaving cvs/dirbad
Leaving cvs
Entering dir space
Leaving dir space
Entering docbook-xml
Entering docbook-xml/3.1.7
Leaving docbook-xml/3.1.7
Entering docbook-xml/4.0
Leaving docbook-xml/4.0
Entering docbook-xml/4.1.2
Leaving docbook-xml/4.1.2
Entering docbook-xml/4.2
Leaving docbook-xml/4.2
Entering docbook-xml/4.3
Leaving docbook-xml/4.3
Entering docbook-xml/4.4
Leaving docbook-xml/4.4
Leaving docbook-xml
Parsed 32 file(s)
 ---> Journal is empty, not merging

List:
[16] file://host      /home/User/testdir                 d     0 755
[16] file://host      /home/User/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[16] file://host      /home/User/testfile2               f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[16] file://host      /home/User/testfile~               f 524288 644 59071590099d21dd439896592338bf95-0
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/crash                   d     0 755
[16] file://localhost /home/User/crash/file              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[13] file://localhost /home/User/cvs/filenew.c           f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml             d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7       d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.0         d     0 755
[14] file://localhost /home/User/docbook-xml/4.0/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.1.2       d     0 755
[14] file://localhost /home/User/docbook-xml/4.1.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.2         d     0 755
[14] file://localhost /home/User/docbook-xml/4.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.3         d     0 755
[14] file://localhost /home/User/docbook-xml/4.3/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.4         d     0 755
[14] file://localhost /home/User/docbook-xml/4.4/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat.old     f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir                 [rm]
[ 1] file://localhost /home/User/testdir                 d     0 755
[16] file://localhost /home/User/testdir/biblio          [rm]
[14] file://localhost /home/User/testdir/biblio          d     0 755
[16] file://localhost /home/User/testdir/biblio/biblio.dbf [rm]
[14] file://localhost /home/User/testdir/biblio/biblio.dbf f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/biblio/biblio.dbt [rm]
[14] file://localhost /home/User/testdir/biblio/biblio.dbt f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/biblio.odb      [rm]
[14] file://localhost /home/User/testdir/biblio.odb      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/evolocal.odb    [rm]
[14] file://localhost /home/User/testdir/evolocal.odb    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
Entering testdir
Leaving testdir
Parsed 4 file(s)
 ---> Journal is empty, not merging

List:
[16] file://host      /home/User/testdir                 d     0 755
[16] file://host      /home/User/testfile                f 145408 644 3d546a1ce46c6ae10ad34ab8a81c542e-0
[16] file://host      /home/User/testfile2               f 259072 644 fb00cd74a5f35e89a7fbdd3c1d05375a-0
[16] file://host      /home/User/testfile~               f 524288 644 59071590099d21dd439896592338bf95-0
[ 1] file://localhost /home/User/àccénts_test          f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/crash                   d     0 755
[16] file://localhost /home/User/crash/file              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs                     d     0 755
[ 1] file://localhost /home/User/cvs/CVS                 d     0 755
[ 1] file://localhost /home/User/cvs/CVS/Entries         f   141 644 63b52e85e7a255c09df5cca819b74a88-0
[ 1] file://localhost /home/User/cvs/dirbad              d     0 755
[ 8] file://localhost /home/User/cvs/dirbad/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/dirbad/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirbad/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/diroth              [rm]
[ 1] file://localhost /home/User/cvs/diroth              d     0 755
[10] file://localhost /home/User/cvs/dirutd              [rm]
[ 1] file://localhost /home/User/cvs/dirutd              d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS          [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS          d     0 755
[10] file://localhost /home/User/cvs/dirutd/CVS/Entries  [rm]
[ 1] file://localhost /home/User/cvs/dirutd/CVS/Entries  f    42 644 5252f242d27b8c2c9fdbdcbb33545d07-0
[ 8] file://localhost /home/User/cvs/dirutd/fileoth      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileoth      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[10] file://localhost /home/User/cvs/dirutd/fileutd      [rm]
[ 1] file://localhost /home/User/cvs/dirutd/fileutd      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/filemod.o           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[13] file://localhost /home/User/cvs/filenew.c           f     5 644 0d599f0ec05c3bda8c3b8a68c32a1b47-0
[ 1] file://localhost /home/User/cvs/filenew.c           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 8] file://localhost /home/User/cvs/fileoth             [rm]
[ 1] file://localhost /home/User/cvs/fileoth             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/cvs/fileutd.h           f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/dir space               d     0 755
[ 1] file://localhost /home/User/dir space/file space    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml             d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7       d     0 755
[14] file://localhost /home/User/docbook-xml/3.1.7/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.0         d     0 755
[14] file://localhost /home/User/docbook-xml/4.0/dbgenent.ent f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.1.2       d     0 755
[14] file://localhost /home/User/docbook-xml/4.1.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.2         d     0 755
[14] file://localhost /home/User/docbook-xml/4.2/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.3         d     0 755
[14] file://localhost /home/User/docbook-xml/4.3/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml/4.4         d     0 755
[14] file://localhost /home/User/docbook-xml/4.4/dbgenent.mod f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat         f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[14] file://localhost /home/User/docbook-xml.cat.old     f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir                  [rm]
[ 1] file://localhost /home/User/subdir                  d     0 755
[ 4] file://localhost /home/User/subdir/testfile         [rm]
[ 1] file://localhost /home/User/subdir/testfile         f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 5] file://localhost /home/User/subdir/testfile1        [rm]
[ 1] file://localhost /home/User/subdir/testfile1        f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 5] file://localhost /home/User/subdir/testfile2        [rm]
[ 1] file://localhost /home/User/subdir/testfile2        f    12 644 285b35198a5e188b3a0df3ed33f93a26-0
[ 1] file://localhost /home/User/subdir-file             f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/subdirfile              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 1] file://localhost /home/User/test space              f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir                 [rm]
[ 1] file://localhost /home/User/testdir                 d     0 755
[16] file://localhost /home/User/testdir/biblio          [rm]
[14] file://localhost /home/User/testdir/biblio          d     0 755
[16] file://localhost /home/User/testdir/biblio/biblio.dbf [rm]
[14] file://localhost /home/User/testdir/biblio/biblio.dbf f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/biblio/biblio.dbt [rm]
[14] file://localhost /home/User/testdir/biblio/biblio.dbt f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/biblio.odb      [rm]
[14] file://localhost /home/User/testdir/biblio.odb      f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[16] file://localhost /home/User/testdir/evolocal.odb    [rm]
[14] file://localhost /home/User/testdir/evolocal.odb    f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[12] file://localhost /home/User/testfile                f    13 660 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile                f    13 644 59ca0efa9f5633cb0371bbc0355478d8-0
[ 1] file://localhost /home/User/testfile~               f     0 644 d41d8cd98f00b204e9800998ecf8427e-0
[ 7] file://localhost /home/User/testlink                [rm]
[ 6] file://localhost /home/User/testlink                l     8 777 testnull
[ 1] file://localhost /home/User/testlink                l     8 777 testfile
[11] file://localhost /home/User/testpipe                [rm]
[ 1] file://localhost /home/User/testpipe                p     0 644

Journal:
