Report tests

Default behaviour
default level
ALERT! alert level
Error: error level
Warning: warning level
info level

Verbosity level: alert
ALERT! alert level

Verbosity level: error
ALERT! alert level
Error: error level

Verbosity level: warning
ALERT! alert level
Error: error level
Warning: warning level

Verbosity level: info
default level
ALERT! alert level
Error: error level
Warning: warning level
info level

Verbosity level: verbose
default level
ALERT! alert level
Error: error level
Warning: warning level
info level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level

Verbosity level: debug
default level
ALERT! alert level
Error: error level
Warning: warning level
info level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level
debug level

End of tests
