Report tests

Default behaviour
default level
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level
info level
info 0 level
 -> info 1 level
 --> info 2 level

Verbosity level: alert
ALERT! alert level
ALERT! alert 0 level

Verbosity level: error
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level

Verbosity level: warning
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level

Verbosity level: info
default level
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level
info level
info 0 level
 -> info 1 level
 --> info 2 level

Verbosity level: verbose
default level
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level
info level
info 0 level
 -> info 1 level
 --> info 2 level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level

Verbosity level: debug
default level
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level
info level
info 0 level
 -> info 1 level
 --> info 2 level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level
debug level
debug 0 level
 -> debug 1 level
 --> debug 2 level

Line autoblanking
\r
Short line\r
A longer line\r
Tiny one     \r
.       \r
A longer line\r
An even longer line\r
A normal line      

End of tests
