Test: char (1)

Test: one reader

Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0

write: 123456
Buffer capacity = 10
Buffer usage = 6
Buffer empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 6

read: 3: 123
Buffer capacity = 10
Buffer usage = 3
Buffer empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 3

read: 3: 456
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

write: ABCD
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer full? no
Buffer writeable = 6
Buffer readable = 4

read: 3: ABC
Buffer capacity = 10
Buffer usage = 1
Buffer empty? no
Buffer full? no
Buffer writeable = 9
Buffer readable = 1

read: 1: D
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0

write: abcdefghij
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 10

read: 6: abcdef
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer full? no
Buffer writeable = 6
Buffer readable = 4

write: !@#$%^
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

wrote: 0
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

read: 10: ghij!@#$%^
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

read: 0: 
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

wrote: 10
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

wrote: 0
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

emptied
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0

Test: multiple readers

Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0
Buffer2 readable = 0

write: 123456
Buffer capacity = 10
Buffer usage = 6
Buffer empty? no
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 6
Buffer2 readable = 6

read: 3: 123
Buffer capacity = 10
Buffer usage = 6
Buffer empty? no
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 3
Buffer2 readable = 6

read2: 4: 1234
Buffer capacity = 10
Buffer usage = 3
Buffer empty? no
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 3
Buffer2 readable = 2

read: 3: 456
Buffer capacity = 10
Buffer usage = 2
Buffer empty? yes
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 2

read2: 2: 56
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 0

write: ABCD
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer2 empty? no
Buffer full? no
Buffer writeable = 6
Buffer readable = 4
Buffer2 readable = 4

read2: 4: ABCD
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 6
Buffer readable = 4
Buffer2 readable = 0

read: 3: ABC
Buffer capacity = 10
Buffer usage = 1
Buffer empty? no
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 9
Buffer readable = 1
Buffer2 readable = 0

read: 1: D
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0
Buffer2 readable = 0

write: abcdefghij
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 10
Buffer2 readable = 10

read: 6: abcdef
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 10

read2: 10: abcdefghij
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 6
Buffer readable = 4
Buffer2 readable = 0

write: !@#$%^
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 6

wrote: 0
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 6

read: 10: ghij!@#$%^
Buffer capacity = 10
Buffer usage = 6
Buffer empty? yes
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 6

read: 0: 
Buffer capacity = 10
Buffer usage = 6
Buffer empty? yes
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 6

read2: 6: !@#$%^
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 0

wrote: 10
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 4

wrote: 0
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 4

emptied
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0
Buffer2 readable = 0

Test: wchar_t (4)

Test: one reader

Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0

write: 123456
Buffer capacity = 10
Buffer usage = 6
Buffer empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 6

read: 3: 123
Buffer capacity = 10
Buffer usage = 3
Buffer empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 3

read: 3: 456
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

write: ABCD
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer full? no
Buffer writeable = 6
Buffer readable = 4

read: 3: ABC
Buffer capacity = 10
Buffer usage = 1
Buffer empty? no
Buffer full? no
Buffer writeable = 9
Buffer readable = 1

read: 1: D
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0

write: abcdefghij
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 10

read: 6: abcdef
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer full? no
Buffer writeable = 6
Buffer readable = 4

write: !@#$%^
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

wrote: 0
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

read: 10: ghij!@#$%^
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

read: 0: 
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0

wrote: 10
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

wrote: 0
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4

emptied
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0

Test: multiple readers

Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0
Buffer2 readable = 0

write: 123456
Buffer capacity = 10
Buffer usage = 6
Buffer empty? no
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 6
Buffer2 readable = 6

read: 3: 123
Buffer capacity = 10
Buffer usage = 6
Buffer empty? no
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 3
Buffer2 readable = 6

read2: 4: 1234
Buffer capacity = 10
Buffer usage = 3
Buffer empty? no
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 3
Buffer2 readable = 2

read: 3: 456
Buffer capacity = 10
Buffer usage = 2
Buffer empty? yes
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 2

read2: 2: 56
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 0

write: ABCD
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer2 empty? no
Buffer full? no
Buffer writeable = 6
Buffer readable = 4
Buffer2 readable = 4

read2: 4: ABCD
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 6
Buffer readable = 4
Buffer2 readable = 0

read: 3: ABC
Buffer capacity = 10
Buffer usage = 1
Buffer empty? no
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 9
Buffer readable = 1
Buffer2 readable = 0

read: 1: D
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0
Buffer2 readable = 0

write: abcdefghij
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 10
Buffer2 readable = 10

read: 6: abcdef
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 10

read2: 10: abcdefghij
Buffer capacity = 10
Buffer usage = 4
Buffer empty? no
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 6
Buffer readable = 4
Buffer2 readable = 0

write: !@#$%^
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 6

wrote: 0
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 6

read: 10: ghij!@#$%^
Buffer capacity = 10
Buffer usage = 6
Buffer empty? yes
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 6

read: 0: 
Buffer capacity = 10
Buffer usage = 6
Buffer empty? yes
Buffer2 empty? no
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 6

read2: 6: !@#$%^
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 4
Buffer readable = 0
Buffer2 readable = 0

wrote: 10
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 4

wrote: 0
Buffer capacity = 10
Buffer usage = 10
Buffer empty? no
Buffer2 empty? no
Buffer full? yes
Buffer writeable = 0
Buffer readable = 4
Buffer2 readable = 4

emptied
Buffer capacity = 10
Buffer usage = 0
Buffer empty? yes
Buffer2 empty? yes
Buffer full? no
Buffer writeable = 10
Buffer readable = 0
Buffer2 readable = 0
