
extractParams
readline(a): 0
a

readline( 	a 	b): 0
a
b

readline(	 ab): 0
ab

readline(	 ab cd): 0
ab
cd

readline(	 ab cd	ef # blah): 0
ab
cd
ef

readline(	 'ab' 'cd'	'ef' # blah): 0
ab
cd
ef

readline(	 "ab" 'cd'	"ef" # blah): 0
ab
cd
ef

readline(	 ab cd	ef 'gh ij	kl' "mn op	qr" 	# blah): 0
ab
cd
ef
gh ij	kl
mn op	qr

readline(	 ab cd	ef 'gh "ij\'	kl' "mn 'op\"	qr" 	# blah): 0
ab
cd
ef
gh "ij'	kl
mn 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr" 	# blah): 0
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl): 1
a\b
cd
ef
g\h "ij'	kl

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr): 1
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(path "C:\Backup\"): 1
path
C:\Backup"

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path
C:\Backup



and

spaces
matter


readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path

readline(		f	blah	''): 0


f
blah


readline(		f	blah	'): 1


f
blah


readline(		f	blah		): 0


f
blah




Test: client configuration
Syntax:
  expire, occ.: optional, max = 1; params: min = max = 1
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  path, occ.: min = 1, no max; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    ignore, occ.: optional, max = 1; params: min = max = 1
    no_compress, occ.: optional, max = 1; params: min = max = 1
    parser, occ.: optional, no max; params: min = 1, max = 2
  users, occ.: optional, max = 1; params: min = 1, no max
Test: with object
 0: root
 2:   filter and subdir
 3:     condition path_start subdir
 4:     condition !size< 100
 6:   users biloute machin
 8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Config:
2:   filter and subdir
3:     condition path_start subdir
4:     condition !size< 100
6:   users biloute machin
8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Test: server configuration
Syntax:
  client, occ.: min = 1, no max; params: min = 1, max = 2
    config, occ.: optional, max = 1; params: min = max = 1
    expire, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    hostname, occ.: optional, max = 1; params: min = max = 1
    ignore, occ.: optional, max = 1; params: min = max = 1
    option, occ.: optional, no max; params: min = 1, max = 2
    path, occ.: optional, no max; params: min = max = 1
      compress, occ.: optional, max = 1; params: min = max = 1
      filter, occ.: optional, no max; params: min = max = 2
        condition, occ.: min = 1, no max; params: min = max = 2
      ignore, occ.: optional, max = 1; params: min = max = 1
      no_compress, occ.: optional, max = 1; params: min = max = 1
      parser, occ.: optional, no max; params: min = 1, max = 2
    protocol, occ.: min = 1, max = 1; params: min = max = 1
    report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
    timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
    users, occ.: optional, max = 1; params: min = 1, no max
  db, occ.: optional, max = 1; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    compress_auto, occ.: optional, max = 1; params: min = max = 0
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  log, occ.: optional, max = 1; params: min = max = 1
    backups, occ.: optional, max = 1; params: min = max = 1
    level, occ.: optional, max = 1; params: min = max = 1
    max_lines, occ.: optional, max = 1; params: min = max = 1
  parsers_dir, occ.: optional, no max; params: min = max = 1
  report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
  timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
  tree, occ.: optional, max = 1; params: min = max = 1
    daily, occ.: optional, max = 1; params: min = max = 1
    hourly, occ.: optional, max = 1; params: min = max = 1
    links, occ.: optional, max = 1; params: min = max = 1
    weekly, occ.: optional, max = 1; params: min = max = 1
 0: root
 1:   log hbackup.log
 2:     max_lines 100000
 3:     backups 10
 4:     level verbose
 6:   db test_db
 7:     compress auto
 9:     compress_auto
11:   tree test_tree
12:     links symbolic
13:     hourly 23
14:     daily 6
15:     weekly 52
17:   parsers_dir ../../../parsers/.libs
19:   filter all nothing
20:     condition type pipe
21:     condition size> 10
23:   ignore nothing
25:   filter all backup
26:     condition type file
27:     condition path_end ~
29:   filter any test_or
30:     condition filter backup
31:     condition !size< 1000
33:   client myClient xp
34:     protocol smb
35:     users backup
36:     config C:\Backup\Backup.LST
38:   client myClient
39:     protocol nfs
40:     users backup root
41:     hostname myClient
42:     config /home/User/hbackup.list
44:   client newClient
45:     protocol ssh
46:     option username user
47:     option password p4sS?
48:     config /home/Blah/hbackup.list
50:   client other
51:     protocol none
52:     hostname otherClient
53:     option username foo
54:     option password bar
55:     config /home/Blah/hbackup.list
57:     filter and subdir
58:       condition path_start subdir
59:       condition !size< 100
61:     filter and bigfile
62:       condition size>= 10
63:       condition type file
65:     expire 1
67:     path test2//
69:     path test1
71:       filter and not_object
72:         condition !path_end .o
74:       filter or to_be_ignored
75:         condition filter subdir
76:         condition filter backup
77:         condition !filter not_object
79:       ignore to_be_ignored
81:       compress bigfile
83:       parser cvs controlled
84:       parser svn modified
86:   client myhost
87:     report_copy_error_once
88:     protocol file
89:     hostname myhost.mynetwork.lan
90:     timeout_nowarning
91:     config etc/localhost.list
92:     expire 1
94:   client client xp
95:     ignore backup
96:     protocol smb
97:     option username Myself
98:     option password flesyM
99:     option nocase
100:     hostname myClient
101:     config C:\Backup\Backup.LST
103:   client aClient vista
104:     protocol smb
105:     filter and huge_file
106:       condition !filter backup
107:       condition !size< 100
109:     path C:\Test Dir
110:       filter and compress_m
111:         condition !filter huge_file
112:       compress compress_m
113:       ignore backup
114:       parser svn modified
115:     report_copy_error_once
Config:
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
6:   db test_db
7:     compress auto
9:     compress_auto
11:   tree test_tree
12:     links symbolic
13:     hourly 23
14:     daily 6
15:     weekly 52
17:   parsers_dir ../../../parsers/.libs
19:   filter all nothing
20:     condition type pipe
21:     condition size> 10
23:   ignore nothing
25:   filter all backup
26:     condition type file
27:     condition path_end ~
29:   filter any test_or
30:     condition filter backup
31:     condition !size< 1000
33:   client myClient xp
34:     protocol smb
35:     users backup
36:     config C:\Backup\Backup.LST
38:   client myClient
39:     protocol nfs
40:     users backup root
41:     hostname myClient
42:     config /home/User/hbackup.list
44:   client newClient
45:     protocol ssh
46:     option username user
47:     option password p4sS?
48:     config /home/Blah/hbackup.list
50:   client other
51:     protocol none
52:     hostname otherClient
53:     option username foo
54:     option password bar
55:     config /home/Blah/hbackup.list
57:     filter and subdir
58:       condition path_start subdir
59:       condition !size< 100
61:     filter and bigfile
62:       condition size>= 10
63:       condition type file
65:     expire 1
67:     path test2//
69:     path test1
71:       filter and not_object
72:         condition !path_end .o
74:       filter or to_be_ignored
75:         condition filter subdir
76:         condition filter backup
77:         condition !filter not_object
79:       ignore to_be_ignored
81:       compress bigfile
83:       parser cvs controlled
84:       parser svn modified
86:   client myhost
87:     report_copy_error_once
88:     protocol file
89:     hostname myhost.mynetwork.lan
90:     timeout_nowarning
91:     config etc/localhost.list
92:     expire 1
94:   client client xp
95:     ignore backup
96:     protocol smb
97:     option username Myself
98:     option password flesyM
99:     option nocase
100:     hostname myClient
101:     config C:\Backup\Backup.LST
103:   client aClient vista
104:     protocol smb
105:     filter and huge_file
106:       condition !filter backup
107:       condition !size< 100
109:     path C:\Test Dir
110:       filter and compress_m
111:         condition !filter huge_file
112:       compress compress_m
113:       ignore backup
114:       parser svn modified
115:     report_copy_error_once
Test: configuration save
 0: root
 1:   log hbackup.log
 2:     max_lines 100000
 3:     backups 10
 4:     level verbose
 5:   db test_db
 6:     compress auto
 7:     compress_auto
 8:   tree test_tree
 9:     links symbolic
10:     hourly 23
11:     daily 6
12:     weekly 52
13:   parsers_dir ../../../parsers/.libs
14:   filter all nothing
15:     condition type pipe
16:     condition size> 10
17:   ignore nothing
18:   filter all backup
19:     condition type file
20:     condition path_end ~
21:   filter any test_or
22:     condition filter backup
23:     condition !size< 1000
24:   client myClient xp
25:     protocol smb
26:     users backup
27:     config C:\Backup\Backup.LST
28:   client myClient
29:     protocol nfs
30:     users backup root
31:     hostname myClient
32:     config /home/User/hbackup.list
33:   client newClient
34:     protocol ssh
35:     option username user
36:     option password p4sS?
37:     config /home/Blah/hbackup.list
38:   client other
39:     protocol none
40:     hostname otherClient
41:     option username foo
42:     option password bar
43:     config /home/Blah/hbackup.list
44:     filter and subdir
45:       condition path_start subdir
46:       condition !size< 100
47:     filter and bigfile
48:       condition size>= 10
49:       condition type file
50:     expire 1
51:     path test2//
52:     path test1
53:       filter and not_object
54:         condition !path_end .o
55:       filter or to_be_ignored
56:         condition filter subdir
57:         condition filter backup
58:         condition !filter not_object
59:       ignore to_be_ignored
60:       compress bigfile
61:       parser cvs controlled
62:       parser svn modified
63:   client myhost
64:     report_copy_error_once
65:     protocol file
66:     hostname myhost.mynetwork.lan
67:     timeout_nowarning
68:     config etc/localhost.list
69:     expire 1
70:   client client xp
71:     ignore backup
72:     protocol smb
73:     option username Myself
74:     option password flesyM
75:     option nocase
76:     hostname myClient
77:     config C:\Backup\Backup.LST
78:   client aClient vista
79:     protocol smb
80:     filter and huge_file
81:       condition !filter backup
82:       condition !size< 100
83:     path C:\Test Dir
84:       filter and compress_m
85:         condition !filter huge_file
86:       compress compress_m
87:       ignore backup
88:       parser svn modified
89:     report_copy_error_once
Config:
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
5:   db test_db
6:     compress auto
7:     compress_auto
8:   tree test_tree
9:     links symbolic
10:     hourly 23
11:     daily 6
12:     weekly 52
13:   parsers_dir ../../../parsers/.libs
14:   filter all nothing
15:     condition type pipe
16:     condition size> 10
17:   ignore nothing
18:   filter all backup
19:     condition type file
20:     condition path_end ~
21:   filter any test_or
22:     condition filter backup
23:     condition !size< 1000
24:   client myClient xp
25:     protocol smb
26:     users backup
27:     config C:\Backup\Backup.LST
28:   client myClient
29:     protocol nfs
30:     users backup root
31:     hostname myClient
32:     config /home/User/hbackup.list
33:   client newClient
34:     protocol ssh
35:     option username user
36:     option password p4sS?
37:     config /home/Blah/hbackup.list
38:   client other
39:     protocol none
40:     hostname otherClient
41:     option username foo
42:     option password bar
43:     config /home/Blah/hbackup.list
44:     filter and subdir
45:       condition path_start subdir
46:       condition !size< 100
47:     filter and bigfile
48:       condition size>= 10
49:       condition type file
50:     expire 1
51:     path test2//
52:     path test1
53:       filter and not_object
54:         condition !path_end .o
55:       filter or to_be_ignored
56:         condition filter subdir
57:         condition filter backup
58:         condition !filter not_object
59:       ignore to_be_ignored
60:       compress bigfile
61:       parser cvs controlled
62:       parser svn modified
63:   client myhost
64:     report_copy_error_once
65:     protocol file
66:     hostname myhost.mynetwork.lan
67:     timeout_nowarning
68:     config etc/localhost.list
69:     expire 1
70:   client client xp
71:     ignore backup
72:     protocol smb
73:     option username Myself
74:     option password flesyM
75:     option nocase
76:     hostname myClient
77:     config C:\Backup\Backup.LST
78:   client aClient vista
79:     protocol smb
80:     filter and huge_file
81:       condition !filter backup
82:       condition !size< 100
83:     path C:\Test Dir
84:       filter and compress_m
85:         condition !filter huge_file
86:       compress compress_m
87:       ignore backup
88:       parser svn modified
89:     report_copy_error_once
Test: broken configuration
failed to read config!
Error: after line 0: need at most 1 occurence(s) of keyword 'db'
Error: after line 0: need at most 1 occurence(s) of keyword 'report_copy_error_once'
Error: at line 7: keyword 'filter' requires 2 parameter(s), found 1
Error: after line 11: missing keyword 'condition'
Error: after line 13: need at most 1 occurence(s) of keyword 'ignore'
Error: at line 15: keyword 'users' requires at least 1 parameter(s), found 0
Error: at line 17: keyword 'ignore' requires 1 parameter(s), found 0
Error: after line 19: need at most 1 occurence(s) of keyword 'config'
Error: after line 19: need at most 1 occurence(s) of keyword 'expire'
Error: after line 19: need at most 1 occurence(s) of keyword 'hostname'
Error: at line 23: keyword 'option' requires at most 2 parameter(s), found 3
Error: at line 24: keyword 'option' requires at least 1 parameter(s), found 0
Error: at line 32: keyword 'filter' requires 2 parameter(s), found 3
Error: at line 33: keyword 'condition' requires 2 parameter(s), found 3
Error: at line 34: keyword 'condition' requires 2 parameter(s), found 1
Error: at line 37: keyword 'expire' requires 1 parameter(s), found 2
Error: after line 41: need at most 1 occurence(s) of keyword 'compress'
Error: after line 41: need at most 1 occurence(s) of keyword 'ignore'
Error: after line 51: missing keyword 'condition'
Error: at line 53: keyword 'filter' requires 2 parameter(s), found 1
Error: after line 53: missing keyword 'condition'
Error: after line 65: missing keyword 'protocol'
Error: at line 71: keyword 'ignore' requires 1 parameter(s), found 2
Error: at line 72: keyword 'compress' requires 1 parameter(s), found 2
Error: at line 85: keyword 'ignore' requires 1 parameter(s), found 0
Error: at line 86: keyword 'compress' requires 1 parameter(s), found 0
Error: at line 88: keyword 'what_the_f...?' incorrect or misplaced, aborting
 0: root
 1:   db test_db
 2:   db blah
 4:   report_copy_error_once
 5:   report_copy_error_once
Config:
1:   db test_db
2:   db blah
4:   report_copy_error_once
5:   report_copy_error_once
7:   filter all
8:     condition type file
9:     condition path_end ~
11:   filter any test_or
13:   client myClient
14:     protocol nfs
15:     users
16:     ignore test_or
17:     ignore
19:   client other
20:     protocol ssh
21:     hostname otherClient
22:     hostname 192.168.0.132
23:     option I am happy
24:     option
25:     config /home/backup/Backup.list
26:     config /home/backup/Backup2.list
28:     filter and subdir
29:       condition path_start subdir
30:       condition !size< 100
32:     filter and bigfile 3
33:       condition size>= 10 yeah
34:       condition type
36:     expire 1
37:     expire 2 3
39:     path test2//
41:     path test1
43:       filter and not_object
44:         condition !path_end .o
46:       filter or to_be_ignored
47:         condition filter subdir
48:         condition filter backup
49:         condition !filter not_object
51:       filter and blah
53:       filter or
56:       ignore to_be_ignored
57:       ignore to_be_ignored2
59:       compress bigfile
60:       compress bigfile2
62:       parser cvs controlled
63:       parser svn modified
65:   client myhost
66:     hostname myhost.mynetwork.lan
67:     config etc/localhost.list
68:     expire 1
70:     path blah
71:       ignore 2 3
72:       compress 4 5
74:   client client xp
75:     protocol smb
76:     option username Myself
77:     option password flesyM
78:     option nocase
79:     hostname myClient
80:     config C:\Backup\Backup.LST
82:     path C:\Crash"
83:     path C:\Crash
84:     path blah
85:       ignore
86:       compress
