
extractParams
readline(a): 0
a

readline( 	a 	b): 0
a
b

readline(	 ab): 0
ab

readline(	 ab cd): 0
ab
cd

readline(	 ab cd	ef # blah): 0
ab
cd
ef

readline(	 'ab' 'cd'	'ef' # blah): 0
ab
cd
ef

readline(	 "ab" 'cd'	"ef" # blah): 0
ab
cd
ef

readline(	 ab cd	ef 'gh ij	kl' "mn op	qr" 	# blah): 0
ab
cd
ef
gh ij	kl
mn op	qr

readline(	 ab cd	ef 'gh "ij\'	kl' "mn 'op\"	qr" 	# blah): 0
ab
cd
ef
gh "ij'	kl
mn 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr" 	# blah): 0
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl): 1
a\b
cd
ef
g\h "ij'	kl

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr): 1
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(path "C:\Backup\"): 1
path
C:\Backup"

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path
C:\Backup



and

spaces
matter


readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path

readline(		f	blah	''): 0


f
blah


readline(		f	blah	'): 1


f
blah


readline(		f	blah		): 0


f
blah




Test: client configuration
Syntax:
  expire, occ.: optional, max = 1; params: min = max = 1
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  path, occ.: min = 1, no max; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    ignore, occ.: optional, max = 1; params: min = max = 1
    no_compress, occ.: optional, max = 1; params: min = max = 1
    parser, occ.: optional, no max; params: min = 1, max = 2
  users, occ.: optional, max = 1; params: min = 1, no max
Test: with object
 0: root
 2:   filter and subdir
 3:     condition path_start subdir
 4:     condition !size< 100
 6:   users biloute machin
 8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Config:
2:   filter and subdir
3:     condition path_start subdir
4:     condition !size< 100
6:   users biloute machin
8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Test: server configuration
Syntax:
  client, occ.: min = 1, no max; params: min = 1, max = 2
    config, occ.: optional, max = 1; params: min = max = 1
    expire, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    hostname, occ.: optional, max = 1; params: min = max = 1
    ignore, occ.: optional, max = 1; params: min = max = 1
    option, occ.: optional, no max; params: min = 1, max = 2
    path, occ.: optional, no max; params: min = max = 1
      compress, occ.: optional, max = 1; params: min = max = 1
      filter, occ.: optional, no max; params: min = max = 2
        condition, occ.: min = 1, no max; params: min = max = 2
      ignore, occ.: optional, max = 1; params: min = max = 1
      no_compress, occ.: optional, max = 1; params: min = max = 1
      parser, occ.: optional, no max; params: min = 1, max = 2
    protocol, occ.: min = 1, max = 1; params: min = max = 1
    report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
    timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
    users, occ.: optional, max = 1; params: min = 1, no max
  db, occ.: optional, max = 1; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    compress_auto, occ.: optional, max = 1; params: min = max = 0
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  log, occ.: optional, max = 1; params: min = max = 1
    backups, occ.: optional, max = 1; params: min = max = 1
    level, occ.: optional, max = 1; params: min = max = 1
    max_lines, occ.: optional, max = 1; params: min = max = 1
  parsers_dir, occ.: optional, no max; params: min = max = 1
  report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
  timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
  tree, occ.: optional, max = 1; params: min = max = 1
    daily, occ.: optional, max = 1; params: min = max = 1
    hourly, occ.: optional, max = 1; params: min = max = 1
    weekly, occ.: optional, max = 1; params: min = max = 1
 0: root
 1:   log hbackup.log
 2:     max_lines 100000
 3:     backups 10
 4:     level verbose
 6:   db test_db
 7:     compress auto
 9:     compress_auto
11:   tree test_tree
12:     hourly 23
13:     daily 6
14:     weekly 52
16:   parsers_dir ../../../parsers/.libs
18:   filter all nothing
19:     condition type pipe
20:     condition size> 10
22:   ignore nothing
24:   filter all backup
25:     condition type file
26:     condition path_end ~
28:   filter any test_or
29:     condition filter backup
30:     condition !size< 1000
32:   client myClient xp
33:     protocol smb
34:     users backup
35:     config C:\Backup\Backup.LST
37:   client myClient
38:     protocol nfs
39:     users backup root
40:     hostname myClient
41:     config /home/User/hbackup.list
43:   client newClient
44:     protocol ssh
45:     option username user
46:     option password p4sS?
47:     config /home/Blah/hbackup.list
49:   client other
50:     protocol none
51:     hostname otherClient
52:     option username foo
53:     option password bar
54:     config /home/Blah/hbackup.list
56:     filter and subdir
57:       condition path_start subdir
58:       condition !size< 100
60:     filter and bigfile
61:       condition size>= 10
62:       condition type file
64:     expire 1
66:     path test2//
68:     path test1
70:       filter and not_object
71:         condition !path_end .o
73:       filter or to_be_ignored
74:         condition filter subdir
75:         condition filter backup
76:         condition !filter not_object
78:       ignore to_be_ignored
80:       compress bigfile
82:       parser cvs controlled
83:       parser svn modified
85:   client myhost
86:     report_copy_error_once
87:     protocol file
88:     hostname myhost.mynetwork.lan
89:     timeout_nowarning
90:     config etc/localhost.list
91:     expire 1
93:   client client xp
94:     ignore backup
95:     protocol smb
96:     option username Myself
97:     option password flesyM
98:     option nocase
99:     hostname myClient
100:     config C:\Backup\Backup.LST
102:   client aClient vista
103:     protocol smb
104:     filter and huge_file
105:       condition !filter backup
106:       condition !size< 100
108:     path C:\Test Dir
109:       filter and compress_m
110:         condition !filter huge_file
111:       compress compress_m
112:       ignore backup
113:       parser svn modified
114:     report_copy_error_once
Config:
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
6:   db test_db
7:     compress auto
9:     compress_auto
11:   tree test_tree
12:     hourly 23
13:     daily 6
14:     weekly 52
16:   parsers_dir ../../../parsers/.libs
18:   filter all nothing
19:     condition type pipe
20:     condition size> 10
22:   ignore nothing
24:   filter all backup
25:     condition type file
26:     condition path_end ~
28:   filter any test_or
29:     condition filter backup
30:     condition !size< 1000
32:   client myClient xp
33:     protocol smb
34:     users backup
35:     config C:\Backup\Backup.LST
37:   client myClient
38:     protocol nfs
39:     users backup root
40:     hostname myClient
41:     config /home/User/hbackup.list
43:   client newClient
44:     protocol ssh
45:     option username user
46:     option password p4sS?
47:     config /home/Blah/hbackup.list
49:   client other
50:     protocol none
51:     hostname otherClient
52:     option username foo
53:     option password bar
54:     config /home/Blah/hbackup.list
56:     filter and subdir
57:       condition path_start subdir
58:       condition !size< 100
60:     filter and bigfile
61:       condition size>= 10
62:       condition type file
64:     expire 1
66:     path test2//
68:     path test1
70:       filter and not_object
71:         condition !path_end .o
73:       filter or to_be_ignored
74:         condition filter subdir
75:         condition filter backup
76:         condition !filter not_object
78:       ignore to_be_ignored
80:       compress bigfile
82:       parser cvs controlled
83:       parser svn modified
85:   client myhost
86:     report_copy_error_once
87:     protocol file
88:     hostname myhost.mynetwork.lan
89:     timeout_nowarning
90:     config etc/localhost.list
91:     expire 1
93:   client client xp
94:     ignore backup
95:     protocol smb
96:     option username Myself
97:     option password flesyM
98:     option nocase
99:     hostname myClient
100:     config C:\Backup\Backup.LST
102:   client aClient vista
103:     protocol smb
104:     filter and huge_file
105:       condition !filter backup
106:       condition !size< 100
108:     path C:\Test Dir
109:       filter and compress_m
110:         condition !filter huge_file
111:       compress compress_m
112:       ignore backup
113:       parser svn modified
114:     report_copy_error_once
Test: configuration save
 0: root
 1:   log hbackup.log
 2:     max_lines 100000
 3:     backups 10
 4:     level verbose
 5:   db test_db
 6:     compress auto
 7:     compress_auto
 8:   tree test_tree
 9:     hourly 23
10:     daily 6
11:     weekly 52
12:   parsers_dir ../../../parsers/.libs
13:   filter all nothing
14:     condition type pipe
15:     condition size> 10
16:   ignore nothing
17:   filter all backup
18:     condition type file
19:     condition path_end ~
20:   filter any test_or
21:     condition filter backup
22:     condition !size< 1000
23:   client myClient xp
24:     protocol smb
25:     users backup
26:     config C:\Backup\Backup.LST
27:   client myClient
28:     protocol nfs
29:     users backup root
30:     hostname myClient
31:     config /home/User/hbackup.list
32:   client newClient
33:     protocol ssh
34:     option username user
35:     option password p4sS?
36:     config /home/Blah/hbackup.list
37:   client other
38:     protocol none
39:     hostname otherClient
40:     option username foo
41:     option password bar
42:     config /home/Blah/hbackup.list
43:     filter and subdir
44:       condition path_start subdir
45:       condition !size< 100
46:     filter and bigfile
47:       condition size>= 10
48:       condition type file
49:     expire 1
50:     path test2//
51:     path test1
52:       filter and not_object
53:         condition !path_end .o
54:       filter or to_be_ignored
55:         condition filter subdir
56:         condition filter backup
57:         condition !filter not_object
58:       ignore to_be_ignored
59:       compress bigfile
60:       parser cvs controlled
61:       parser svn modified
62:   client myhost
63:     report_copy_error_once
64:     protocol file
65:     hostname myhost.mynetwork.lan
66:     timeout_nowarning
67:     config etc/localhost.list
68:     expire 1
69:   client client xp
70:     ignore backup
71:     protocol smb
72:     option username Myself
73:     option password flesyM
74:     option nocase
75:     hostname myClient
76:     config C:\Backup\Backup.LST
77:   client aClient vista
78:     protocol smb
79:     filter and huge_file
80:       condition !filter backup
81:       condition !size< 100
82:     path C:\Test Dir
83:       filter and compress_m
84:         condition !filter huge_file
85:       compress compress_m
86:       ignore backup
87:       parser svn modified
88:     report_copy_error_once
Config:
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
5:   db test_db
6:     compress auto
7:     compress_auto
8:   tree test_tree
9:     hourly 23
10:     daily 6
11:     weekly 52
12:   parsers_dir ../../../parsers/.libs
13:   filter all nothing
14:     condition type pipe
15:     condition size> 10
16:   ignore nothing
17:   filter all backup
18:     condition type file
19:     condition path_end ~
20:   filter any test_or
21:     condition filter backup
22:     condition !size< 1000
23:   client myClient xp
24:     protocol smb
25:     users backup
26:     config C:\Backup\Backup.LST
27:   client myClient
28:     protocol nfs
29:     users backup root
30:     hostname myClient
31:     config /home/User/hbackup.list
32:   client newClient
33:     protocol ssh
34:     option username user
35:     option password p4sS?
36:     config /home/Blah/hbackup.list
37:   client other
38:     protocol none
39:     hostname otherClient
40:     option username foo
41:     option password bar
42:     config /home/Blah/hbackup.list
43:     filter and subdir
44:       condition path_start subdir
45:       condition !size< 100
46:     filter and bigfile
47:       condition size>= 10
48:       condition type file
49:     expire 1
50:     path test2//
51:     path test1
52:       filter and not_object
53:         condition !path_end .o
54:       filter or to_be_ignored
55:         condition filter subdir
56:         condition filter backup
57:         condition !filter not_object
58:       ignore to_be_ignored
59:       compress bigfile
60:       parser cvs controlled
61:       parser svn modified
62:   client myhost
63:     report_copy_error_once
64:     protocol file
65:     hostname myhost.mynetwork.lan
66:     timeout_nowarning
67:     config etc/localhost.list
68:     expire 1
69:   client client xp
70:     ignore backup
71:     protocol smb
72:     option username Myself
73:     option password flesyM
74:     option nocase
75:     hostname myClient
76:     config C:\Backup\Backup.LST
77:   client aClient vista
78:     protocol smb
79:     filter and huge_file
80:       condition !filter backup
81:       condition !size< 100
82:     path C:\Test Dir
83:       filter and compress_m
84:         condition !filter huge_file
85:       compress compress_m
86:       ignore backup
87:       parser svn modified
88:     report_copy_error_once
Test: broken configuration
failed to read config!
Error: after line 0: need at most 1 occurence(s) of keyword 'db'
Error: after line 0: need at most 1 occurence(s) of keyword 'report_copy_error_once'
Error: at line 7: keyword 'filter' requires 2 parameter(s), found 1
Error: after line 11: missing keyword 'condition'
Error: after line 13: need at most 1 occurence(s) of keyword 'ignore'
Error: at line 15: keyword 'users' requires at least 1 parameter(s), found 0
Error: at line 17: keyword 'ignore' requires 1 parameter(s), found 0
Error: after line 19: need at most 1 occurence(s) of keyword 'config'
Error: after line 19: need at most 1 occurence(s) of keyword 'expire'
Error: after line 19: need at most 1 occurence(s) of keyword 'hostname'
Error: at line 23: keyword 'option' requires at most 2 parameter(s), found 3
Error: at line 24: keyword 'option' requires at least 1 parameter(s), found 0
Error: at line 32: keyword 'filter' requires 2 parameter(s), found 3
Error: at line 33: keyword 'condition' requires 2 parameter(s), found 3
Error: at line 34: keyword 'condition' requires 2 parameter(s), found 1
Error: at line 37: keyword 'expire' requires 1 parameter(s), found 2
Error: after line 41: need at most 1 occurence(s) of keyword 'compress'
Error: after line 41: need at most 1 occurence(s) of keyword 'ignore'
Error: after line 51: missing keyword 'condition'
Error: at line 53: keyword 'filter' requires 2 parameter(s), found 1
Error: after line 53: missing keyword 'condition'
Error: after line 65: missing keyword 'protocol'
Error: at line 71: keyword 'ignore' requires 1 parameter(s), found 2
Error: at line 72: keyword 'compress' requires 1 parameter(s), found 2
Error: at line 85: keyword 'ignore' requires 1 parameter(s), found 0
Error: at line 86: keyword 'compress' requires 1 parameter(s), found 0
Error: at line 88: keyword 'what_the_f...?' incorrect or misplaced, aborting
 0: root
 1:   db test_db
 2:   db blah
 4:   report_copy_error_once
 5:   report_copy_error_once
Config:
1:   db test_db
2:   db blah
4:   report_copy_error_once
5:   report_copy_error_once
7:   filter all
8:     condition type file
9:     condition path_end ~
11:   filter any test_or
13:   client myClient
14:     protocol nfs
15:     users
16:     ignore test_or
17:     ignore
19:   client other
20:     protocol ssh
21:     hostname otherClient
22:     hostname 192.168.0.132
23:     option I am happy
24:     option
25:     config /home/backup/Backup.list
26:     config /home/backup/Backup2.list
28:     filter and subdir
29:       condition path_start subdir
30:       condition !size< 100
32:     filter and bigfile 3
33:       condition size>= 10 yeah
34:       condition type
36:     expire 1
37:     expire 2 3
39:     path test2//
41:     path test1
43:       filter and not_object
44:         condition !path_end .o
46:       filter or to_be_ignored
47:         condition filter subdir
48:         condition filter backup
49:         condition !filter not_object
51:       filter and blah
53:       filter or
56:       ignore to_be_ignored
57:       ignore to_be_ignored2
59:       compress bigfile
60:       compress bigfile2
62:       parser cvs controlled
63:       parser svn modified
65:   client myhost
66:     hostname myhost.mynetwork.lan
67:     config etc/localhost.list
68:     expire 1
70:     path blah
71:       ignore 2 3
72:       compress 4 5
74:   client client xp
75:     protocol smb
76:     option username Myself
77:     option password flesyM
78:     option nocase
79:     hostname myClient
80:     config C:\Backup\Backup.LST
82:     path C:\Crash"
83:     path C:\Crash
84:     path blah
85:       ignore
86:       compress
