
extractParams
readline(a): 0
a

readline( 	a 	b): 0
a
b

readline(	 ab): 0
ab

readline(	 ab cd): 0
ab
cd

readline(	 ab cd	ef # blah): 0
ab
cd
ef

readline(	 'ab' 'cd'	'ef' # blah): 0
ab
cd
ef

readline(	 "ab" 'cd'	"ef" # blah): 0
ab
cd
ef

readline(	 ab cd	ef 'gh ij	kl' "mn op	qr" 	# blah): 0
ab
cd
ef
gh ij	kl
mn op	qr

readline(	 ab cd	ef 'gh "ij\'	kl' "mn 'op\"	qr" 	# blah): 0
ab
cd
ef
gh "ij'	kl
mn 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr" 	# blah): 0
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(	 a\b cd	ef 'g\h "ij\'	kl): 1
a\b
cd
ef
g\h "ij'	kl

readline(	 a\b cd	ef 'g\h "ij\'	kl' "m\n 'op\"	qr): 1
a\b
cd
ef
g\h "ij'	kl
m\n 'op"	qr

readline(path "C:\Backup\"): 1
path
C:\Backup"

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline(path "C:\Backup\"): 0
path
C:\Backup\

readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path
C:\Backup



and

spaces
matter


readline( this is a path "C:\Backup"   and  spaces matter ): 0

this
is
a
path

readline(		f	blah	''): 0


f
blah


readline(		f	blah	'): 1


f
blah


readline(		f	blah		): 0


f
blah




Test: client configuration
Syntax:
  expire, occ.: optional, max = 1; params: min = max = 1
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  path, occ.: min = 1, no max; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    ignore, occ.: optional, max = 1; params: min = max = 1
    no_compress, occ.: optional, max = 1; params: min = max = 1
    parser, occ.: optional, no max; params: min = 1, max = 2
  users, occ.: optional, max = 1; params: min = 1, no max
Test: with object
0: root
2:   filter and subdir
3:     condition path_start subdir
4:     condition !size< 100
6:   users biloute machin
8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Config:
2:   filter and subdir
3:     condition path_start subdir
4:     condition !size< 100
6:   users biloute machin
8:   ignore backup
10:   filter and bigfile
11:     condition size>= 10
12:     condition type file
14:   expire 1
16:   path test2//
18:   path test1
20:     filter and not_object
21:       condition !path_end .o
23:     filter or to_be_ignored
24:       condition filter subdir
25:       condition !filter not_object
27:     ignore to_be_ignored
29:     compress bigfile
31:     parser cvs controlled
32:     parser svn modified
34:     filter and cvs_entries
35:       condition name Entries
37:     no_compress cvs_entries
Test: server configuration
Syntax:
  client, occ.: min = 1, no max; params: min = 1, max = 2
    config, occ.: optional, max = 1; params: min = max = 1
    expire, occ.: optional, max = 1; params: min = max = 1
    filter, occ.: optional, no max; params: min = max = 2
      condition, occ.: min = 1, no max; params: min = max = 2
    hostname, occ.: optional, max = 1; params: min = max = 1
    ignore, occ.: optional, max = 1; params: min = max = 1
    option, occ.: optional, no max; params: min = 1, max = 2
    path, occ.: optional, no max; params: min = max = 1
      compress, occ.: optional, max = 1; params: min = max = 1
      filter, occ.: optional, no max; params: min = max = 2
        condition, occ.: min = 1, no max; params: min = max = 2
      ignore, occ.: optional, max = 1; params: min = max = 1
      no_compress, occ.: optional, max = 1; params: min = max = 1
      parser, occ.: optional, no max; params: min = 1, max = 2
    protocol, occ.: min = 1, max = 1; params: min = max = 1
    report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
    timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
    users, occ.: optional, max = 1; params: min = 1, no max
  db, occ.: optional, max = 1; params: min = max = 1
    compress, occ.: optional, max = 1; params: min = max = 1
    compress_auto, occ.: optional, max = 1; params: min = max = 0
  filter, occ.: optional, no max; params: min = max = 2
    condition, occ.: min = 1, no max; params: min = max = 2
  ignore, occ.: optional, max = 1; params: min = max = 1
  log, occ.: optional, max = 1; params: min = max = 1
    backups, occ.: optional, max = 1; params: min = max = 1
    level, occ.: optional, max = 1; params: min = max = 1
    max_lines, occ.: optional, max = 1; params: min = max = 1
  parsers_dir, occ.: optional, no max; params: min = max = 1
  report_copy_error_once, occ.: optional, max = 1; params: min = max = 0
  timeout_nowarning, occ.: optional, max = 1; params: min = max = 0
0: root
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
5:   db test_db
6:     compress auto
8:     compress_auto
10:   parsers_dir ../../../parsers/.libs
12:   filter all nothing
13:     condition type pipe
14:     condition size> 10
16:   ignore nothing
18:   filter all backup
19:     condition type file
20:     condition path_end ~
22:   filter any test_or
23:     condition filter backup
24:     condition !size< 1000
26:   client myClient xp
27:     protocol smb
28:     users backup
29:     config C:\Backup\Backup.LST
31:   client myClient
32:     protocol nfs
33:     users backup root
34:     hostname myClient
35:     config /home/User/hbackup.list
37:   client newClient
38:     protocol ssh
39:     option username user
40:     option password p4sS?
41:     config /home/Blah/hbackup.list
43:   client other
44:     protocol none
45:     hostname otherClient
46:     option username foo
47:     option password bar
48:     config /home/Blah/hbackup.list
50:     filter and subdir
51:       condition path_start subdir
52:       condition !size< 100
54:     filter and bigfile
55:       condition size>= 10
56:       condition type file
58:     expire 1
60:     path test2//
62:     path test1
64:       filter and not_object
65:         condition !path_end .o
67:       filter or to_be_ignored
68:         condition filter subdir
69:         condition filter backup
70:         condition !filter not_object
72:       ignore to_be_ignored
74:       compress bigfile
76:       parser cvs controlled
77:       parser svn modified
79:   client myhost
80:     report_copy_error_once
81:     protocol file
82:     hostname myhost.mynetwork.lan
83:     timeout_nowarning
84:     config etc/localhost.list
85:     expire 1
87:   client client xp
88:     ignore backup
89:     protocol smb
90:     option username Myself
91:     option password flesyM
92:     option nocase
93:     hostname myClient
94:     config C:\Backup\Backup.LST
96:   client aClient vista
97:     protocol smb
98:     filter and huge_file
99:       condition !filter backup
100:       condition !size< 100
102:     path C:\Test Dir
103:       filter and compress_m
104:         condition !filter huge_file
105:       compress compress_m
106:       ignore backup
107:       parser svn modified
108:     report_copy_error_once
Config:
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
5:   db test_db
6:     compress auto
8:     compress_auto
10:   parsers_dir ../../../parsers/.libs
12:   filter all nothing
13:     condition type pipe
14:     condition size> 10
16:   ignore nothing
18:   filter all backup
19:     condition type file
20:     condition path_end ~
22:   filter any test_or
23:     condition filter backup
24:     condition !size< 1000
26:   client myClient xp
27:     protocol smb
28:     users backup
29:     config C:\Backup\Backup.LST
31:   client myClient
32:     protocol nfs
33:     users backup root
34:     hostname myClient
35:     config /home/User/hbackup.list
37:   client newClient
38:     protocol ssh
39:     option username user
40:     option password p4sS?
41:     config /home/Blah/hbackup.list
43:   client other
44:     protocol none
45:     hostname otherClient
46:     option username foo
47:     option password bar
48:     config /home/Blah/hbackup.list
50:     filter and subdir
51:       condition path_start subdir
52:       condition !size< 100
54:     filter and bigfile
55:       condition size>= 10
56:       condition type file
58:     expire 1
60:     path test2//
62:     path test1
64:       filter and not_object
65:         condition !path_end .o
67:       filter or to_be_ignored
68:         condition filter subdir
69:         condition filter backup
70:         condition !filter not_object
72:       ignore to_be_ignored
74:       compress bigfile
76:       parser cvs controlled
77:       parser svn modified
79:   client myhost
80:     report_copy_error_once
81:     protocol file
82:     hostname myhost.mynetwork.lan
83:     timeout_nowarning
84:     config etc/localhost.list
85:     expire 1
87:   client client xp
88:     ignore backup
89:     protocol smb
90:     option username Myself
91:     option password flesyM
92:     option nocase
93:     hostname myClient
94:     config C:\Backup\Backup.LST
96:   client aClient vista
97:     protocol smb
98:     filter and huge_file
99:       condition !filter backup
100:       condition !size< 100
102:     path C:\Test Dir
103:       filter and compress_m
104:         condition !filter huge_file
105:       compress compress_m
106:       ignore backup
107:       parser svn modified
108:     report_copy_error_once
Test: configuration save
0: root
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
5:   db test_db
6:     compress auto
7:     compress_auto
8:   parsers_dir ../../../parsers/.libs
9:   filter all nothing
10:     condition type pipe
11:     condition size> 10
12:   ignore nothing
13:   filter all backup
14:     condition type file
15:     condition path_end ~
16:   filter any test_or
17:     condition filter backup
18:     condition !size< 1000
19:   client myClient xp
20:     protocol smb
21:     users backup
22:     config C:\Backup\Backup.LST
23:   client myClient
24:     protocol nfs
25:     users backup root
26:     hostname myClient
27:     config /home/User/hbackup.list
28:   client newClient
29:     protocol ssh
30:     option username user
31:     option password p4sS?
32:     config /home/Blah/hbackup.list
33:   client other
34:     protocol none
35:     hostname otherClient
36:     option username foo
37:     option password bar
38:     config /home/Blah/hbackup.list
39:     filter and subdir
40:       condition path_start subdir
41:       condition !size< 100
42:     filter and bigfile
43:       condition size>= 10
44:       condition type file
45:     expire 1
46:     path test2//
47:     path test1
48:       filter and not_object
49:         condition !path_end .o
50:       filter or to_be_ignored
51:         condition filter subdir
52:         condition filter backup
53:         condition !filter not_object
54:       ignore to_be_ignored
55:       compress bigfile
56:       parser cvs controlled
57:       parser svn modified
58:   client myhost
59:     report_copy_error_once
60:     protocol file
61:     hostname myhost.mynetwork.lan
62:     timeout_nowarning
63:     config etc/localhost.list
64:     expire 1
65:   client client xp
66:     ignore backup
67:     protocol smb
68:     option username Myself
69:     option password flesyM
70:     option nocase
71:     hostname myClient
72:     config C:\Backup\Backup.LST
73:   client aClient vista
74:     protocol smb
75:     filter and huge_file
76:       condition !filter backup
77:       condition !size< 100
78:     path C:\Test Dir
79:       filter and compress_m
80:         condition !filter huge_file
81:       compress compress_m
82:       ignore backup
83:       parser svn modified
84:     report_copy_error_once
Config:
1:   log hbackup.log
2:     max_lines 100000
3:     backups 10
4:     level verbose
5:   db test_db
6:     compress auto
7:     compress_auto
8:   parsers_dir ../../../parsers/.libs
9:   filter all nothing
10:     condition type pipe
11:     condition size> 10
12:   ignore nothing
13:   filter all backup
14:     condition type file
15:     condition path_end ~
16:   filter any test_or
17:     condition filter backup
18:     condition !size< 1000
19:   client myClient xp
20:     protocol smb
21:     users backup
22:     config C:\Backup\Backup.LST
23:   client myClient
24:     protocol nfs
25:     users backup root
26:     hostname myClient
27:     config /home/User/hbackup.list
28:   client newClient
29:     protocol ssh
30:     option username user
31:     option password p4sS?
32:     config /home/Blah/hbackup.list
33:   client other
34:     protocol none
35:     hostname otherClient
36:     option username foo
37:     option password bar
38:     config /home/Blah/hbackup.list
39:     filter and subdir
40:       condition path_start subdir
41:       condition !size< 100
42:     filter and bigfile
43:       condition size>= 10
44:       condition type file
45:     expire 1
46:     path test2//
47:     path test1
48:       filter and not_object
49:         condition !path_end .o
50:       filter or to_be_ignored
51:         condition filter subdir
52:         condition filter backup
53:         condition !filter not_object
54:       ignore to_be_ignored
55:       compress bigfile
56:       parser cvs controlled
57:       parser svn modified
58:   client myhost
59:     report_copy_error_once
60:     protocol file
61:     hostname myhost.mynetwork.lan
62:     timeout_nowarning
63:     config etc/localhost.list
64:     expire 1
65:   client client xp
66:     ignore backup
67:     protocol smb
68:     option username Myself
69:     option password flesyM
70:     option nocase
71:     hostname myClient
72:     config C:\Backup\Backup.LST
73:   client aClient vista
74:     protocol smb
75:     filter and huge_file
76:       condition !filter backup
77:       condition !size< 100
78:     path C:\Test Dir
79:       filter and compress_m
80:         condition !filter huge_file
81:       compress compress_m
82:       ignore backup
83:       parser svn modified
84:     report_copy_error_once
Test: broken configuration
failed to read config!
Error: after line 0: need at most 1 occurence(s) of keyword 'db'
Error: after line 0: need at most 1 occurence(s) of keyword 'report_copy_error_once'
Error: at line 7: keyword 'filter' requires 2 parameter(s), found 1
Error: after line 11: missing keyword 'condition'
Error: after line 13: need at most 1 occurence(s) of keyword 'ignore'
Error: at line 15: keyword 'users' requires at least 1 parameter(s), found 0
Error: at line 17: keyword 'ignore' requires 1 parameter(s), found 0
Error: after line 19: need at most 1 occurence(s) of keyword 'config'
Error: after line 19: need at most 1 occurence(s) of keyword 'expire'
Error: after line 19: need at most 1 occurence(s) of keyword 'hostname'
Error: at line 23: keyword 'option' requires at most 2 parameter(s), found 3
Error: at line 24: keyword 'option' requires at least 1 parameter(s), found 0
Error: at line 32: keyword 'filter' requires 2 parameter(s), found 3
Error: at line 33: keyword 'condition' requires 2 parameter(s), found 3
Error: at line 34: keyword 'condition' requires 2 parameter(s), found 1
Error: at line 37: keyword 'expire' requires 1 parameter(s), found 2
Error: after line 41: need at most 1 occurence(s) of keyword 'compress'
Error: after line 41: need at most 1 occurence(s) of keyword 'ignore'
Error: after line 51: missing keyword 'condition'
Error: at line 53: keyword 'filter' requires 2 parameter(s), found 1
Error: after line 53: missing keyword 'condition'
Error: after line 65: missing keyword 'protocol'
Error: at line 71: keyword 'ignore' requires 1 parameter(s), found 2
Error: at line 72: keyword 'compress' requires 1 parameter(s), found 2
Error: at line 85: keyword 'ignore' requires 1 parameter(s), found 0
Error: at line 86: keyword 'compress' requires 1 parameter(s), found 0
Error: at line 88: keyword 'what_the_f...?' incorrect or misplaced, aborting
0: root
1:   db test_db
2:   db blah
4:   report_copy_error_once
5:   report_copy_error_once
Config:
1:   db test_db
2:   db blah
4:   report_copy_error_once
5:   report_copy_error_once
7:   filter all
8:     condition type file
9:     condition path_end ~
11:   filter any test_or
13:   client myClient
14:     protocol nfs
15:     users
16:     ignore test_or
17:     ignore
19:   client other
20:     protocol ssh
21:     hostname otherClient
22:     hostname 192.168.0.132
23:     option I am happy
24:     option
25:     config /home/backup/Backup.list
26:     config /home/backup/Backup2.list
28:     filter and subdir
29:       condition path_start subdir
30:       condition !size< 100
32:     filter and bigfile 3
33:       condition size>= 10 yeah
34:       condition type
36:     expire 1
37:     expire 2 3
39:     path test2//
41:     path test1
43:       filter and not_object
44:         condition !path_end .o
46:       filter or to_be_ignored
47:         condition filter subdir
48:         condition filter backup
49:         condition !filter not_object
51:       filter and blah
53:       filter or
56:       ignore to_be_ignored
57:       ignore to_be_ignored2
59:       compress bigfile
60:       compress bigfile2
62:       parser cvs controlled
63:       parser svn modified
65:   client myhost
66:     hostname myhost.mynetwork.lan
67:     config etc/localhost.list
68:     expire 1
70:     path blah
71:       ignore 2 3
72:       compress 4 5
74:   client client xp
75:     protocol smb
76:     option username Myself
77:     option password flesyM
78:     option nocase
79:     hostname myClient
80:     config C:\Backup\Backup.LST
82:     path C:\Crash"
83:     path C:\Crash
84:     path blah
85:       ignore
86:       compress
