Report tests

Default behaviour
default level
ALERT! alert level
Error: error level
Warning: warning level
info level

Verbosity level: alert
ALERT! alert level

Verbosity level: error
ALERT! alert level
Error: error level

Verbosity level: warning
ALERT! alert level
Error: error level
Warning: warning level

Verbosity level: info
default level
ALERT! alert level
Error: error level
Warning: warning level
info level

Verbosity level: verbose
default level
ALERT! alert level
Error: error level
Warning: warning level
info level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level

Verbosity level: debug
default level
ALERT! alert level
Error: error level
Warning: warning level
info level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level
debug level
debug 0 level
 -> debug 1 level
 --> debug 2 level

Verbosity level: regression
default level
ALERT! alert level
Error: error level
Warning: warning level
info level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level
debug level
debug 0 level
 -> debug 1 level
 --> debug 2 level
regression level

Line autoblanking
\r
Short line\r
A longer line\r
Tiny one     \r
.       \r
A longer line\r
An even longer line\r
A normal line      

Macros
ALERT! message: alert
Error: message: error
Warning: message: warning
message: info
message: verbose
message: debug
message: regression
temporary message: info\r
temporary message: verbose\r
temporary message: debug  \r
                        \r

Log to file

Error logging to file
Error: No such file or directory creating log file: 'missing/report.log'

Rotate file
report.log:
2009-08-07 06:05:04 DEBUG report_test.cpp:208 message: debug
report.log-1:
2009-08-07 06:05:04 VERB  report_test.cpp:207 message: verbose
report.log-2:
2009-08-07 06:05:04 INFO  report_test.cpp:206 message: info
report.log-3:
2009-08-07 06:05:04 WARN  report_test.cpp:205 message: warning
report.log-4:
2009-08-07 06:05:04 ERROR report_test.cpp:204 message: error
report.log-5:
2009-08-07 06:05:04 ALERT report_test.cpp:203 message: alert
report.log:
report.log-1:
2009-08-07 06:05:04 DEBUG report_test.cpp:208 message: debug
report.log-2:
2009-08-07 06:05:04 VERB  report_test.cpp:207 message: verbose
report.log-3:
2009-08-07 06:05:04 INFO  report_test.cpp:206 message: info
report.log-4:
2009-08-07 06:05:04 WARN  report_test.cpp:205 message: warning
report.log-5:
2009-08-07 06:05:04 ERROR report_test.cpp:204 message: error
report.log:
report.log-1:
2009-08-07 06:05:04 DEBUG report_test.cpp:208 message: debug
report.log-2:
2009-08-07 06:05:04 VERB  report_test.cpp:207 message: verbose
report.log-3:
2009-08-07 06:05:04 INFO  report_test.cpp:206 message: info
report.log-4:
2009-08-07 06:05:04 WARN  report_test.cpp:205 message: warning
report.log-5:
2009-08-07 06:05:04 ERROR report_test.cpp:204 message: error
report.log:
report.log-1:
1
report.log-2:
2009-08-07 06:05:04 DEBUG report_test.cpp:208 message: debug
report.log-3:
2009-08-07 06:05:04 VERB  report_test.cpp:207 message: verbose
report.log-4:
2009-08-07 06:05:04 INFO  report_test.cpp:206 message: info
report.log-5:
2009-08-07 06:05:04 WARN  report_test.cpp:205 message: warning
report.log:
report.log-1:
1
report.log-2:
1
report.log-3:
2009-08-07 06:05:04 DEBUG report_test.cpp:208 message: debug
report.log-4:
2009-08-07 06:05:04 VERB  report_test.cpp:207 message: verbose
report.log-5:
2009-08-07 06:05:04 INFO  report_test.cpp:206 message: info
report.log:
report.log-1:
1
report.log-2:
1
report.log-3:
1
report.log-4:
2009-08-07 06:05:04 DEBUG report_test.cpp:208 message: debug
report.log-5:
2009-08-07 06:05:04 VERB  report_test.cpp:207 message: verbose
report.log:
report.log-1:
1
report.log-2:
1
report.log-3:
1
report.log-4:
2009-08-07 06:05:04 DEBUG report_test.cpp:208 message: debug
report.log-5:
2009-08-07 06:05:04 VERB  report_test.cpp:207 message: verbose

End of tests
