Report tests

Default behaviour
default level
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level
info level
info 0 level
 -> info 1 level
 --> info 2 level

Verbosity level: alert
ALERT! alert level
ALERT! alert 0 level

Verbosity level: error
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level

Verbosity level: warning
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level

Verbosity level: info
default level
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level
info level
info 0 level
 -> info 1 level
 --> info 2 level

Verbosity level: verbose
default level
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level
info level
info 0 level
 -> info 1 level
 --> info 2 level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level

Verbosity level: debug
default level
ALERT! alert level
ALERT! alert 0 level
Error: error level
Error: error 0 level
Warning: warning level
Warning: warning 0 level
Warning:  -> warning 1 level
Warning:  --> warning 2 level
info level
info 0 level
 -> info 1 level
 --> info 2 level
verbose level
verbose 0 level
 -> verbose 1 level
 --> verbose 2 level
debug level
debug 0 level
 -> debug 1 level
 --> debug 2 level

Line autoblanking
\r
Short line\r
A longer line\r
Tiny one     \r
.       \r
A longer line\r
An even longer line\r
A normal line      

Macros
ALERT! message: alert
Error: message: error
Warning: message: warning
message: info
message: verbose
message: debug
temporary message: info\r
temporary message: verbose\r
temporary message: debug  \r
                        \r

Log to file

Error logging to file
Error: No such file or directory creating log file: 'missing/report.log'

Rotate file
report.log:
2009-08-07 06:05:04 report_test.cpp:239 DEBUG message: debug
report.log-1:
2009-08-07 06:05:04 report_test.cpp:238 VERB  message: verbose
report.log-2:
2009-08-07 06:05:04 report_test.cpp:237 INFO  message: info
report.log-3:
2009-08-07 06:05:04 report_test.cpp:236 WARN  message: warning
report.log-4:
2009-08-07 06:05:04 report_test.cpp:235 ERROR message: error
report.log-5:
2009-08-07 06:05:04 report_test.cpp:234 ALERT message: alert
report.log:
report.log-1:
2009-08-07 06:05:04 report_test.cpp:239 DEBUG message: debug
report.log-2:
2009-08-07 06:05:04 report_test.cpp:238 VERB  message: verbose
report.log-3:
2009-08-07 06:05:04 report_test.cpp:237 INFO  message: info
report.log-4:
2009-08-07 06:05:04 report_test.cpp:236 WARN  message: warning
report.log-5:
2009-08-07 06:05:04 report_test.cpp:235 ERROR message: error
report.log:
report.log-1:
2009-08-07 06:05:04 report_test.cpp:239 DEBUG message: debug
report.log-2:
2009-08-07 06:05:04 report_test.cpp:238 VERB  message: verbose
report.log-3:
2009-08-07 06:05:04 report_test.cpp:237 INFO  message: info
report.log-4:
2009-08-07 06:05:04 report_test.cpp:236 WARN  message: warning
report.log-5:
2009-08-07 06:05:04 report_test.cpp:235 ERROR message: error
report.log:
report.log-1:
1
report.log-2:
2009-08-07 06:05:04 report_test.cpp:239 DEBUG message: debug
report.log-3:
2009-08-07 06:05:04 report_test.cpp:238 VERB  message: verbose
report.log-4:
2009-08-07 06:05:04 report_test.cpp:237 INFO  message: info
report.log-5:
2009-08-07 06:05:04 report_test.cpp:236 WARN  message: warning
report.log:
report.log-1:
1
report.log-2:
1
report.log-3:
2009-08-07 06:05:04 report_test.cpp:239 DEBUG message: debug
report.log-4:
2009-08-07 06:05:04 report_test.cpp:238 VERB  message: verbose
report.log-5:
2009-08-07 06:05:04 report_test.cpp:237 INFO  message: info
report.log:
report.log-1:
1
report.log-2:
1
report.log-3:
1
report.log-4:
2009-08-07 06:05:04 report_test.cpp:239 DEBUG message: debug
report.log-5:
2009-08-07 06:05:04 report_test.cpp:238 VERB  message: verbose
report.log:
report.log-1:
1
report.log-2:
1
report.log-3:
1
report.log-4:
2009-08-07 06:05:04 report_test.cpp:239 DEBUG message: debug
report.log-5:
2009-08-07 06:05:04 report_test.cpp:238 VERB  message: verbose

End of tests
